/* eslint-disable */
/* Code generated by ng-openapi-gen DO NOT EDIT. */

import { HttpClient, HttpContext, HttpResponse } from '@angular/common/http';
import { Observable } from 'rxjs';
import { filter, map } from 'rxjs/operators';
import { StrictHttpResponse } from '../../strict-http-response';
import { RequestBuilder } from '../../request-builder';

import { AiUser } from '../../models/ai-user';
import { Identifier } from '../../models/Identifier';
export type IdentifierLike = Identifier | string;



export interface ServiceAiUserGet$Params {

/**
 * The identifier of a resource
 */
  id: IdentifierLike;
}

export function serviceAiUserGet(http: HttpClient, rootUrl: string, params: ServiceAiUserGet$Params, context?: HttpContext): Observable<StrictHttpResponse<AiUser>> {
  const rb = new RequestBuilder(rootUrl, serviceAiUserGet.PATH, 'get');
  if (params) {
    rb.path('id', String(params.id), {});
  }

  return http.request(
    rb.build({ responseType: 'json', accept: 'application/json', context })
  ).pipe(
    filter((r: any): r is HttpResponse<any> => r instanceof HttpResponse),
    map((r: HttpResponse<any>) => {
      return r as StrictHttpResponse<AiUser>;
    })
  );
}

serviceAiUserGet.PATH = '/aiuser/{id}';

export { serviceAiUserGet as get };
