/* eslint-disable */
/* Code generated by ng-openapi-gen DO NOT EDIT. */

import { HttpClient, HttpContext, HttpResponse } from '@angular/common/http';
import { Observable } from 'rxjs';
import { filter, map } from 'rxjs/operators';
import { StrictHttpResponse } from '../../strict-http-response';
import { RequestBuilder } from '../../request-builder';

import { DatabaseBackup } from '../../models/database-backup';
import { Identifier } from '../../models/Identifier';
export type IdentifierLike = Identifier | string;



export interface ServiceLocalDatabaseGet$Params {

/**
 * The identifier of a resource
 */
  id: IdentifierLike;
}

export function serviceLocalDatabaseGet(http: HttpClient, rootUrl: string, params: ServiceLocalDatabaseGet$Params, context?: HttpContext): Observable<StrictHttpResponse<DatabaseBackup>> {
  const rb = new RequestBuilder(rootUrl, serviceLocalDatabaseGet.PATH, 'get');
  if (params) {
    rb.path('id', String(params.id), {});
  }

  return http.request(
    rb.build({ responseType: 'json', accept: 'application/json', context })
  ).pipe(
    filter((r: any): r is HttpResponse<any> => r instanceof HttpResponse),
    map((r: HttpResponse<any>) => {
      return r as StrictHttpResponse<DatabaseBackup>;
    })
  );
}

serviceLocalDatabaseGet.PATH = '/localdatabase/{id}';

export { serviceLocalDatabaseGet as get };
