/* eslint-disable */
/* Code generated by ng-openapi-gen DO NOT EDIT. */

import { HttpClient, HttpContext, HttpResponse } from '@angular/common/http';
import { Observable } from 'rxjs';
import { filter, map } from 'rxjs/operators';
import { StrictHttpResponse } from '../../strict-http-response';
import { RequestBuilder } from '../../request-builder';
import { Identifier } from '../../models/Identifier';
export type IdentifierLike = Identifier | string;




export interface ServiceAlbumMetricsErase$Params {

/**
 * The identifier of a resource
 */
  id: IdentifierLike;
}

export function serviceAlbumMetricsErase(http: HttpClient, rootUrl: string, params: ServiceAlbumMetricsErase$Params, context?: HttpContext): Observable<StrictHttpResponse<void>> {
  const rb = new RequestBuilder(rootUrl, serviceAlbumMetricsErase.PATH, 'delete');
  if (params) {
    rb.path('id', String(params.id), {});
  }

  return http.request(
    rb.build({ responseType: 'text', accept: '*/*', context })
  ).pipe(
    filter((r: any): r is HttpResponse<any> => r instanceof HttpResponse),
    map((r: HttpResponse<any>) => {
      return (r as HttpResponse<any>).clone({ body: undefined }) as StrictHttpResponse<void>;
    })
  );
}

serviceAlbumMetricsErase.PATH = '/albummetrics/{id}';

export { serviceAlbumMetricsErase as erase };
