/* eslint-disable */
/* Code generated by ng-openapi-gen DO NOT EDIT. */

import { HttpClient, HttpContext, HttpResponse } from '@angular/common/http';
import { Observable } from 'rxjs';
import { filter, map } from 'rxjs/operators';
import { StrictHttpResponse } from '../../strict-http-response';
import { RequestBuilder } from '../../request-builder';

import { AlbumMetrics } from '../../models/album-metrics';
import { Identifier } from '../../models/Identifier';
export type IdentifierLike = Identifier | string;



export interface ServiceAlbumMetricsGet$Params {

/**
 * The identifier of a resource
 */
  id: IdentifierLike;
}

export function serviceAlbumMetricsGet(http: HttpClient, rootUrl: string, params: ServiceAlbumMetricsGet$Params, context?: HttpContext): Observable<StrictHttpResponse<AlbumMetrics>> {
  const rb = new RequestBuilder(rootUrl, serviceAlbumMetricsGet.PATH, 'get');
  if (params) {
    rb.path('id', String(params.id), {});
  }

  return http.request(
    rb.build({ responseType: 'json', accept: 'application/json', context })
  ).pipe(
    filter((r: any): r is HttpResponse<any> => r instanceof HttpResponse),
    map((r: HttpResponse<any>) => {
      return r as StrictHttpResponse<AlbumMetrics>;
    })
  );
}

serviceAlbumMetricsGet.PATH = '/albummetrics/{id}';

export { serviceAlbumMetricsGet as get };
