/* eslint-disable */
/* Code generated by ng-openapi-gen DO NOT EDIT. */

import { HttpClient, HttpContext, HttpResponse } from '@angular/common/http';
import { Observable } from 'rxjs';
import { filter, map } from 'rxjs/operators';
import { StrictHttpResponse } from '../../strict-http-response';
import { RequestBuilder } from '../../request-builder';

import { MetricsChartEntry } from '../../models/metrics-chart-entry';
import { Identifier } from '../../models/Identifier';
export type IdentifierLike = Identifier | string;



export interface ServiceAlbumMetricsGetChartData$Params {

/**
 * the name of a Filter resource
 */
  filterName?: string;

/**
 * input parameter for the filter use ';' to separate values
 */
  values?: string;
  sortBy?: 'date' | 'label' | 'value';
  orderBy?: 'ASC' | 'DESC' | 'RANDOM';
  pageIndex?: number;
}

export function serviceAlbumMetricsGetChartData(http: HttpClient, rootUrl: string, params?: ServiceAlbumMetricsGetChartData$Params, context?: HttpContext): Observable<StrictHttpResponse<Array<MetricsChartEntry>>> {
  const rb = new RequestBuilder(rootUrl, serviceAlbumMetricsGetChartData.PATH, 'get');
  if (params) {
    rb.query('filterName', params.filterName, {});
    rb.query('values', params.values, {});
    rb.query('sortBy', params.sortBy, {});
    rb.query('orderBy', params.orderBy, {});
    rb.query('pageIndex', params.pageIndex, {});
  }

  return http.request(
    rb.build({ responseType: 'json', accept: 'application/json', context })
  ).pipe(
    filter((r: any): r is HttpResponse<any> => r instanceof HttpResponse),
    map((r: HttpResponse<any>) => {
      return r as StrictHttpResponse<Array<MetricsChartEntry>>;
    })
  );
}

serviceAlbumMetricsGetChartData.PATH = '/albummetrics/getchartdata';

export { serviceAlbumMetricsGetChartData as getChartData };
