/* eslint-disable */
/* Code generated by ng-openapi-gen DO NOT EDIT. */

import { HttpClient, HttpContext, HttpResponse } from '@angular/common/http';
import { Observable } from 'rxjs';
import { filter, map } from 'rxjs/operators';
import { StrictHttpResponse } from '../../strict-http-response';
import { RequestBuilder } from '../../request-builder';

import { PlaylistMetrics } from '../../models/playlist-metrics';
import { Identifier } from '../../models/Identifier';
export type IdentifierLike = Identifier | string;



export interface ServicePlaylistMetricsGetPage$Params {

/**
 * the name of a Filter resource
 */
  filterName?: string;

/**
 * input parameter for the filter use ';' to separate values
 */
  values?: string;
  sortBy?: 'playDuration' | 'totalPlays' | 'totalSongPlays' | 'completed' | 'skipCount' | 'skipRate' | 'lastPlayed' | 'firstPlayed' | 'month';
  orderBy?: 'ASC' | 'DESC' | 'RANDOM';
  pageIndex?: number;
}

export function servicePlaylistMetricsGetPage(http: HttpClient, rootUrl: string, params?: ServicePlaylistMetricsGetPage$Params, context?: HttpContext): Observable<StrictHttpResponse<Array<PlaylistMetrics>>> {
  const rb = new RequestBuilder(rootUrl, servicePlaylistMetricsGetPage.PATH, 'get');
  if (params) {
    rb.query('filterName', params.filterName, {});
    rb.query('values', params.values, {});
    rb.query('sortBy', params.sortBy, {});
    rb.query('orderBy', params.orderBy, {});
    rb.query('pageIndex', params.pageIndex, {});
  }

  return http.request(
    rb.build({ responseType: 'json', accept: 'application/json', context })
  ).pipe(
    filter((r: any): r is HttpResponse<any> => r instanceof HttpResponse),
    map((r: HttpResponse<any>) => {
      return r as StrictHttpResponse<Array<PlaylistMetrics>>;
    })
  );
}

servicePlaylistMetricsGetPage.PATH = '/playlistmetrics';

export { servicePlaylistMetricsGetPage as getPage };
