/* eslint-disable */
/* Code generated by ng-openapi-gen DO NOT EDIT. */

import { HttpClient, HttpContext, HttpResponse } from '@angular/common/http';
import { Observable } from 'rxjs';
import { filter, map } from 'rxjs/operators';
import { StrictHttpResponse } from '../../strict-http-response';
import { RequestBuilder } from '../../request-builder';

import { Album } from '../../models/album';
import { Artist } from '../../models/artist';
import { Playlist } from '../../models/playlist';
import { Song } from '../../models/song';
import { Identifier } from '../../models/Identifier';
export type IdentifierLike = Identifier | string;



export interface ServiceMusicElementGet$Params {

/**
 * The identifier of a resource
 */
  id: IdentifierLike;
}

export function serviceMusicElementGet(http: HttpClient, rootUrl: string, params: ServiceMusicElementGet$Params, context?: HttpContext): Observable<StrictHttpResponse<(Song | Album | Artist | Playlist)>> {
  const rb = new RequestBuilder(rootUrl, serviceMusicElementGet.PATH, 'get');
  if (params) {
    rb.path('id', String(params.id), {});
  }

  return http.request(
    rb.build({ responseType: 'json', accept: 'application/json', context })
  ).pipe(
    filter((r: any): r is HttpResponse<any> => r instanceof HttpResponse),
    map((r: HttpResponse<any>) => {
      return r as StrictHttpResponse<(Song | Album | Artist | Playlist)>;
    })
  );
}

serviceMusicElementGet.PATH = '/musicelement/{id}';

export { serviceMusicElementGet as get };
