/* eslint-disable */
/* Code generated by ng-openapi-gen DO NOT EDIT. */

import { HttpClient, HttpContext, HttpResponse } from '@angular/common/http';
import { Observable } from 'rxjs';
import { filter, map } from 'rxjs/operators';
import { StrictHttpResponse } from '../../strict-http-response';
import { RequestBuilder } from '../../request-builder';
import { Identifier } from '../../models/Identifier';
export type IdentifierLike = Identifier | string;




export interface ServiceFilePayloadGetInProgressCount$Params {
}

export function serviceFilePayloadGetInProgressCount(http: HttpClient, rootUrl: string, params?: ServiceFilePayloadGetInProgressCount$Params, context?: HttpContext): Observable<StrictHttpResponse<number>> {
  const rb = new RequestBuilder(rootUrl, serviceFilePayloadGetInProgressCount.PATH, 'get');
  if (params) {
  }

  return http.request(
    rb.build({ responseType: 'json', accept: 'application/json', context })
  ).pipe(
    filter((r: any): r is HttpResponse<any> => r instanceof HttpResponse),
    map((r: HttpResponse<any>) => {
      return (r as HttpResponse<any>).clone({ body: parseFloat(String((r as HttpResponse<any>).body)) }) as StrictHttpResponse<number>;
    })
  );
}

serviceFilePayloadGetInProgressCount.PATH = '/filepayload/getinprogresscount';

export { serviceFilePayloadGetInProgressCount as getInProgressCount };
