/* eslint-disable */
/* Code generated by ng-openapi-gen DO NOT EDIT. */

import { HttpClient, HttpContext, HttpResponse } from '@angular/common/http';
import { Observable } from 'rxjs';
import { filter, map } from 'rxjs/operators';
import { StrictHttpResponse } from '../../strict-http-response';
import { RequestBuilder } from '../../request-builder';

import { Filter } from '../../models/filter';
import { Identifier } from '../../models/Identifier';
export type IdentifierLike = Identifier | string;



export interface ServiceFilterGet$Params {

/**
 * The identifier of a resource
 */
  id: IdentifierLike;
}

export function serviceFilterGet(http: HttpClient, rootUrl: string, params: ServiceFilterGet$Params, context?: HttpContext): Observable<StrictHttpResponse<Filter>> {
  const rb = new RequestBuilder(rootUrl, serviceFilterGet.PATH, 'get');
  if (params) {
    rb.path('id', String(params.id), {});
  }

  return http.request(
    rb.build({ responseType: 'json', accept: 'application/json', context })
  ).pipe(
    filter((r: any): r is HttpResponse<any> => r instanceof HttpResponse),
    map((r: HttpResponse<any>) => {
      return r as StrictHttpResponse<Filter>;
    })
  );
}

serviceFilterGet.PATH = '/filter/{id}';

export { serviceFilterGet as get };
