/* eslint-disable */
/* Code generated by ng-openapi-gen DO NOT EDIT. */

import { HttpClient, HttpContext, HttpResponse } from '@angular/common/http';
import { Observable } from 'rxjs';
import { filter, map } from 'rxjs/operators';
import { StrictHttpResponse } from '../../strict-http-response';
import { RequestBuilder } from '../../request-builder';

import { SongMetrics } from '../../models/song-metrics';
import { Identifier } from '../../models/Identifier';
export type IdentifierLike = Identifier | string;



export interface ServiceSongMetricsGet$Params {

/**
 * The identifier of a resource
 */
  id: IdentifierLike;
}

export function serviceSongMetricsGet(http: HttpClient, rootUrl: string, params: ServiceSongMetricsGet$Params, context?: HttpContext): Observable<StrictHttpResponse<SongMetrics>> {
  const rb = new RequestBuilder(rootUrl, serviceSongMetricsGet.PATH, 'get');
  if (params) {
    rb.path('id', String(params.id), {});
  }

  return http.request(
    rb.build({ responseType: 'json', accept: 'application/json', context })
  ).pipe(
    filter((r: any): r is HttpResponse<any> => r instanceof HttpResponse),
    map((r: HttpResponse<any>) => {
      return r as StrictHttpResponse<SongMetrics>;
    })
  );
}

serviceSongMetricsGet.PATH = '/songmetrics/{id}';

export { serviceSongMetricsGet as get };
