# coding: utf-8

"""
    MyMusik API

    MyMusik is an music player platform for offline music.  The API is object based. Each object has base methods: Insert, Update, Get, Get-Page, Erase.  Insert and Update always require a complete object. Every property must be present. Empty values are allowed.  For Insert the id is empty. The generated id is returned in the Location header.  Get requires only the object id. Get-Page uses a separate Filter object with Condition objects.  There are predefined filters available for example <ObjectName>By<PropertyName> lets you filter pages by any property. Additional actions are defined per path and may vary. Some enum values are placeholders for future features.  The API is protected using access tokens. By default remote access is disabled. You can enable it in settings but do so carefully.

    The version of the OpenAPI document: 1.0.0
    Contact: info@shaggai.email
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest

from mymusik_client.api.cloud_storage_api import CloudStorageApi


class TestCloudStorageApi(unittest.TestCase):
    """CloudStorageApi unit test stubs"""

    def setUp(self) -> None:
        self.api = CloudStorageApi()

    def tearDown(self) -> None:
        pass

    def test_service_cloud_storage_get(self) -> None:
        """Test case for service_cloud_storage_get

        Returns an CloudStorage using an id
        """
        pass

    def test_service_cloud_storage_get_page(self) -> None:
        """Test case for service_cloud_storage_get_page

        Returns CloudStorage(s) using an filter.       Add an filter by using the '/filter' and '/condition' paths.      You can sort them by an property
        """
        pass

    def test_service_cloud_storage_get_storage_left(self) -> None:
        """Test case for service_cloud_storage_get_storage_left

        Retrieves the left storage in bytes available.
        """
        pass

    def test_service_cloud_storage_get_used_storage(self) -> None:
        """Test case for service_cloud_storage_get_used_storage

        Retrieves the total storage in bytes available for the year.
        """
        pass


if __name__ == '__main__':
    unittest.main()
