# coding: utf-8

"""
    MyMusik API

    MyMusik is an music player platform for offline music.  The API is object based. Each object has base methods: Insert, Update, Get, Get-Page, Erase.  Insert and Update always require a complete object. Every property must be present. Empty values are allowed.  For Insert the id is empty. The generated id is returned in the Location header.  Get requires only the object id. Get-Page uses a separate Filter object with Condition objects.  There are predefined filters available for example <ObjectName>By<PropertyName> lets you filter pages by any property. Additional actions are defined per path and may vary. Some enum values are placeholders for future features.  The API is protected using access tokens. By default remote access is disabled. You can enable it in settings but do so carefully.

    The version of the OpenAPI document: 1.0.0
    Contact: info@shaggai.email
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest

from mymusik_client.api.local_storage_api import LocalStorageApi


class TestLocalStorageApi(unittest.TestCase):
    """LocalStorageApi unit test stubs"""

    def setUp(self) -> None:
        self.api = LocalStorageApi()

    def tearDown(self) -> None:
        pass

    def test_service_local_storage_enqueue_cover_images_for_grid_prefetch(self) -> None:
        """Test case for service_local_storage_enqueue_cover_images_for_grid_prefetch

        Queues cover image identifiers for background prefetch downloads.
        """
        pass

    def test_service_local_storage_enqueue_library_cover_images_prefetch(self) -> None:
        """Test case for service_local_storage_enqueue_library_cover_images_prefetch

        Queues all visible library cover image identifiers for background prefetch downloads.
        """
        pass

    def test_service_local_storage_get(self) -> None:
        """Test case for service_local_storage_get

        Returns an LocalStorage using an id
        """
        pass

    def test_service_local_storage_get_page(self) -> None:
        """Test case for service_local_storage_get_page

        Returns LocalStorage(s) using an filter.       Add an filter by using the '/filter' and '/condition' paths.      You can sort them by an property
        """
        pass


if __name__ == '__main__':
    unittest.main()
