# coding: utf-8

"""
    MyMusik API

    MyMusik is an music player platform for offline music.  The API is object based. Each object has base methods: Insert, Update, Get, Get-Page, Erase.  Insert and Update always require a complete object. Every property must be present. Empty values are allowed.  For Insert the id is empty. The generated id is returned in the Location header.  Get requires only the object id. Get-Page uses a separate Filter object with Condition objects.  There are predefined filters available for example <ObjectName>By<PropertyName> lets you filter pages by any property. Additional actions are defined per path and may vary. Some enum values are placeholders for future features.  The API is protected using access tokens. By default remote access is disabled. You can enable it in settings but do so carefully.

    The version of the OpenAPI document: 1.0.0
    Contact: info@shaggai.email
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest

from mymusik_client.api.ai_music_voice_command_api import AiMusicVoiceCommandApi


class TestAiMusicVoiceCommandApi(unittest.TestCase):
    """AiMusicVoiceCommandApi unit test stubs"""

    def setUp(self) -> None:
        self.api = AiMusicVoiceCommandApi()

    def tearDown(self) -> None:
        pass

    def test_service_ai_music_voice_command_count(self) -> None:
        """Test case for service_ai_music_voice_command_count

        Get the count of voice commands.
        """
        pass

    def test_service_ai_music_voice_command_current_duration(self) -> None:
        """Test case for service_ai_music_voice_command_current_duration

        Get current recording duration in seconds.
        """
        pass

    def test_service_ai_music_voice_command_erase(self) -> None:
        """Test case for service_ai_music_voice_command_erase

        Deletes an AiMusicVoiceCommand using an id
        """
        pass

    def test_service_ai_music_voice_command_get(self) -> None:
        """Test case for service_ai_music_voice_command_get

        Returns an AiMusicVoiceCommand using an id
        """
        pass

    def test_service_ai_music_voice_command_get_page(self) -> None:
        """Test case for service_ai_music_voice_command_get_page

        Returns AiMusicVoiceCommand(s) using an filter.       Add an filter by using the '/filter' and '/condition' paths.      You can sort them by an property
        """
        pass

    def test_service_ai_music_voice_command_insert(self) -> None:
        """Test case for service_ai_music_voice_command_insert

        Creates an AiMusicVoiceCommand. You can pass an empty id, it will then create one.
        """
        pass

    def test_service_ai_music_voice_command_report(self) -> None:
        """Test case for service_ai_music_voice_command_report

        Report a voice command result.
        """
        pass

    def test_service_ai_music_voice_command_retry_script_generation(self) -> None:
        """Test case for service_ai_music_voice_command_retry_script_generation

        Retry script generation from the stored transcript.
        """
        pass

    def test_service_ai_music_voice_command_start_voice_recording(self) -> None:
        """Test case for service_ai_music_voice_command_start_voice_recording

        Start recording audio for a voice command id.
        """
        pass

    def test_service_ai_music_voice_command_stop_and_delete_voice_recording(self) -> None:
        """Test case for service_ai_music_voice_command_stop_and_delete_voice_recording

        Cancel recording and mark the current voice command as cancelled.
        """
        pass

    def test_service_ai_music_voice_command_stop_voice_recording(self) -> None:
        """Test case for service_ai_music_voice_command_stop_voice_recording

        Stop recording and continue transcription and script generation.
        """
        pass

    def test_service_ai_music_voice_command_update(self) -> None:
        """Test case for service_ai_music_voice_command_update

        Updates an AiMusicVoiceCommand using an id
        """
        pass


if __name__ == '__main__':
    unittest.main()
