# coding: utf-8

"""
    MyMusik API

    MyMusik is an music player platform for offline music.  The API is object based. Each object has base methods: Insert, Update, Get, Get-Page, Erase.  Insert and Update always require a complete object. Every property must be present. Empty values are allowed.  For Insert the id is empty. The generated id is returned in the Location header.  Get requires only the object id. Get-Page uses a separate Filter object with Condition objects.  There are predefined filters available for example <ObjectName>By<PropertyName> lets you filter pages by any property. Additional actions are defined per path and may vary. Some enum values are placeholders for future features.  The API is protected using access tokens. By default remote access is disabled. You can enable it in settings but do so carefully.

    The version of the OpenAPI document: 1.0.0
    Contact: info@shaggai.email
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest

from mymusik_client.api.artist_metrics_api import ArtistMetricsApi


class TestArtistMetricsApi(unittest.TestCase):
    """ArtistMetricsApi unit test stubs"""

    def setUp(self) -> None:
        self.api = ArtistMetricsApi()

    def tearDown(self) -> None:
        pass

    def test_service_artist_metrics_erase(self) -> None:
        """Test case for service_artist_metrics_erase

        Deletes an ArtistMetrics using an id
        """
        pass

    def test_service_artist_metrics_get(self) -> None:
        """Test case for service_artist_metrics_get

        Returns an ArtistMetrics using an id
        """
        pass

    def test_service_artist_metrics_get_chart_data(self) -> None:
        """Test case for service_artist_metrics_get_chart_data

        Get artist metrics chart data
        """
        pass

    def test_service_artist_metrics_get_page(self) -> None:
        """Test case for service_artist_metrics_get_page

        Returns ArtistMetrics(s) using an filter.       Add an filter by using the '/filter' and '/condition' paths.      You can sort them by an property
        """
        pass


if __name__ == '__main__':
    unittest.main()
