# coding: utf-8

"""
    MyMusik API

    MyMusik is an music player platform for offline music.  The API is object based. Each object has base methods: Insert, Update, Get, Get-Page, Erase.  Insert and Update always require a complete object. Every property must be present. Empty values are allowed.  For Insert the id is empty. The generated id is returned in the Location header.  Get requires only the object id. Get-Page uses a separate Filter object with Condition objects.  There are predefined filters available for example <ObjectName>By<PropertyName> lets you filter pages by any property. Additional actions are defined per path and may vary. Some enum values are placeholders for future features.  The API is protected using access tokens. By default remote access is disabled. You can enable it in settings but do so carefully.

    The version of the OpenAPI document: 1.0.0
    Contact: info@shaggai.email
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest

from mymusik_client.api.album_identifier_api import AlbumIdentifierApi


class TestAlbumIdentifierApi(unittest.TestCase):
    """AlbumIdentifierApi unit test stubs"""

    def setUp(self) -> None:
        self.api = AlbumIdentifierApi()

    def tearDown(self) -> None:
        pass

    def test_service_album_identifier_download_artist_images_for_song(self) -> None:
        """Test case for service_album_identifier_download_artist_images_for_song

        Download artist images of a song.
        """
        pass

    def test_service_album_identifier_download_image_for_music_element(self) -> None:
        """Test case for service_album_identifier_download_image_for_music_element

        Download an image for an music element, playlists are not supported.
        """
        pass

    def test_service_album_identifier_erase(self) -> None:
        """Test case for service_album_identifier_erase

        Deletes an AlbumIdentifier using an id
        """
        pass

    def test_service_album_identifier_get(self) -> None:
        """Test case for service_album_identifier_get

        Returns an AlbumIdentifier using an id
        """
        pass

    def test_service_album_identifier_get_page(self) -> None:
        """Test case for service_album_identifier_get_page

        Returns AlbumIdentifier(s) using an filter.       Add an filter by using the '/filter' and '/condition' paths.      You can sort them by an property
        """
        pass


if __name__ == '__main__':
    unittest.main()
