# coding: utf-8

"""
    MyMusik API

    MyMusik is an music player platform for offline music.  The API is object based. Each object has base methods: Insert, Update, Get, Get-Page, Erase.  Insert and Update always require a complete object. Every property must be present. Empty values are allowed.  For Insert the id is empty. The generated id is returned in the Location header.  Get requires only the object id. Get-Page uses a separate Filter object with Condition objects.  There are predefined filters available for example <ObjectName>By<PropertyName> lets you filter pages by any property. Additional actions are defined per path and may vary. Some enum values are placeholders for future features.  The API is protected using access tokens. By default remote access is disabled. You can enable it in settings but do so carefully.

    The version of the OpenAPI document: 1.0.0
    Contact: info@shaggai.email
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest

from mymusik_client.api.queue_item_api import QueueItemApi


class TestQueueItemApi(unittest.TestCase):
    """QueueItemApi unit test stubs"""

    def setUp(self) -> None:
        self.api = QueueItemApi()

    def tearDown(self) -> None:
        pass

    def test_service_queue_item_add_album(self) -> None:
        """Test case for service_queue_item_add_album

        Adds albums to the queue.
        """
        pass

    def test_service_queue_item_add_container(self) -> None:
        """Test case for service_queue_item_add_container

        Adds a container (playlist, album) to the queue.
        """
        pass

    def test_service_queue_item_add_songs(self) -> None:
        """Test case for service_queue_item_add_songs

        Adds multiple songs to the queue.
        """
        pass

    def test_service_queue_item_clear(self) -> None:
        """Test case for service_queue_item_clear

        Clears all songs from the current queue.
        """
        pass

    def test_service_queue_item_count(self) -> None:
        """Test case for service_queue_item_count

        Get the count of the queue.
        """
        pass

    def test_service_queue_item_erase(self) -> None:
        """Test case for service_queue_item_erase

        Deletes an QueueItem using an id
        """
        pass

    def test_service_queue_item_get(self) -> None:
        """Test case for service_queue_item_get

        Returns an QueueItem using an id
        """
        pass

    def test_service_queue_item_get_page(self) -> None:
        """Test case for service_queue_item_get_page

        Returns QueueItem(s) using an filter.       Add an filter by using the '/filter' and '/condition' paths.      You can sort them by an property
        """
        pass

    def test_service_queue_item_get_queue_duration(self) -> None:
        """Test case for service_queue_item_get_queue_duration

        Calculates the total duration of all songs in the queue. (in seconds)
        """
        pass

    def test_service_queue_item_handle_items_moved_to_boundary(self) -> None:
        """Test case for service_queue_item_handle_items_moved_to_boundary

        Reposition items in the queue to start or end of queue.An action is defined in additionalValue and can be 'start' or 'end'.The items in ther queueitemlist are moved to the start or end of the queue
        """
        pass

    def test_service_queue_item_handle_items_repositioned(self) -> None:
        """Test case for service_queue_item_handle_items_repositioned

        Reposition items in the queue.The id of the list represents the target item id to do an action on.An action is defined in additionalValue and can be 'Before', 'After' or 'Swap'.The items in ther queueitemlist are moved before, after or swapped with the target item.
        """
        pass

    def test_service_queue_item_play_songs_after_next(self) -> None:
        """Test case for service_queue_item_play_songs_after_next

        Enqueues multiple songs to play immediately after the next track. This function allows users to add new songs to the queue without interrupting the currently playing song, ensuring the newly added songs are played right after the upcoming one.
        """
        pass

    def test_service_queue_item_play_songs_next(self) -> None:
        """Test case for service_queue_item_play_songs_next

        Adds multiple songs to the front of the queue, making them the next to play. This action shifts the current queue back, allowing for an immediate update to the listening order with the new selections.
        """
        pass

    def test_service_queue_item_remove_multiple(self) -> None:
        """Test case for service_queue_item_remove_multiple

        Removes multiple items from the queue.
        """
        pass

    def test_service_queue_item_set_queue_with_albums(self) -> None:
        """Test case for service_queue_item_set_queue_with_albums

        Replaces the current queue with a new set of albums.
        """
        pass

    def test_service_queue_item_set_queue_with_songs(self) -> None:
        """Test case for service_queue_item_set_queue_with_songs

        Replaces the current queue with a new set of songs.
        """
        pass

    def test_service_queue_item_shuffle(self) -> None:
        """Test case for service_queue_item_shuffle

        Randomizes the order of songs in the current queue without changing its contents.
        """
        pass

    def test_service_queue_item_skip_items_up_to(self) -> None:
        """Test case for service_queue_item_skip_items_up_to

        Skips items up to the selected item, removing the items before it from the queue.
        """
        pass

    def test_service_queue_item_update(self) -> None:
        """Test case for service_queue_item_update

        Updates an QueueItem using an id
        """
        pass


if __name__ == '__main__':
    unittest.main()
