# coding: utf-8

"""
    MyMusik API

    MyMusik is an music player platform for offline music.  The API is object based. Each object has base methods: Insert, Update, Get, Get-Page, Erase.  Insert and Update always require a complete object. Every property must be present. Empty values are allowed.  For Insert the id is empty. The generated id is returned in the Location header.  Get requires only the object id. Get-Page uses a separate Filter object with Condition objects.  There are predefined filters available for example <ObjectName>By<PropertyName> lets you filter pages by any property. Additional actions are defined per path and may vary. Some enum values are placeholders for future features.  The API is protected using access tokens. By default remote access is disabled. You can enable it in settings but do so carefully.

    The version of the OpenAPI document: 1.0.0
    Contact: info@shaggai.email
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest

from mymusik_client.api.image_file_api import ImageFileApi


class TestImageFileApi(unittest.TestCase):
    """ImageFileApi unit test stubs"""

    def setUp(self) -> None:
        self.api = ImageFileApi()

    def tearDown(self) -> None:
        pass

    def test_service_image_file_content(self) -> None:
        """Test case for service_image_file_content

        Returns the content of a file
        """
        pass

    def test_service_image_file_does_exist(self) -> None:
        """Test case for service_image_file_does_exist

        Checks if a image File exists locally.
        """
        pass

    def test_service_image_file_download_file(self) -> None:
        """Test case for service_image_file_download_file

        Downloads a image file from the cloud asynchronously, allowing other operations to continue in the background.
        """
        pass

    def test_service_image_file_erase(self) -> None:
        """Test case for service_image_file_erase

        Deletes an ImageFile using an id
        """
        pass

    def test_service_image_file_get(self) -> None:
        """Test case for service_image_file_get

        Returns an ImageFile using an id
        """
        pass

    def test_service_image_file_get_page(self) -> None:
        """Test case for service_image_file_get_page

        Returns ImageFile(s) using an filter.       Add an filter by using the '/filter' and '/condition' paths.      You can sort them by an property
        """
        pass

    def test_service_image_file_insert(self) -> None:
        """Test case for service_image_file_insert

        Creates an ImageFile. You can pass an empty id, it will then create one.
        """
        pass

    def test_service_image_file_pick_and_insert_from_device(self) -> None:
        """Test case for service_image_file_pick_and_insert_from_device

        Opens the native image picker and inserts the selected image into the image file store.
        """
        pass

    def test_service_image_file_update(self) -> None:
        """Test case for service_image_file_update

        Updates an ImageFile using an id
        """
        pass


if __name__ == '__main__':
    unittest.main()
