# coding: utf-8

"""
    MyMusik API

    MyMusik is an music player platform for offline music.  The API is object based. Each object has base methods: Insert, Update, Get, Get-Page, Erase.  Insert and Update always require a complete object. Every property must be present. Empty values are allowed.  For Insert the id is empty. The generated id is returned in the Location header.  Get requires only the object id. Get-Page uses a separate Filter object with Condition objects.  There are predefined filters available for example <ObjectName>By<PropertyName> lets you filter pages by any property. Additional actions are defined per path and may vary. Some enum values are placeholders for future features.  The API is protected using access tokens. By default remote access is disabled. You can enable it in settings but do so carefully.

    The version of the OpenAPI document: 1.0.0
    Contact: info@shaggai.email
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest

from mymusik_client.models.date_time_condition import DateTimeCondition

class TestDateTimeCondition(unittest.TestCase):
    """DateTimeCondition unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def make_instance(self, include_optional) -> DateTimeCondition:
        """Test DateTimeCondition
            include_optional is a boolean, when False only required
            params are included, when True both required and
            optional params are included """
        # uncomment below to create an instance of `DateTimeCondition`
        """
        model = DateTimeCondition()
        if include_optional:
            return DateTimeCondition(
                class_type = 'NumberCondition',
                close_parentheses_count = 56,
                has_static_value = True,
                id = '',
                is_and_connected = True,
                open_parentheses_count = 56,
                var_property = '',
                compare_operator = 'AFTER_OR_ON_DATE',
                date_time = datetime.datetime.strptime('2013-10-20 19:20:30.00', '%Y-%m-%d %H:%M:%S.%f')
            )
        else:
            return DateTimeCondition(
                class_type = 'NumberCondition',
                has_static_value = True,
                id = '',
                is_and_connected = True,
                var_property = '',
        )
        """

    def testDateTimeCondition(self):
        """Test DateTimeCondition"""
        # inst_req_only = self.make_instance(include_optional=False)
        # inst_req_and_optional = self.make_instance(include_optional=True)

if __name__ == '__main__':
    unittest.main()
