import { Identifier } from "./Identifier";
/* eslint-disable */
/* Code generated by ng-openapi-gen DO NOT EDIT. */

import { Artist } from '../models/artist';
import { MusicElement } from '../models/music-element';
export type Album = MusicElement & {
'artists'?: Array<Artist>;
'year'?: number;
};

