import { Identifier } from "./Identifier";
/* eslint-disable */
/* Code generated by ng-openapi-gen DO NOT EDIT. */

import { Album } from '../models/album';
export interface AlbumMetrics {
  album?: Album;
  completed?: number;
  firstPlayed?: string;
  id: Identifier;
  lastPlayed?: string;
  month?: string;
  playDuration?: number;
  skipCount?: number;
  skipRate?: number;
  totalPlays?: number;
  totalSongPlays?: number;
}
