import { Identifier } from "./Identifier";
/* eslint-disable */
/* Code generated by ng-openapi-gen DO NOT EDIT. */

export interface AppEvent {
  id: Identifier;
  subType?: string;
  type?: 'FIRST_LOGIN' | 'LOGIN' | 'LOGOUT' | 'RESTART' | 'DEVICE_INITALIZED' | 'ERROR' | 'WARNING' | 'INFO' | 'MESSAGE' | 'CUSTOM' | 'UNKNOWN';
  value?: string;
}
