import { Identifier } from "./Identifier";
/* eslint-disable */
/* Code generated by ng-openapi-gen DO NOT EDIT. */

export interface AudioEdit {
  arguments?: string;
  created?: string;
  durationInSeconds?: number;
  finished?: string;
  id: Identifier;
  inputFormat?: 'M4A' | 'MP3' | 'OGG' | 'WAV' | 'FLAC' | 'WMA' | 'UNKNOWN';
  inputId?: string;
  lastUpdate?: string;
  outputId?: string;
  progress?: number;
  shouldNormalize?: boolean;
  started?: string;
  status?: 'NOT_STARTED' | 'PENDING' | 'IN_PROGRESS' | 'FAILED' | 'SUCCESS';
  type?: 'CONVERT_TO_MP3' | 'CONVERT_TO_FLAC' | 'CONVERT_TO_OGG' | 'CUT' | 'EXTRACT' | 'REMOVE_SILENCE' | 'MERGE_FILES' | 'DETECT_CLIPPING' | 'CHANGE_PITCH' | 'CHANGE_SPEED' | 'APPLY_LOWPASS_FILTER' | 'APPLY_HIGHPASS_FILTER' | 'CUSTOM_FFMPEG_ARGS';
}
