import { Identifier } from "./Identifier";
/* eslint-disable */
/* Code generated by ng-openapi-gen DO NOT EDIT. */

export interface BanNotification {
  actionWasImmediate?: boolean;
  appealAt?: string;
  appealComment?: string;
  appealModeratorComment?: string;
  appealReason?: 'NoPolicyViolation' | 'MissingContextOrQuotation' | 'FairUseOrLicensed' | 'EducationalScientificOrNewsContext' | 'SatireOrParody' | 'AgeRestrictedButCompliant' | 'SupportResourcesOrHarmReduction' | 'NotSpam' | 'NotAdvertisement' | 'AccountCompromised' | 'OtherAppeal';
  appealSolved?: boolean;
  assetId?: string;
  assetParentId?: string;
  banEndsAt?: string;
  banStartsAt?: string;
  created?: string;
  dsaAffectedEntityId?: string;
  dsaAffectedEntityType?: 'DsaComment' | 'DsaSharedAsset' | 'DsaAccount' | 'DsaOther';
  dsaAutomatedProcessing?: boolean;
  dsaAutomationExplanation?: string;
  dsaDecisionAt?: string;
  dsaDecisionType?: 'Removal' | 'DisableAccess' | 'Deprioritization' | 'MonetizationRestriction' | 'AccountSuspension' | 'AccountTermination' | 'Ban';
  dsaHumanReviewAvailable?: boolean;
  dsaInternalComplaintDeadlineDays?: number;
  dsaNoticeId?: string;
  dsaSorId?: string;
  dsaTerritorialScope?: string;
  dsaTrustedFlaggerCase?: boolean;
  evidence?: string;
  explanation?: string;
  id: Identifier;
  isAdminInitiated?: boolean;
  isAppealDeclined?: boolean;
  isAppealed?: boolean;
  issuer?: string;
  issuerType?: 'User' | 'Moderator' | 'Admin' | 'Monitoring' | 'UserReports' | 'AssetOwner';
  justFYI?: boolean;
  modified?: string;
  owner?: string;
  protectedAsset?: boolean;
  reason?: 'InappropriateContent' | 'CopyrightViolation' | 'Spam' | 'Fraud' | 'PrivacyViolation' | 'SexualContent' | 'ViolentOrRepulsiveContent' | 'HatefulOrAbusiveContent' | 'HarassmentOrBullying' | 'HarmfulOrDangerousActs' | 'SuicideSelfHarmOrEatingDisorders' | 'Misinformation' | 'ChildAbuse' | 'PromotesTerrorism' | 'SpamOrMisleading' | 'LegalIssue' | 'Advertisement' | 'Other';
  reference?: string;
  relatedReportId?: string;
  revertAction?: boolean;
  scope?: 'Global' | 'Community' | 'Comments' | 'Assets' | 'Tags' | 'Reports' | 'SpecificAsset' | 'None';
  wasShown?: boolean;
}
