import { Identifier } from "./Identifier";
/* eslint-disable */
/* Code generated by ng-openapi-gen DO NOT EDIT. */

export interface Cloud {
  cloudLinkId?: string;
  compressedSize?: number;
  created?: string;
  deletedAt?: string;
  description?: string;
  expires?: string;
  fileIdentifier?: string;
  fileSize?: number;
  fileUrl?: string;
  id: Identifier;
  isDeleted?: boolean;
  lastDownload?: string;
  lastOnlineCheck?: string;
  lastUpdate?: string;
  modus?: 'LOCAL_ONLY' | 'CLOUD_ONLY' | 'SYNC_BOTH' | 'SMART_LOCAL';
  ownerId?: string;
  revision?: number;
  shouldExpire?: boolean;
  shouldRemove?: boolean;
  sig?: string;
  status?: 'PENDING' | 'UPLOADING' | 'UPLOADED' | 'FAILED';
  type?: 'OTHER' | 'IMAGE' | 'AUDIO' | 'TEXT' | 'VIDEO' | 'SCRIPT' | 'BINARY' | 'DATABASE' | 'PDF' | 'ZIP' | 'DOCX' | 'XLSX' | 'PPTX' | 'SVG' | 'PSD' | 'OBJ' | 'STL' | 'RAR' | 'MKV' | 'DLL' | 'EXE' | 'FLAC' | 'APK' | 'JSON' | 'YAML' | 'HTML' | 'CSS' | 'JS';
}
