import { Identifier } from "./Identifier";
/* eslint-disable */
/* Code generated by ng-openapi-gen DO NOT EDIT. */

export interface DatabaseBackup {
  cloudId?: string;
  compressedSize?: number;
  created?: string;
  fileCreated?: string;
  fileHash?: string;
  fileLastModified?: string;
  fileSize?: number;
  finished?: string;
  id: Identifier;
  isLocked?: boolean;
  lastCheck?: string;
  locked?: string;
  name?: string;
  owner?: string;
  version?: number;
}
