import { Identifier } from "./Identifier";
/* eslint-disable */
/* Code generated by ng-openapi-gen DO NOT EDIT. */

import { FileIdentifier } from '../models/file-identifier';
export interface FileIdentifierList {
  fileIdentifierList?: Array<FileIdentifier>;
  id: Identifier;
}
