import { Identifier } from "./Identifier";
/* eslint-disable */
/* Code generated by ng-openapi-gen DO NOT EDIT. */

export interface FilePayload {
  autoEraseFile?: boolean;
  created?: string;
  dataBase64?: string;
  filePath?: string;
  filename?: string;
  folderName?: string;
  groupCreated?: string;
  groupId?: string;
  hasData?: boolean;
  id: Identifier;
  lastModifiedDate?: string;
  processed?: boolean;
  retry?: number;
  size?: number;
  totalFiles?: number;
}
