import { Identifier } from "./Identifier";
/* eslint-disable */
/* Code generated by ng-openapi-gen DO NOT EDIT. */

import { ClassTypeCondition } from '../models/class-type-condition';
import { DateTimeCondition } from '../models/date-time-condition';
import { NumberCondition } from '../models/number-condition';
import { StringCondition } from '../models/string-condition';
export interface Filter {
  conditions?: Array<(NumberCondition | StringCondition | ClassTypeCondition | DateTimeCondition)>;
  created?: string;
  description?: string;
  id: Identifier;
  name?: string;
}
