import { Identifier } from "./Identifier";
/* eslint-disable */
/* Code generated by ng-openapi-gen DO NOT EDIT. */

import { ImageFile } from '../models/image-file';
import { Tag } from '../models/tag';
export interface MusicElement {
  classType: 'Song' | 'Album' | 'Artist' | 'Playlist';
  couldntFindMusicId?: boolean;
  created?: string;
  id: Identifier;
  image: ImageFile;
  modified?: string;
  name: string;
  publicMusicId?: string;
  shouldFetchCover?: boolean;
  tags: Array<Tag>;
  visible: boolean;
}
