import { Identifier } from "./Identifier";
/* eslint-disable */
/* Code generated by ng-openapi-gen DO NOT EDIT. */

import { Song } from '../models/song';
export interface PlayHistory {
  created?: string;
  id: Identifier;
  position?: number;
  song?: Song;
}
