import { Identifier } from "./Identifier";
/* eslint-disable */
/* Code generated by ng-openapi-gen DO NOT EDIT. */

import { QueueItem } from '../models/queue-item';
export interface QueueItemList {
  additionalValue?: string;
  id: Identifier;
  isRandom?: boolean;
  items?: Array<QueueItem>;
}
