import { Identifier } from "./Identifier";
/* eslint-disable */
/* Code generated by ng-openapi-gen DO NOT EDIT. */

export interface Report {
  action?: 'NoAction' | 'Hide' | 'Show' | 'Erase' | 'RestrictAccess' | 'ReturnAccess' | 'BanOwner' | 'UnbanOwner' | 'DeepBanOwner' | 'DeepUnbanOwner' | 'OtherAction';
  additionalText?: string;
  assetId?: string;
  assetParentId?: string;
  blamedUser?: string;
  category?: string;
  created?: string;
  evidence?: string;
  evidenceHash?: string;
  id: Identifier;
  isAdminReport?: boolean;
  isResolved?: boolean;
  modified?: string;
  owner?: string;
  preProccessed?: boolean;
  punishment?: 'None' | 'Warning' | 'TemporaryRestriction' | 'PermanentBan' | 'Takedown' | 'OtherPunishment';
  reason?: 'InappropriateContent' | 'CopyrightViolation' | 'Spam' | 'Fraud' | 'PrivacyViolation' | 'SexualContent' | 'ViolentOrRepulsiveContent' | 'HatefulOrAbusiveContent' | 'HarassmentOrBullying' | 'HarmfulOrDangerousActs' | 'SuicideSelfHarmOrEatingDisorders' | 'Misinformation' | 'ChildAbuse' | 'PromotesTerrorism' | 'SpamOrMisleading' | 'LegalIssue' | 'Advertisement' | 'Other' | 'AiGeneratedContent' | 'AiHallucination' | 'AiPolicyEvasion' | 'AiPromptInjection' | 'AiUnsafeInstructions' | 'AiSensitiveDataExposure';
  reportFor?: 'NotDefined' | 'Comment' | 'SharedAsset' | 'Tag';
  resolvedAt?: string;
  resolvedComment?: string;
  severity?: number;
  sig?: string;
  stamp?: string;
}
