import { Identifier } from "./Identifier";
/* eslint-disable */
/* Code generated by ng-openapi-gen DO NOT EDIT. */

import { Song } from '../models/song';
export interface SongMetrics {
  averageCompletionRate?: number;
  completed?: number;
  firstPlayed?: string;
  id: Identifier;
  lastPlaybackRate?: number;
  lastPlayed?: string;
  lastSeekForwardPosition?: number;
  lastSkipPosition?: number;
  lastVolume?: number;
  month?: string;
  playDuration?: number;
  repeatOneCount?: number;
  seekForwardCount?: number;
  skipped?: number;
  song?: Song;
  totalPlays?: number;
}
