/* eslint-disable */
/* Code generated by ng-openapi-gen DO NOT EDIT. */

import { HttpClient, HttpContext, HttpResponse } from '@angular/common/http';
import { Observable } from 'rxjs';
import { filter, map } from 'rxjs/operators';
import { StrictHttpResponse } from '../../strict-http-response';
import { RequestBuilder } from '../../request-builder';

import { TemporaryMessage } from '../../models/temporary-message';
import { Identifier } from '../../models/Identifier';
export type IdentifierLike = Identifier | string;



export interface ServiceTemporaryMessageInsert$Params {
  
    /**
     * TemporaryMessage that should be updated
     */
    body?: TemporaryMessage
}

export function serviceTemporaryMessageInsert(http: HttpClient, rootUrl: string, params?: ServiceTemporaryMessageInsert$Params, context?: HttpContext): Observable<StrictHttpResponse<void>> {
  const rb = new RequestBuilder(rootUrl, serviceTemporaryMessageInsert.PATH, 'post');
  if (params) {
    rb.body(params.body, 'application/json');
  }

  return http.request(
    rb.build({ responseType: 'text', accept: '*/*', context })
  ).pipe(
    filter((r: any): r is HttpResponse<any> => r instanceof HttpResponse),
    map((r: HttpResponse<any>) => {
      return (r as HttpResponse<any>).clone({ body: undefined }) as StrictHttpResponse<void>;
    })
  );
}

serviceTemporaryMessageInsert.PATH = '/temporarymessage';

export { serviceTemporaryMessageInsert as insert };
