/* eslint-disable */
/* Code generated by ng-openapi-gen DO NOT EDIT. */

import { HttpClient, HttpContext, HttpResponse } from '@angular/common/http';
import { Observable } from 'rxjs';
import { filter, map } from 'rxjs/operators';
import { StrictHttpResponse } from '../../strict-http-response';
import { RequestBuilder } from '../../request-builder';

import { CloudStorage } from '../../models/cloud-storage';
import { Identifier } from '../../models/Identifier';
export type IdentifierLike = Identifier | string;



export interface ServiceCloudStorageGetPage$Params {

/**
 * the name of a Filter resource
 */
  filterName?: string;

/**
 * input parameter for the filter use ';' to separate values
 */
  values?: string;
  sortBy?: 'region' | 'usedStorage' | 'storedFiles' | 'erasedStorage' | 'erasedMonthlyStorage' | 'downloadLinkCount' | 'uploadedStorage' | 'downloadedStorage' | 'lastMonthlyReset' | 'created' | 'lastRegionChange' | 'lastDownloadLinkTime' | 'regionChangeCount' | 'pendingErase' | 'expiredDate' | 'storageLimit' | 'lang' | 'revisionCounter' | 'minAvailableCloudRevision';
  orderBy?: 'ASC' | 'DESC' | 'RANDOM';
  pageIndex?: number;
}

export function serviceCloudStorageGetPage(http: HttpClient, rootUrl: string, params?: ServiceCloudStorageGetPage$Params, context?: HttpContext): Observable<StrictHttpResponse<Array<CloudStorage>>> {
  const rb = new RequestBuilder(rootUrl, serviceCloudStorageGetPage.PATH, 'get');
  if (params) {
    rb.query('filterName', params.filterName, {});
    rb.query('values', params.values, {});
    rb.query('sortBy', params.sortBy, {});
    rb.query('orderBy', params.orderBy, {});
    rb.query('pageIndex', params.pageIndex, {});
  }

  return http.request(
    rb.build({ responseType: 'json', accept: 'application/json', context })
  ).pipe(
    filter((r: any): r is HttpResponse<any> => r instanceof HttpResponse),
    map((r: HttpResponse<any>) => {
      return r as StrictHttpResponse<Array<CloudStorage>>;
    })
  );
}

serviceCloudStorageGetPage.PATH = '/cloudstorage';

export { serviceCloudStorageGetPage as getPage };
