/* eslint-disable */
/* Code generated by ng-openapi-gen DO NOT EDIT. */

import { HttpClient, HttpContext, HttpResponse } from '@angular/common/http';
import { Observable } from 'rxjs';
import { filter, map } from 'rxjs/operators';
import { StrictHttpResponse } from '../../strict-http-response';
import { RequestBuilder } from '../../request-builder';

import { CloudStorage } from '../../models/cloud-storage';
import { Identifier } from '../../models/Identifier';
export type IdentifierLike = Identifier | string;



export interface ServiceCloudStorageGet$Params {

/**
 * The identifier of a resource
 */
  id: IdentifierLike;
}

export function serviceCloudStorageGet(http: HttpClient, rootUrl: string, params: ServiceCloudStorageGet$Params, context?: HttpContext): Observable<StrictHttpResponse<CloudStorage>> {
  const rb = new RequestBuilder(rootUrl, serviceCloudStorageGet.PATH, 'get');
  if (params) {
    rb.path('id', String(params.id), {});
  }

  return http.request(
    rb.build({ responseType: 'json', accept: 'application/json', context })
  ).pipe(
    filter((r: any): r is HttpResponse<any> => r instanceof HttpResponse),
    map((r: HttpResponse<any>) => {
      return r as StrictHttpResponse<CloudStorage>;
    })
  );
}

serviceCloudStorageGet.PATH = '/cloudstorage/{id}';

export { serviceCloudStorageGet as get };
