import { takeUntil } from 'rxjs/operators';
import { Identifier } from "../models/Identifier";
/* eslint-disable */
/* Code generated by ng-openapi-gen DO NOT EDIT. */

import { HttpClient, HttpContext } from '@angular/common/http';
import { Injectable } from '@angular/core';
import { Observable } from 'rxjs';
import { map } from 'rxjs/operators';

import { BaseService } from '../base-service';
import { ApiConfiguration } from '../api-configuration';
import { StrictHttpResponse } from '../strict-http-response';

import { AiUser } from '../models/ai-user';
import { serviceAiUserGet } from '../fn/ai-user/service-ai-user-get';
import { ServiceAiUserGet$Params } from '../fn/ai-user/service-ai-user-get';
import { serviceAiUserGetPage } from '../fn/ai-user/service-ai-user-get-page';
import { ServiceAiUserGetPage$Params } from '../fn/ai-user/service-ai-user-get-page';
import { serviceAiUserGetTokens } from '../fn/ai-user/service-ai-user-get-tokens';
import { ServiceAiUserGetTokens$Params } from '../fn/ai-user/service-ai-user-get-tokens';

@Injectable({ providedIn: 'root' })
export class AiUserService extends BaseService<AiUser> {
  
    constructor(config: ApiConfiguration, http: HttpClient) {
        super(config, http);  
        this.catchNullEntityIfAvailable();
    }
    

  /** Path part for operation `getPage()` */
  static readonly GetPagePath = '/aiuser';

  /**
   * Returns AiUser(s) using an filter.
   *  					Add an filter by using the '/filter' and '/condition' paths.					
   * You can sort them by an property.
   *
   *
   *
   * This method provides access to the full `HttpResponse`, allowing access to response headers.
   * To access only the response body, use `getPage()` instead.
   *
   * This method doesn't expect any request body.
   */
  getPage$Response(params?: ServiceAiUserGetPage$Params, context?: HttpContext): Observable<StrictHttpResponse<Array<AiUser>>> {
    const obs = serviceAiUserGetPage(this.http, this.rootUrl, params, context);
    return obs;
  }

  /**
   * Returns AiUser(s) using an filter.
   *  					Add an filter by using the '/filter' and '/condition' paths.					
   * You can sort them by an property.
   *
   *
   *
   * This method provides access only to the response body.
   * To access the full response (for headers, for example), `getPage$Response()` instead.
   *
   * This method doesn't expect any request body.
   */
  getPage(params?: ServiceAiUserGetPage$Params, context?: HttpContext): Observable<Array<AiUser>> {
    const resp = this.getPage$Response(params, context);
    return resp.pipe(takeUntil(this.cancelPendingRequests$), 
      map((r: StrictHttpResponse<Array<AiUser>>): Array<AiUser> => r.body)
    );
  }

  /** Path part for operation `getTokens()` */
  static readonly ServiceAiUserGetTokensPath = '/aiuser/gettokens';

  /**
   * Retrieves the current token count for the AI user.
   *
   *
   *
   * This method provides access to the full `HttpResponse`, allowing access to response headers.
   * To access only the response body, use `getTokens()` instead.
   *
   * This method doesn't expect any request body.
   */
  getTokens$Response(params?: ServiceAiUserGetTokens$Params, context?: HttpContext): Observable<StrictHttpResponse<number>> {
    const obs = serviceAiUserGetTokens(this.http, this.rootUrl, params, context);
    return obs;
  }

  /**
   * Retrieves the current token count for the AI user.
   *
   *
   *
   * This method provides access only to the response body.
   * To access the full response (for headers, for example), `getTokens$Response()` instead.
   *
   * This method doesn't expect any request body.
   */
  getTokens(params?: ServiceAiUserGetTokens$Params, context?: HttpContext): Observable<number> {
    const resp = this.getTokens$Response(params, context);
    return resp.pipe(takeUntil(this.cancelPendingRequests$), 
      map((r: StrictHttpResponse<number>): number => r.body)
    );
  }

  /** Path part for operation `get()` */
  static readonly ServiceAiUserGetPath = '/aiuser/{id}';

  /**
   * Returns an AiUser using an id.
   *
   *
   *
   * This method provides access to the full `HttpResponse`, allowing access to response headers.
   * To access only the response body, use `get()` instead.
   *
   * This method doesn't expect any request body.
   */
  get$Response(params: ServiceAiUserGet$Params, context?: HttpContext): Observable<StrictHttpResponse<AiUser>> {
    const obs = serviceAiUserGet(this.http, this.rootUrl, params, context);
    return obs;
  }

  /**
   * Returns an AiUser using an id.
   *
   *
   *
   * This method provides access only to the response body.
   * To access the full response (for headers, for example), `get$Response()` instead.
   *
   * This method doesn't expect any request body.
   */
  get(params: ServiceAiUserGet$Params, context?: HttpContext): Observable<AiUser> {
    const resp = this.get$Response(params, context);
    return resp.pipe(takeUntil(this.cancelPendingRequests$), 
      map((r: StrictHttpResponse<AiUser>): AiUser => r.body)
    );
  }



    getEntityName(): string {
        return 'AiUser';
    }
}