import { takeUntil } from 'rxjs/operators';
import { Identifier } from "../models/Identifier";
/* eslint-disable */
/* Code generated by ng-openapi-gen DO NOT EDIT. */

import { HttpClient, HttpContext } from '@angular/common/http';
import { Injectable } from '@angular/core';
import { Observable } from 'rxjs';
import { map } from 'rxjs/operators';

import { BaseService } from '../base-service';
import { ApiConfiguration } from '../api-configuration';
import { StrictHttpResponse } from '../strict-http-response';

import { CloudStorage } from '../models/cloud-storage';
import { serviceCloudStorageGet } from '../fn/cloud-storage/service-cloud-storage-get';
import { ServiceCloudStorageGet$Params } from '../fn/cloud-storage/service-cloud-storage-get';
import { serviceCloudStorageGetPage } from '../fn/cloud-storage/service-cloud-storage-get-page';
import { ServiceCloudStorageGetPage$Params } from '../fn/cloud-storage/service-cloud-storage-get-page';
import { serviceCloudStorageGetStorageLeft } from '../fn/cloud-storage/service-cloud-storage-get-storage-left';
import { ServiceCloudStorageGetStorageLeft$Params } from '../fn/cloud-storage/service-cloud-storage-get-storage-left';
import { serviceCloudStorageGetUsedStorage } from '../fn/cloud-storage/service-cloud-storage-get-used-storage';
import { ServiceCloudStorageGetUsedStorage$Params } from '../fn/cloud-storage/service-cloud-storage-get-used-storage';

@Injectable({ providedIn: 'root' })
export class CloudStorageService extends BaseService<CloudStorage> {
  
    constructor(config: ApiConfiguration, http: HttpClient) {
        super(config, http);  
        this.catchNullEntityIfAvailable();
    }
    

  /** Path part for operation `getPage()` */
  static readonly GetPagePath = '/cloudstorage';

  /**
   * Returns CloudStorage(s) using an filter.
   *  					Add an filter by using the '/filter' and '/condition' paths.					
   * You can sort them by an property.
   *
   *
   *
   * This method provides access to the full `HttpResponse`, allowing access to response headers.
   * To access only the response body, use `getPage()` instead.
   *
   * This method doesn't expect any request body.
   */
  getPage$Response(params?: ServiceCloudStorageGetPage$Params, context?: HttpContext): Observable<StrictHttpResponse<Array<CloudStorage>>> {
    const obs = serviceCloudStorageGetPage(this.http, this.rootUrl, params, context);
    return obs;
  }

  /**
   * Returns CloudStorage(s) using an filter.
   *  					Add an filter by using the '/filter' and '/condition' paths.					
   * You can sort them by an property.
   *
   *
   *
   * This method provides access only to the response body.
   * To access the full response (for headers, for example), `getPage$Response()` instead.
   *
   * This method doesn't expect any request body.
   */
  getPage(params?: ServiceCloudStorageGetPage$Params, context?: HttpContext): Observable<Array<CloudStorage>> {
    const resp = this.getPage$Response(params, context);
    return resp.pipe(takeUntil(this.cancelPendingRequests$), 
      map((r: StrictHttpResponse<Array<CloudStorage>>): Array<CloudStorage> => r.body)
    );
  }

  /** Path part for operation `getStorageLeft()` */
  static readonly ServiceCloudStorageGetStorageLeftPath = '/cloudstorage/getstorageleft';

  /**
   * Retrieves the left storage in bytes available.
   *
   *
   *
   * This method provides access to the full `HttpResponse`, allowing access to response headers.
   * To access only the response body, use `getStorageLeft()` instead.
   *
   * This method doesn't expect any request body.
   */
  getStorageLeft$Response(params?: ServiceCloudStorageGetStorageLeft$Params, context?: HttpContext): Observable<StrictHttpResponse<number>> {
    const obs = serviceCloudStorageGetStorageLeft(this.http, this.rootUrl, params, context);
    return obs;
  }

  /**
   * Retrieves the left storage in bytes available.
   *
   *
   *
   * This method provides access only to the response body.
   * To access the full response (for headers, for example), `getStorageLeft$Response()` instead.
   *
   * This method doesn't expect any request body.
   */
  getStorageLeft(params?: ServiceCloudStorageGetStorageLeft$Params, context?: HttpContext): Observable<number> {
    const resp = this.getStorageLeft$Response(params, context);
    return resp.pipe(takeUntil(this.cancelPendingRequests$), 
      map((r: StrictHttpResponse<number>): number => r.body)
    );
  }

  /** Path part for operation `getUsedStorage()` */
  static readonly ServiceCloudStorageGetUsedStoragePath = '/cloudstorage/getusedstorage';

  /**
   * Retrieves the total storage in bytes available for the year.
   *
   *
   *
   * This method provides access to the full `HttpResponse`, allowing access to response headers.
   * To access only the response body, use `getUsedStorage()` instead.
   *
   * This method doesn't expect any request body.
   */
  getUsedStorage$Response(params?: ServiceCloudStorageGetUsedStorage$Params, context?: HttpContext): Observable<StrictHttpResponse<number>> {
    const obs = serviceCloudStorageGetUsedStorage(this.http, this.rootUrl, params, context);
    return obs;
  }

  /**
   * Retrieves the total storage in bytes available for the year.
   *
   *
   *
   * This method provides access only to the response body.
   * To access the full response (for headers, for example), `getUsedStorage$Response()` instead.
   *
   * This method doesn't expect any request body.
   */
  getUsedStorage(params?: ServiceCloudStorageGetUsedStorage$Params, context?: HttpContext): Observable<number> {
    const resp = this.getUsedStorage$Response(params, context);
    return resp.pipe(takeUntil(this.cancelPendingRequests$), 
      map((r: StrictHttpResponse<number>): number => r.body)
    );
  }

  /** Path part for operation `get()` */
  static readonly ServiceCloudStorageGetPath = '/cloudstorage/{id}';

  /**
   * Returns an CloudStorage using an id.
   *
   *
   *
   * This method provides access to the full `HttpResponse`, allowing access to response headers.
   * To access only the response body, use `get()` instead.
   *
   * This method doesn't expect any request body.
   */
  get$Response(params: ServiceCloudStorageGet$Params, context?: HttpContext): Observable<StrictHttpResponse<CloudStorage>> {
    const obs = serviceCloudStorageGet(this.http, this.rootUrl, params, context);
    return obs;
  }

  /**
   * Returns an CloudStorage using an id.
   *
   *
   *
   * This method provides access only to the response body.
   * To access the full response (for headers, for example), `get$Response()` instead.
   *
   * This method doesn't expect any request body.
   */
  get(params: ServiceCloudStorageGet$Params, context?: HttpContext): Observable<CloudStorage> {
    const resp = this.get$Response(params, context);
    return resp.pipe(takeUntil(this.cancelPendingRequests$), 
      map((r: StrictHttpResponse<CloudStorage>): CloudStorage => r.body)
    );
  }



    getEntityName(): string {
        return 'CloudStorage';
    }
}