import { takeUntil } from 'rxjs/operators';
import { Identifier } from "../models/Identifier";
/* eslint-disable */
/* Code generated by ng-openapi-gen DO NOT EDIT. */

import { HttpClient, HttpContext } from '@angular/common/http';
import { Injectable } from '@angular/core';
import { Observable } from 'rxjs';
import { map } from 'rxjs/operators';

import { BaseService } from '../base-service';
import { ApiConfiguration } from '../api-configuration';
import { StrictHttpResponse } from '../strict-http-response';

import { CloudUpload } from '../models/cloud-upload';
import { serviceCloudUploadGet } from '../fn/cloud-upload/service-cloud-upload-get';
import { ServiceCloudUploadGet$Params } from '../fn/cloud-upload/service-cloud-upload-get';
import { serviceCloudUploadGetPage } from '../fn/cloud-upload/service-cloud-upload-get-page';
import { ServiceCloudUploadGetPage$Params } from '../fn/cloud-upload/service-cloud-upload-get-page';

@Injectable({ providedIn: 'root' })
export class CloudUploadService extends BaseService<CloudUpload> {
  
    constructor(config: ApiConfiguration, http: HttpClient) {
        super(config, http);  
        this.catchNullEntityIfAvailable();
    }
    

  /** Path part for operation `getPage()` */
  static readonly GetPagePath = '/cloudupload';

  /**
   * Returns CloudUpload(s) using an filter.
   *  					Add an filter by using the '/filter' and '/condition' paths.					
   * You can sort them by an property.
   *
   *
   *
   * This method provides access to the full `HttpResponse`, allowing access to response headers.
   * To access only the response body, use `getPage()` instead.
   *
   * This method doesn't expect any request body.
   */
  getPage$Response(params?: ServiceCloudUploadGetPage$Params, context?: HttpContext): Observable<StrictHttpResponse<Array<CloudUpload>>> {
    const obs = serviceCloudUploadGetPage(this.http, this.rootUrl, params, context);
    return obs;
  }

  /**
   * Returns CloudUpload(s) using an filter.
   *  					Add an filter by using the '/filter' and '/condition' paths.					
   * You can sort them by an property.
   *
   *
   *
   * This method provides access only to the response body.
   * To access the full response (for headers, for example), `getPage$Response()` instead.
   *
   * This method doesn't expect any request body.
   */
  getPage(params?: ServiceCloudUploadGetPage$Params, context?: HttpContext): Observable<Array<CloudUpload>> {
    const resp = this.getPage$Response(params, context);
    return resp.pipe(takeUntil(this.cancelPendingRequests$), 
      map((r: StrictHttpResponse<Array<CloudUpload>>): Array<CloudUpload> => r.body)
    );
  }

  /** Path part for operation `get()` */
  static readonly ServiceCloudUploadGetPath = '/cloudupload/{id}';

  /**
   * Returns an CloudUpload using an id.
   *
   *
   *
   * This method provides access to the full `HttpResponse`, allowing access to response headers.
   * To access only the response body, use `get()` instead.
   *
   * This method doesn't expect any request body.
   */
  get$Response(params: ServiceCloudUploadGet$Params, context?: HttpContext): Observable<StrictHttpResponse<CloudUpload>> {
    const obs = serviceCloudUploadGet(this.http, this.rootUrl, params, context);
    return obs;
  }

  /**
   * Returns an CloudUpload using an id.
   *
   *
   *
   * This method provides access only to the response body.
   * To access the full response (for headers, for example), `get$Response()` instead.
   *
   * This method doesn't expect any request body.
   */
  get(params: ServiceCloudUploadGet$Params, context?: HttpContext): Observable<CloudUpload> {
    const resp = this.get$Response(params, context);
    return resp.pipe(takeUntil(this.cancelPendingRequests$), 
      map((r: StrictHttpResponse<CloudUpload>): CloudUpload => r.body)
    );
  }



    getEntityName(): string {
        return 'CloudUpload';
    }
}