import { takeUntil } from 'rxjs/operators';
import { Condition } from "../models";
import { Identifier } from "../models/Identifier";
/* eslint-disable */
/* Code generated by ng-openapi-gen DO NOT EDIT. */

import { HttpClient, HttpContext } from '@angular/common/http';
import { Injectable } from '@angular/core';
import { Observable } from 'rxjs';
import { map } from 'rxjs/operators';

import { BaseService } from '../base-service';
import { ApiConfiguration } from '../api-configuration';
import { StrictHttpResponse } from '../strict-http-response';

import { ClassTypeCondition } from '../models/class-type-condition';
import { DateTimeCondition } from '../models/date-time-condition';
import { NumberCondition } from '../models/number-condition';
import { serviceConditionErase } from '../fn/condition/service-condition-erase';
import { ServiceConditionErase$Params } from '../fn/condition/service-condition-erase';
import { serviceConditionGet } from '../fn/condition/service-condition-get';
import { ServiceConditionGet$Params } from '../fn/condition/service-condition-get';
import { serviceConditionGetPage } from '../fn/condition/service-condition-get-page';
import { ServiceConditionGetPage$Params } from '../fn/condition/service-condition-get-page';
import { serviceConditionInsert } from '../fn/condition/service-condition-insert';
import { ServiceConditionInsert$Params } from '../fn/condition/service-condition-insert';
import { serviceConditionUpdate } from '../fn/condition/service-condition-update';
import { ServiceConditionUpdate$Params } from '../fn/condition/service-condition-update';
import { StringCondition } from '../models/string-condition';

@Injectable({ providedIn: 'root' })
export class ConditionService extends BaseService<Condition> {
  
    constructor(config: ApiConfiguration, http: HttpClient) {
        super(config, http);  
        this.catchNullEntityIfAvailable();
    }
    

  /** Path part for operation `getPage()` */
  static readonly GetPagePath = '/condition';

  /**
   * Returns Condition(s) using an filter.
   *  					Add an filter by using the '/filter' and '/condition' paths.					
   * You can sort them by an property.
   *
   *
   *
   * This method provides access to the full `HttpResponse`, allowing access to response headers.
   * To access only the response body, use `getPage()` instead.
   *
   * This method doesn't expect any request body.
   */
  getPage$Response(params?: ServiceConditionGetPage$Params, context?: HttpContext): Observable<StrictHttpResponse<Array<(NumberCondition | StringCondition | ClassTypeCondition | DateTimeCondition)>>> {
    const obs = serviceConditionGetPage(this.http, this.rootUrl, params, context);
    return obs;
  }

  /**
   * Returns Condition(s) using an filter.
   *  					Add an filter by using the '/filter' and '/condition' paths.					
   * You can sort them by an property.
   *
   *
   *
   * This method provides access only to the response body.
   * To access the full response (for headers, for example), `getPage$Response()` instead.
   *
   * This method doesn't expect any request body.
   */
  getPage(params?: ServiceConditionGetPage$Params, context?: HttpContext): Observable<Array<(NumberCondition | StringCondition | ClassTypeCondition | DateTimeCondition)>> {
    const resp = this.getPage$Response(params, context);
    return resp.pipe(takeUntil(this.cancelPendingRequests$), 
      map((r: StrictHttpResponse<Array<(NumberCondition | StringCondition | ClassTypeCondition | DateTimeCondition)>>): Array<(NumberCondition | StringCondition | ClassTypeCondition | DateTimeCondition)> => r.body)
    );
  }

  /** Path part for operation `insert()` */
  static readonly ServiceConditionInsertPath = '/condition';

  /**
   * Creates an Condition. You can pass an empty id, it will then create one.
   *
   *
   *
   * This method provides access to the full `HttpResponse`, allowing access to response headers.
   * To access only the response body, use `insert()` instead.
   *
   * This method sends `application/json` and handles request body of type `application/json`.
   */
  insert$Response(params?: ServiceConditionInsert$Params, context?: HttpContext): Observable<StrictHttpResponse<void>> {
    const obs = serviceConditionInsert(this.http, this.rootUrl, params, context);
    return obs;
  }

  /**
   * Creates an Condition. You can pass an empty id, it will then create one.
   *
   *
   *
   * This method provides access only to the response body.
   * To access the full response (for headers, for example), `insert$Response()` instead.
   *
   * This method sends `application/json` and handles request body of type `application/json`.
   */
  insert(params?: ServiceConditionInsert$Params, context?: HttpContext): Observable<void> {
    const resp = this.insert$Response(params, context);
    return resp.pipe(takeUntil(this.cancelPendingRequests$), 
      map((r: StrictHttpResponse<void>): void => r.body)
    );
  }

  /** Path part for operation `get()` */
  static readonly ServiceConditionGetPath = '/condition/{id}';

  /**
   * Returns an Condition using an id.
   *
   *
   *
   * This method provides access to the full `HttpResponse`, allowing access to response headers.
   * To access only the response body, use `get()` instead.
   *
   * This method doesn't expect any request body.
   */
  get$Response(params: ServiceConditionGet$Params, context?: HttpContext): Observable<StrictHttpResponse<(NumberCondition | StringCondition | ClassTypeCondition | DateTimeCondition)>> {
    const obs = serviceConditionGet(this.http, this.rootUrl, params, context);
    return obs;
  }

  /**
   * Returns an Condition using an id.
   *
   *
   *
   * This method provides access only to the response body.
   * To access the full response (for headers, for example), `get$Response()` instead.
   *
   * This method doesn't expect any request body.
   */
  get(params: ServiceConditionGet$Params, context?: HttpContext): Observable<(NumberCondition | StringCondition | ClassTypeCondition | DateTimeCondition)> {
    const resp = this.get$Response(params, context);
    return resp.pipe(takeUntil(this.cancelPendingRequests$), 
      map((r: StrictHttpResponse<(NumberCondition | StringCondition | ClassTypeCondition | DateTimeCondition)>): (NumberCondition | StringCondition | ClassTypeCondition | DateTimeCondition) => r.body)
    );
  }

  /** Path part for operation `update()` */
  static readonly ServiceConditionUpdatePath = '/condition/{id}';

  /**
   * Updates an Condition using an id.
   *
   *
   *
   * This method provides access to the full `HttpResponse`, allowing access to response headers.
   * To access only the response body, use `update()` instead.
   *
   * This method sends `application/json` and handles request body of type `application/json`.
   */
  update$Response(params: ServiceConditionUpdate$Params, context?: HttpContext): Observable<StrictHttpResponse<void>> {
    const obs = serviceConditionUpdate(this.http, this.rootUrl, params, context);
    return obs;
  }

  /**
   * Updates an Condition using an id.
   *
   *
   *
   * This method provides access only to the response body.
   * To access the full response (for headers, for example), `update$Response()` instead.
   *
   * This method sends `application/json` and handles request body of type `application/json`.
   */
  update(params: ServiceConditionUpdate$Params, context?: HttpContext): Observable<void> {
    const resp = this.update$Response(params, context);
    return resp.pipe(takeUntil(this.cancelPendingRequests$), 
      map((r: StrictHttpResponse<void>): void => r.body)
    );
  }

  /** Path part for operation `erase()` */
  static readonly ServiceConditionErasePath = '/condition/{id}';

  /**
   * Deletes an Condition using an id.
   *
   *
   *
   * This method provides access to the full `HttpResponse`, allowing access to response headers.
   * To access only the response body, use `erase()` instead.
   *
   * This method doesn't expect any request body.
   */
  erase$Response(params: ServiceConditionErase$Params, context?: HttpContext): Observable<StrictHttpResponse<void>> {
    const obs = serviceConditionErase(this.http, this.rootUrl, params, context);
    return obs;
  }

  /**
   * Deletes an Condition using an id.
   *
   *
   *
   * This method provides access only to the response body.
   * To access the full response (for headers, for example), `erase$Response()` instead.
   *
   * This method doesn't expect any request body.
   */
  erase(params: ServiceConditionErase$Params, context?: HttpContext): Observable<void> {
    const resp = this.erase$Response(params, context);
    return resp.pipe(takeUntil(this.cancelPendingRequests$), 
      map((r: StrictHttpResponse<void>): void => r.body)
    );
  }



    getEntityName(): string {
        return 'Condition';
    }
}