import { takeUntil } from 'rxjs/operators';
import { Identifier } from "../models/Identifier";
/* eslint-disable */
/* Code generated by ng-openapi-gen DO NOT EDIT. */

import { HttpClient, HttpContext } from '@angular/common/http';
import { Injectable } from '@angular/core';
import { Observable } from 'rxjs';
import { map } from 'rxjs/operators';

import { BaseService } from '../base-service';
import { ApiConfiguration } from '../api-configuration';
import { StrictHttpResponse } from '../strict-http-response';

import { ConfigSection } from '../models/config-section';
import { serviceConfigSectionErase } from '../fn/config-section/service-config-section-erase';
import { ServiceConfigSectionErase$Params } from '../fn/config-section/service-config-section-erase';
import { serviceConfigSectionGet } from '../fn/config-section/service-config-section-get';
import { ServiceConfigSectionGet$Params } from '../fn/config-section/service-config-section-get';
import { serviceConfigSectionGetPage } from '../fn/config-section/service-config-section-get-page';
import { ServiceConfigSectionGetPage$Params } from '../fn/config-section/service-config-section-get-page';
import { serviceConfigSectionInsert } from '../fn/config-section/service-config-section-insert';
import { ServiceConfigSectionInsert$Params } from '../fn/config-section/service-config-section-insert';
import { serviceConfigSectionUpdate } from '../fn/config-section/service-config-section-update';
import { ServiceConfigSectionUpdate$Params } from '../fn/config-section/service-config-section-update';

@Injectable({ providedIn: 'root' })
export class ConfigSectionService extends BaseService<ConfigSection> {
  
    constructor(config: ApiConfiguration, http: HttpClient) {
        super(config, http);  
        this.catchNullEntityIfAvailable();
    }
    

  /** Path part for operation `getPage()` */
  static readonly GetPagePath = '/configsection';

  /**
   * Returns ConfigSection(s) using an filter.
   *  					Add an filter by using the '/filter' and '/condition' paths.					
   * You can sort them by an property.
   *
   *
   *
   * This method provides access to the full `HttpResponse`, allowing access to response headers.
   * To access only the response body, use `getPage()` instead.
   *
   * This method doesn't expect any request body.
   */
  getPage$Response(params?: ServiceConfigSectionGetPage$Params, context?: HttpContext): Observable<StrictHttpResponse<Array<ConfigSection>>> {
    const obs = serviceConfigSectionGetPage(this.http, this.rootUrl, params, context);
    return obs;
  }

  /**
   * Returns ConfigSection(s) using an filter.
   *  					Add an filter by using the '/filter' and '/condition' paths.					
   * You can sort them by an property.
   *
   *
   *
   * This method provides access only to the response body.
   * To access the full response (for headers, for example), `getPage$Response()` instead.
   *
   * This method doesn't expect any request body.
   */
  getPage(params?: ServiceConfigSectionGetPage$Params, context?: HttpContext): Observable<Array<ConfigSection>> {
    const resp = this.getPage$Response(params, context);
    return resp.pipe(takeUntil(this.cancelPendingRequests$), 
      map((r: StrictHttpResponse<Array<ConfigSection>>): Array<ConfigSection> => r.body)
    );
  }

  /** Path part for operation `insert()` */
  static readonly ServiceConfigSectionInsertPath = '/configsection';

  /**
   * Creates an ConfigSection. You can pass an empty id, it will then create one.
   *
   *
   *
   * This method provides access to the full `HttpResponse`, allowing access to response headers.
   * To access only the response body, use `insert()` instead.
   *
   * This method sends `application/json` and handles request body of type `application/json`.
   */
  insert$Response(params?: ServiceConfigSectionInsert$Params, context?: HttpContext): Observable<StrictHttpResponse<void>> {
    const obs = serviceConfigSectionInsert(this.http, this.rootUrl, params, context);
    return obs;
  }

  /**
   * Creates an ConfigSection. You can pass an empty id, it will then create one.
   *
   *
   *
   * This method provides access only to the response body.
   * To access the full response (for headers, for example), `insert$Response()` instead.
   *
   * This method sends `application/json` and handles request body of type `application/json`.
   */
  insert(params?: ServiceConfigSectionInsert$Params, context?: HttpContext): Observable<void> {
    const resp = this.insert$Response(params, context);
    return resp.pipe(takeUntil(this.cancelPendingRequests$), 
      map((r: StrictHttpResponse<void>): void => r.body)
    );
  }

  /** Path part for operation `get()` */
  static readonly ServiceConfigSectionGetPath = '/configsection/{id}';

  /**
   * Returns an ConfigSection using an id.
   *
   *
   *
   * This method provides access to the full `HttpResponse`, allowing access to response headers.
   * To access only the response body, use `get()` instead.
   *
   * This method doesn't expect any request body.
   */
  get$Response(params: ServiceConfigSectionGet$Params, context?: HttpContext): Observable<StrictHttpResponse<ConfigSection>> {
    const obs = serviceConfigSectionGet(this.http, this.rootUrl, params, context);
    return obs;
  }

  /**
   * Returns an ConfigSection using an id.
   *
   *
   *
   * This method provides access only to the response body.
   * To access the full response (for headers, for example), `get$Response()` instead.
   *
   * This method doesn't expect any request body.
   */
  get(params: ServiceConfigSectionGet$Params, context?: HttpContext): Observable<ConfigSection> {
    const resp = this.get$Response(params, context);
    return resp.pipe(takeUntil(this.cancelPendingRequests$), 
      map((r: StrictHttpResponse<ConfigSection>): ConfigSection => r.body)
    );
  }

  /** Path part for operation `update()` */
  static readonly ServiceConfigSectionUpdatePath = '/configsection/{id}';

  /**
   * Updates an ConfigSection using an id.
   *
   *
   *
   * This method provides access to the full `HttpResponse`, allowing access to response headers.
   * To access only the response body, use `update()` instead.
   *
   * This method sends `application/json` and handles request body of type `application/json`.
   */
  update$Response(params: ServiceConfigSectionUpdate$Params, context?: HttpContext): Observable<StrictHttpResponse<void>> {
    const obs = serviceConfigSectionUpdate(this.http, this.rootUrl, params, context);
    return obs;
  }

  /**
   * Updates an ConfigSection using an id.
   *
   *
   *
   * This method provides access only to the response body.
   * To access the full response (for headers, for example), `update$Response()` instead.
   *
   * This method sends `application/json` and handles request body of type `application/json`.
   */
  update(params: ServiceConfigSectionUpdate$Params, context?: HttpContext): Observable<void> {
    const resp = this.update$Response(params, context);
    return resp.pipe(takeUntil(this.cancelPendingRequests$), 
      map((r: StrictHttpResponse<void>): void => r.body)
    );
  }

  /** Path part for operation `erase()` */
  static readonly ServiceConfigSectionErasePath = '/configsection/{id}';

  /**
   * Deletes an ConfigSection using an id.
   *
   *
   *
   * This method provides access to the full `HttpResponse`, allowing access to response headers.
   * To access only the response body, use `erase()` instead.
   *
   * This method doesn't expect any request body.
   */
  erase$Response(params: ServiceConfigSectionErase$Params, context?: HttpContext): Observable<StrictHttpResponse<void>> {
    const obs = serviceConfigSectionErase(this.http, this.rootUrl, params, context);
    return obs;
  }

  /**
   * Deletes an ConfigSection using an id.
   *
   *
   *
   * This method provides access only to the response body.
   * To access the full response (for headers, for example), `erase$Response()` instead.
   *
   * This method doesn't expect any request body.
   */
  erase(params: ServiceConfigSectionErase$Params, context?: HttpContext): Observable<void> {
    const resp = this.erase$Response(params, context);
    return resp.pipe(takeUntil(this.cancelPendingRequests$), 
      map((r: StrictHttpResponse<void>): void => r.body)
    );
  }



    getEntityName(): string {
        return 'ConfigSection';
    }
}