import { takeUntil } from 'rxjs/operators';
import { Identifier } from "../models/Identifier";
/* eslint-disable */
/* Code generated by ng-openapi-gen DO NOT EDIT. */

import { HttpClient, HttpContext } from '@angular/common/http';
import { Injectable } from '@angular/core';
import { Observable } from 'rxjs';
import { map } from 'rxjs/operators';

import { BaseService } from '../base-service';
import { ApiConfiguration } from '../api-configuration';
import { StrictHttpResponse } from '../strict-http-response';

import { Filter } from '../models/filter';
import { serviceFilterErase } from '../fn/filter/service-filter-erase';
import { ServiceFilterErase$Params } from '../fn/filter/service-filter-erase';
import { serviceFilterGet } from '../fn/filter/service-filter-get';
import { ServiceFilterGet$Params } from '../fn/filter/service-filter-get';
import { serviceFilterGetPage } from '../fn/filter/service-filter-get-page';
import { ServiceFilterGetPage$Params } from '../fn/filter/service-filter-get-page';
import { serviceFilterInsert } from '../fn/filter/service-filter-insert';
import { ServiceFilterInsert$Params } from '../fn/filter/service-filter-insert';
import { serviceFilterUpdate } from '../fn/filter/service-filter-update';
import { ServiceFilterUpdate$Params } from '../fn/filter/service-filter-update';

@Injectable({ providedIn: 'root' })
export class FilterService extends BaseService<Filter> {
  
    constructor(config: ApiConfiguration, http: HttpClient) {
        super(config, http);  
        this.catchNullEntityIfAvailable();
    }
    

  /** Path part for operation `getPage()` */
  static readonly GetPagePath = '/filter';

  /**
   * Returns Filter(s) using an filter.
   *  					Add an filter by using the '/filter' and '/condition' paths.					
   * You can sort them by an property.
   *
   *
   *
   * This method provides access to the full `HttpResponse`, allowing access to response headers.
   * To access only the response body, use `getPage()` instead.
   *
   * This method doesn't expect any request body.
   */
  getPage$Response(params?: ServiceFilterGetPage$Params, context?: HttpContext): Observable<StrictHttpResponse<Array<Filter>>> {
    const obs = serviceFilterGetPage(this.http, this.rootUrl, params, context);
    return obs;
  }

  /**
   * Returns Filter(s) using an filter.
   *  					Add an filter by using the '/filter' and '/condition' paths.					
   * You can sort them by an property.
   *
   *
   *
   * This method provides access only to the response body.
   * To access the full response (for headers, for example), `getPage$Response()` instead.
   *
   * This method doesn't expect any request body.
   */
  getPage(params?: ServiceFilterGetPage$Params, context?: HttpContext): Observable<Array<Filter>> {
    const resp = this.getPage$Response(params, context);
    return resp.pipe(takeUntil(this.cancelPendingRequests$), 
      map((r: StrictHttpResponse<Array<Filter>>): Array<Filter> => r.body)
    );
  }

  /** Path part for operation `insert()` */
  static readonly ServiceFilterInsertPath = '/filter';

  /**
   * Creates an Filter. You can pass an empty id, it will then create one.
   *
   *
   *
   * This method provides access to the full `HttpResponse`, allowing access to response headers.
   * To access only the response body, use `insert()` instead.
   *
   * This method sends `application/json` and handles request body of type `application/json`.
   */
  insert$Response(params?: ServiceFilterInsert$Params, context?: HttpContext): Observable<StrictHttpResponse<void>> {
    const obs = serviceFilterInsert(this.http, this.rootUrl, params, context);
    return obs;
  }

  /**
   * Creates an Filter. You can pass an empty id, it will then create one.
   *
   *
   *
   * This method provides access only to the response body.
   * To access the full response (for headers, for example), `insert$Response()` instead.
   *
   * This method sends `application/json` and handles request body of type `application/json`.
   */
  insert(params?: ServiceFilterInsert$Params, context?: HttpContext): Observable<void> {
    const resp = this.insert$Response(params, context);
    return resp.pipe(takeUntil(this.cancelPendingRequests$), 
      map((r: StrictHttpResponse<void>): void => r.body)
    );
  }

  /** Path part for operation `get()` */
  static readonly ServiceFilterGetPath = '/filter/{id}';

  /**
   * Returns an Filter using an id.
   *
   *
   *
   * This method provides access to the full `HttpResponse`, allowing access to response headers.
   * To access only the response body, use `get()` instead.
   *
   * This method doesn't expect any request body.
   */
  get$Response(params: ServiceFilterGet$Params, context?: HttpContext): Observable<StrictHttpResponse<Filter>> {
    const obs = serviceFilterGet(this.http, this.rootUrl, params, context);
    return obs;
  }

  /**
   * Returns an Filter using an id.
   *
   *
   *
   * This method provides access only to the response body.
   * To access the full response (for headers, for example), `get$Response()` instead.
   *
   * This method doesn't expect any request body.
   */
  get(params: ServiceFilterGet$Params, context?: HttpContext): Observable<Filter> {
    const resp = this.get$Response(params, context);
    return resp.pipe(takeUntil(this.cancelPendingRequests$), 
      map((r: StrictHttpResponse<Filter>): Filter => r.body)
    );
  }

  /** Path part for operation `update()` */
  static readonly ServiceFilterUpdatePath = '/filter/{id}';

  /**
   * Updates an Filter using an id.
   *
   *
   *
   * This method provides access to the full `HttpResponse`, allowing access to response headers.
   * To access only the response body, use `update()` instead.
   *
   * This method sends `application/json` and handles request body of type `application/json`.
   */
  update$Response(params: ServiceFilterUpdate$Params, context?: HttpContext): Observable<StrictHttpResponse<void>> {
    const obs = serviceFilterUpdate(this.http, this.rootUrl, params, context);
    return obs;
  }

  /**
   * Updates an Filter using an id.
   *
   *
   *
   * This method provides access only to the response body.
   * To access the full response (for headers, for example), `update$Response()` instead.
   *
   * This method sends `application/json` and handles request body of type `application/json`.
   */
  update(params: ServiceFilterUpdate$Params, context?: HttpContext): Observable<void> {
    const resp = this.update$Response(params, context);
    return resp.pipe(takeUntil(this.cancelPendingRequests$), 
      map((r: StrictHttpResponse<void>): void => r.body)
    );
  }

  /** Path part for operation `erase()` */
  static readonly ServiceFilterErasePath = '/filter/{id}';

  /**
   * Deletes an Filter using an id.
   *
   *
   *
   * This method provides access to the full `HttpResponse`, allowing access to response headers.
   * To access only the response body, use `erase()` instead.
   *
   * This method doesn't expect any request body.
   */
  erase$Response(params: ServiceFilterErase$Params, context?: HttpContext): Observable<StrictHttpResponse<void>> {
    const obs = serviceFilterErase(this.http, this.rootUrl, params, context);
    return obs;
  }

  /**
   * Deletes an Filter using an id.
   *
   *
   *
   * This method provides access only to the response body.
   * To access the full response (for headers, for example), `erase$Response()` instead.
   *
   * This method doesn't expect any request body.
   */
  erase(params: ServiceFilterErase$Params, context?: HttpContext): Observable<void> {
    const resp = this.erase$Response(params, context);
    return resp.pipe(takeUntil(this.cancelPendingRequests$), 
      map((r: StrictHttpResponse<void>): void => r.body)
    );
  }



    getEntityName(): string {
        return 'Filter';
    }
}