import { takeUntil } from 'rxjs/operators';
import { Identifier } from "../models/Identifier";
/* eslint-disable */
/* Code generated by ng-openapi-gen DO NOT EDIT. */

import { HttpClient, HttpContext } from '@angular/common/http';
import { Injectable } from '@angular/core';
import { Observable } from 'rxjs';
import { map } from 'rxjs/operators';

import { BaseService } from '../base-service';
import { ApiConfiguration } from '../api-configuration';
import { StrictHttpResponse } from '../strict-http-response';

import { LicenseInfo } from '../models/license-info';
import { serviceLicenseInfoGet } from '../fn/license-info/service-license-info-get';
import { ServiceLicenseInfoGet$Params } from '../fn/license-info/service-license-info-get';
import { serviceLicenseInfoGetPage } from '../fn/license-info/service-license-info-get-page';
import { ServiceLicenseInfoGetPage$Params } from '../fn/license-info/service-license-info-get-page';

@Injectable({ providedIn: 'root' })
export class LicenseInfoService extends BaseService<LicenseInfo> {
  
    constructor(config: ApiConfiguration, http: HttpClient) {
        super(config, http);  
        this.catchNullEntityIfAvailable();
    }
    

  /** Path part for operation `getPage()` */
  static readonly GetPagePath = '/licenseinfo';

  /**
   * Returns LicenseInfo(s) using an filter.
   *  					Add an filter by using the '/filter' and '/condition' paths.					
   * You can sort them by an property.
   *
   *
   *
   * This method provides access to the full `HttpResponse`, allowing access to response headers.
   * To access only the response body, use `getPage()` instead.
   *
   * This method doesn't expect any request body.
   */
  getPage$Response(params?: ServiceLicenseInfoGetPage$Params, context?: HttpContext): Observable<StrictHttpResponse<Array<LicenseInfo>>> {
    const obs = serviceLicenseInfoGetPage(this.http, this.rootUrl, params, context);
    return obs;
  }

  /**
   * Returns LicenseInfo(s) using an filter.
   *  					Add an filter by using the '/filter' and '/condition' paths.					
   * You can sort them by an property.
   *
   *
   *
   * This method provides access only to the response body.
   * To access the full response (for headers, for example), `getPage$Response()` instead.
   *
   * This method doesn't expect any request body.
   */
  getPage(params?: ServiceLicenseInfoGetPage$Params, context?: HttpContext): Observable<Array<LicenseInfo>> {
    const resp = this.getPage$Response(params, context);
    return resp.pipe(takeUntil(this.cancelPendingRequests$), 
      map((r: StrictHttpResponse<Array<LicenseInfo>>): Array<LicenseInfo> => r.body)
    );
  }

  /** Path part for operation `get()` */
  static readonly ServiceLicenseInfoGetPath = '/licenseinfo/{id}';

  /**
   * Returns an LicenseInfo using an id.
   *
   *
   *
   * This method provides access to the full `HttpResponse`, allowing access to response headers.
   * To access only the response body, use `get()` instead.
   *
   * This method doesn't expect any request body.
   */
  get$Response(params: ServiceLicenseInfoGet$Params, context?: HttpContext): Observable<StrictHttpResponse<LicenseInfo>> {
    const obs = serviceLicenseInfoGet(this.http, this.rootUrl, params, context);
    return obs;
  }

  /**
   * Returns an LicenseInfo using an id.
   *
   *
   *
   * This method provides access only to the response body.
   * To access the full response (for headers, for example), `get$Response()` instead.
   *
   * This method doesn't expect any request body.
   */
  get(params: ServiceLicenseInfoGet$Params, context?: HttpContext): Observable<LicenseInfo> {
    const resp = this.get$Response(params, context);
    return resp.pipe(takeUntil(this.cancelPendingRequests$), 
      map((r: StrictHttpResponse<LicenseInfo>): LicenseInfo => r.body)
    );
  }



    getEntityName(): string {
        return 'LicenseInfo';
    }
}