import { takeUntil } from 'rxjs/operators';
import { Identifier } from "../models/Identifier";
/* eslint-disable */
/* Code generated by ng-openapi-gen DO NOT EDIT. */

import { HttpClient, HttpContext } from '@angular/common/http';
import { Injectable } from '@angular/core';
import { Observable } from 'rxjs';
import { map } from 'rxjs/operators';

import { BaseService } from '../base-service';
import { ApiConfiguration } from '../api-configuration';
import { StrictHttpResponse } from '../strict-http-response';

import { Login } from '../models/login';
import { serviceLoginErase } from '../fn/login/service-login-erase';
import { ServiceLoginErase$Params } from '../fn/login/service-login-erase';
import { serviceLoginGet } from '../fn/login/service-login-get';
import { ServiceLoginGet$Params } from '../fn/login/service-login-get';
import { serviceLoginGetPage } from '../fn/login/service-login-get-page';
import { ServiceLoginGetPage$Params } from '../fn/login/service-login-get-page';
import { serviceLoginInsert } from '../fn/login/service-login-insert';
import { ServiceLoginInsert$Params } from '../fn/login/service-login-insert';
import { serviceLoginIsLoggedIn } from '../fn/login/service-login-is-logged-in';
import { ServiceLoginIsLoggedIn$Params } from '../fn/login/service-login-is-logged-in';
import { serviceLoginIsLoggedOut } from '../fn/login/service-login-is-logged-out';
import { ServiceLoginIsLoggedOut$Params } from '../fn/login/service-login-is-logged-out';
import { serviceLoginOpenUserProfileInBrowser } from '../fn/login/service-login-open-user-profile-in-browser';
import { ServiceLoginOpenUserProfileInBrowser$Params } from '../fn/login/service-login-open-user-profile-in-browser';
import { serviceLoginTriggerLoginFlow } from '../fn/login/service-login-trigger-login-flow';
import { ServiceLoginTriggerLoginFlow$Params } from '../fn/login/service-login-trigger-login-flow';
import { serviceLoginUpdate } from '../fn/login/service-login-update';
import { ServiceLoginUpdate$Params } from '../fn/login/service-login-update';

@Injectable({ providedIn: 'root' })
export class LoginService extends BaseService<Login> {
  
    constructor(config: ApiConfiguration, http: HttpClient) {
        super(config, http);  
        this.catchNullEntityIfAvailable();
    }
    

  /** Path part for operation `getPage()` */
  static readonly GetPagePath = '/login';

  /**
   * Returns Login(s) using an filter.
   *  					Add an filter by using the '/filter' and '/condition' paths.					
   * You can sort them by an property.
   *
   *
   *
   * This method provides access to the full `HttpResponse`, allowing access to response headers.
   * To access only the response body, use `getPage()` instead.
   *
   * This method doesn't expect any request body.
   */
  getPage$Response(params?: ServiceLoginGetPage$Params, context?: HttpContext): Observable<StrictHttpResponse<Array<Login>>> {
    const obs = serviceLoginGetPage(this.http, this.rootUrl, params, context);
    return obs;
  }

  /**
   * Returns Login(s) using an filter.
   *  					Add an filter by using the '/filter' and '/condition' paths.					
   * You can sort them by an property.
   *
   *
   *
   * This method provides access only to the response body.
   * To access the full response (for headers, for example), `getPage$Response()` instead.
   *
   * This method doesn't expect any request body.
   */
  getPage(params?: ServiceLoginGetPage$Params, context?: HttpContext): Observable<Array<Login>> {
    const resp = this.getPage$Response(params, context);
    return resp.pipe(takeUntil(this.cancelPendingRequests$), 
      map((r: StrictHttpResponse<Array<Login>>): Array<Login> => r.body)
    );
  }

  /** Path part for operation `insert()` */
  static readonly ServiceLoginInsertPath = '/login';

  /**
   * Creates an Login. You can pass an empty id, it will then create one.
   *
   *
   *
   * This method provides access to the full `HttpResponse`, allowing access to response headers.
   * To access only the response body, use `insert()` instead.
   *
   * This method sends `application/json` and handles request body of type `application/json`.
   */
  insert$Response(params?: ServiceLoginInsert$Params, context?: HttpContext): Observable<StrictHttpResponse<void>> {
    const obs = serviceLoginInsert(this.http, this.rootUrl, params, context);
    return obs;
  }

  /**
   * Creates an Login. You can pass an empty id, it will then create one.
   *
   *
   *
   * This method provides access only to the response body.
   * To access the full response (for headers, for example), `insert$Response()` instead.
   *
   * This method sends `application/json` and handles request body of type `application/json`.
   */
  insert(params?: ServiceLoginInsert$Params, context?: HttpContext): Observable<void> {
    const resp = this.insert$Response(params, context);
    return resp.pipe(takeUntil(this.cancelPendingRequests$), 
      map((r: StrictHttpResponse<void>): void => r.body)
    );
  }

  /** Path part for operation `isLoggedIn()` */
  static readonly ServiceLoginIsLoggedInPath = '/login/isloggedin';

  /**
   * Check if the user is logged in.
   *
   *
   *
   * This method provides access to the full `HttpResponse`, allowing access to response headers.
   * To access only the response body, use `isLoggedIn()` instead.
   *
   * This method doesn't expect any request body.
   */
  isLoggedIn$Response(params?: ServiceLoginIsLoggedIn$Params, context?: HttpContext): Observable<StrictHttpResponse<number>> {
    const obs = serviceLoginIsLoggedIn(this.http, this.rootUrl, params, context);
    return obs;
  }

  /**
   * Check if the user is logged in.
   *
   *
   *
   * This method provides access only to the response body.
   * To access the full response (for headers, for example), `isLoggedIn$Response()` instead.
   *
   * This method doesn't expect any request body.
   */
  isLoggedIn(params?: ServiceLoginIsLoggedIn$Params, context?: HttpContext): Observable<number> {
    const resp = this.isLoggedIn$Response(params, context);
    return resp.pipe(takeUntil(this.cancelPendingRequests$), 
      map((r: StrictHttpResponse<number>): number => r.body)
    );
  }

  /** Path part for operation `isLoggedOut()` */
  static readonly ServiceLoginIsLoggedOutPath = '/login/isloggedout';

  /**
   * Check if the user is logged out.
   *
   *
   *
   * This method provides access to the full `HttpResponse`, allowing access to response headers.
   * To access only the response body, use `isLoggedOut()` instead.
   *
   * This method doesn't expect any request body.
   */
  isLoggedOut$Response(params?: ServiceLoginIsLoggedOut$Params, context?: HttpContext): Observable<StrictHttpResponse<void>> {
    const obs = serviceLoginIsLoggedOut(this.http, this.rootUrl, params, context);
    return obs;
  }

  /**
   * Check if the user is logged out.
   *
   *
   *
   * This method provides access only to the response body.
   * To access the full response (for headers, for example), `isLoggedOut$Response()` instead.
   *
   * This method doesn't expect any request body.
   */
  isLoggedOut(params?: ServiceLoginIsLoggedOut$Params, context?: HttpContext): Observable<void> {
    const resp = this.isLoggedOut$Response(params, context);
    return resp.pipe(takeUntil(this.cancelPendingRequests$), 
      map((r: StrictHttpResponse<void>): void => r.body)
    );
  }

  /** Path part for operation `openUserProfileInBrowser()` */
  static readonly ServiceLoginOpenUserProfileInBrowserPath = '/login/openuserprofileinbrowser';

  /**
   * Opens the User Profile page in Browser.
   *
   *
   *
   * This method provides access to the full `HttpResponse`, allowing access to response headers.
   * To access only the response body, use `openUserProfileInBrowser()` instead.
   *
   * This method doesn't expect any request body.
   */
  openUserProfileInBrowser$Response(params?: ServiceLoginOpenUserProfileInBrowser$Params, context?: HttpContext): Observable<StrictHttpResponse<void>> {
    const obs = serviceLoginOpenUserProfileInBrowser(this.http, this.rootUrl, params, context);
    return obs;
  }

  /**
   * Opens the User Profile page in Browser.
   *
   *
   *
   * This method provides access only to the response body.
   * To access the full response (for headers, for example), `openUserProfileInBrowser$Response()` instead.
   *
   * This method doesn't expect any request body.
   */
  openUserProfileInBrowser(params?: ServiceLoginOpenUserProfileInBrowser$Params, context?: HttpContext): Observable<void> {
    const resp = this.openUserProfileInBrowser$Response(params, context);
    return resp.pipe(takeUntil(this.cancelPendingRequests$), 
      map((r: StrictHttpResponse<void>): void => r.body)
    );
  }

  /** Path part for operation `triggerLoginFlow()` */
  static readonly ServiceLoginTriggerLoginFlowPath = '/login/triggerloginflow';

  /**
   * Starts the login flow.
   *
   *
   *
   * This method provides access to the full `HttpResponse`, allowing access to response headers.
   * To access only the response body, use `triggerLoginFlow()` instead.
   *
   * This method doesn't expect any request body.
   */
  triggerLoginFlow$Response(params?: ServiceLoginTriggerLoginFlow$Params, context?: HttpContext): Observable<StrictHttpResponse<void>> {
    const obs = serviceLoginTriggerLoginFlow(this.http, this.rootUrl, params, context);
    return obs;
  }

  /**
   * Starts the login flow.
   *
   *
   *
   * This method provides access only to the response body.
   * To access the full response (for headers, for example), `triggerLoginFlow$Response()` instead.
   *
   * This method doesn't expect any request body.
   */
  triggerLoginFlow(params?: ServiceLoginTriggerLoginFlow$Params, context?: HttpContext): Observable<void> {
    const resp = this.triggerLoginFlow$Response(params, context);
    return resp.pipe(takeUntil(this.cancelPendingRequests$), 
      map((r: StrictHttpResponse<void>): void => r.body)
    );
  }

  /** Path part for operation `get()` */
  static readonly ServiceLoginGetPath = '/login/{id}';

  /**
   * Returns an Login using an id.
   *
   *
   *
   * This method provides access to the full `HttpResponse`, allowing access to response headers.
   * To access only the response body, use `get()` instead.
   *
   * This method doesn't expect any request body.
   */
  get$Response(params: ServiceLoginGet$Params, context?: HttpContext): Observable<StrictHttpResponse<Login>> {
    const obs = serviceLoginGet(this.http, this.rootUrl, params, context);
    return obs;
  }

  /**
   * Returns an Login using an id.
   *
   *
   *
   * This method provides access only to the response body.
   * To access the full response (for headers, for example), `get$Response()` instead.
   *
   * This method doesn't expect any request body.
   */
  get(params: ServiceLoginGet$Params, context?: HttpContext): Observable<Login> {
    const resp = this.get$Response(params, context);
    return resp.pipe(takeUntil(this.cancelPendingRequests$), 
      map((r: StrictHttpResponse<Login>): Login => r.body)
    );
  }

  /** Path part for operation `update()` */
  static readonly ServiceLoginUpdatePath = '/login/{id}';

  /**
   * Updates an Login using an id.
   *
   *
   *
   * This method provides access to the full `HttpResponse`, allowing access to response headers.
   * To access only the response body, use `update()` instead.
   *
   * This method sends `application/json` and handles request body of type `application/json`.
   */
  update$Response(params: ServiceLoginUpdate$Params, context?: HttpContext): Observable<StrictHttpResponse<void>> {
    const obs = serviceLoginUpdate(this.http, this.rootUrl, params, context);
    return obs;
  }

  /**
   * Updates an Login using an id.
   *
   *
   *
   * This method provides access only to the response body.
   * To access the full response (for headers, for example), `update$Response()` instead.
   *
   * This method sends `application/json` and handles request body of type `application/json`.
   */
  update(params: ServiceLoginUpdate$Params, context?: HttpContext): Observable<void> {
    const resp = this.update$Response(params, context);
    return resp.pipe(takeUntil(this.cancelPendingRequests$), 
      map((r: StrictHttpResponse<void>): void => r.body)
    );
  }

  /** Path part for operation `erase()` */
  static readonly ServiceLoginErasePath = '/login/{id}';

  /**
   * Deletes an Login using an id.
   *
   *
   *
   * This method provides access to the full `HttpResponse`, allowing access to response headers.
   * To access only the response body, use `erase()` instead.
   *
   * This method doesn't expect any request body.
   */
  erase$Response(params: ServiceLoginErase$Params, context?: HttpContext): Observable<StrictHttpResponse<void>> {
    const obs = serviceLoginErase(this.http, this.rootUrl, params, context);
    return obs;
  }

  /**
   * Deletes an Login using an id.
   *
   *
   *
   * This method provides access only to the response body.
   * To access the full response (for headers, for example), `erase$Response()` instead.
   *
   * This method doesn't expect any request body.
   */
  erase(params: ServiceLoginErase$Params, context?: HttpContext): Observable<void> {
    const resp = this.erase$Response(params, context);
    return resp.pipe(takeUntil(this.cancelPendingRequests$), 
      map((r: StrictHttpResponse<void>): void => r.body)
    );
  }



    getEntityName(): string {
        return 'Login';
    }
}