import { takeUntil } from 'rxjs/operators';
import { MusicElement } from "../models";
import { Identifier } from "../models/Identifier";
/* eslint-disable */
/* Code generated by ng-openapi-gen DO NOT EDIT. */

import { HttpClient, HttpContext } from '@angular/common/http';
import { Injectable } from '@angular/core';
import { Observable } from 'rxjs';
import { map } from 'rxjs/operators';

import { BaseService } from '../base-service';
import { ApiConfiguration } from '../api-configuration';
import { StrictHttpResponse } from '../strict-http-response';

import { Album } from '../models/album';
import { Artist } from '../models/artist';
import { Playlist } from '../models/playlist';
import { serviceMusicElementCount } from '../fn/music-element/service-music-element-count';
import { ServiceMusicElementCount$Params } from '../fn/music-element/service-music-element-count';
import { serviceMusicElementErase } from '../fn/music-element/service-music-element-erase';
import { ServiceMusicElementErase$Params } from '../fn/music-element/service-music-element-erase';
import { serviceMusicElementGet } from '../fn/music-element/service-music-element-get';
import { ServiceMusicElementGet$Params } from '../fn/music-element/service-music-element-get';
import { serviceMusicElementGetPage } from '../fn/music-element/service-music-element-get-page';
import { ServiceMusicElementGetPage$Params } from '../fn/music-element/service-music-element-get-page';
import { serviceMusicElementInsert } from '../fn/music-element/service-music-element-insert';
import { ServiceMusicElementInsert$Params } from '../fn/music-element/service-music-element-insert';
import { serviceMusicElementUpdate } from '../fn/music-element/service-music-element-update';
import { ServiceMusicElementUpdate$Params } from '../fn/music-element/service-music-element-update';
import { serviceMusicElementUploadCoverToCloud } from '../fn/music-element/service-music-element-upload-cover-to-cloud';
import { ServiceMusicElementUploadCoverToCloud$Params } from '../fn/music-element/service-music-element-upload-cover-to-cloud';
import { Song } from '../models/song';

@Injectable({ providedIn: 'root' })
export class MusicElementService extends BaseService<MusicElement> {
  
    constructor(config: ApiConfiguration, http: HttpClient) {
        super(config, http);  
        this.catchNullEntityIfAvailable();
    }
    

  /** Path part for operation `getPage()` */
  static readonly GetPagePath = '/musicelement';

  /**
   * Returns MusicElement(s) using an filter.
   *  					Add an filter by using the '/filter' and '/condition' paths.					
   * You can sort them by an property.
   *
   *
   *
   * This method provides access to the full `HttpResponse`, allowing access to response headers.
   * To access only the response body, use `getPage()` instead.
   *
   * This method doesn't expect any request body.
   */
  getPage$Response(params?: ServiceMusicElementGetPage$Params, context?: HttpContext): Observable<StrictHttpResponse<Array<(Song | Album | Artist | Playlist)>>> {
    const obs = serviceMusicElementGetPage(this.http, this.rootUrl, params, context);
    return obs;
  }

  /**
   * Returns MusicElement(s) using an filter.
   *  					Add an filter by using the '/filter' and '/condition' paths.					
   * You can sort them by an property.
   *
   *
   *
   * This method provides access only to the response body.
   * To access the full response (for headers, for example), `getPage$Response()` instead.
   *
   * This method doesn't expect any request body.
   */
  getPage(params?: ServiceMusicElementGetPage$Params, context?: HttpContext): Observable<Array<(Song | Album | Artist | Playlist)>> {
    const resp = this.getPage$Response(params, context);
    return resp.pipe(takeUntil(this.cancelPendingRequests$), 
      map((r: StrictHttpResponse<Array<(Song | Album | Artist | Playlist)>>): Array<(Song | Album | Artist | Playlist)> => r.body)
    );
  }

  /** Path part for operation `insert()` */
  static readonly ServiceMusicElementInsertPath = '/musicelement';

  /**
   * Creates an MusicElement. You can pass an empty id, it will then create one.
   *
   *
   *
   * This method provides access to the full `HttpResponse`, allowing access to response headers.
   * To access only the response body, use `insert()` instead.
   *
   * This method sends `application/json` and handles request body of type `application/json`.
   */
  insert$Response(params?: ServiceMusicElementInsert$Params, context?: HttpContext): Observable<StrictHttpResponse<void>> {
    const obs = serviceMusicElementInsert(this.http, this.rootUrl, params, context);
    return obs;
  }

  /**
   * Creates an MusicElement. You can pass an empty id, it will then create one.
   *
   *
   *
   * This method provides access only to the response body.
   * To access the full response (for headers, for example), `insert$Response()` instead.
   *
   * This method sends `application/json` and handles request body of type `application/json`.
   */
  insert(params?: ServiceMusicElementInsert$Params, context?: HttpContext): Observable<void> {
    const resp = this.insert$Response(params, context);
    return resp.pipe(takeUntil(this.cancelPendingRequests$), 
      map((r: StrictHttpResponse<void>): void => r.body)
    );
  }

  /** Path part for operation `count()` */
  static readonly ServiceMusicElementCountPath = '/musicelement/count';

  /**
   * Returns number of filtered musicelements in library.
   *
   *
   *
   * This method provides access to the full `HttpResponse`, allowing access to response headers.
   * To access only the response body, use `count()` instead.
   *
   * This method doesn't expect any request body.
   */
  count$Response(params?: ServiceMusicElementCount$Params, context?: HttpContext): Observable<StrictHttpResponse<number>> {
    const obs = serviceMusicElementCount(this.http, this.rootUrl, params, context);
    return obs;
  }

  /**
   * Returns number of filtered musicelements in library.
   *
   *
   *
   * This method provides access only to the response body.
   * To access the full response (for headers, for example), `count$Response()` instead.
   *
   * This method doesn't expect any request body.
   */
  count(params?: ServiceMusicElementCount$Params, context?: HttpContext): Observable<number> {
    const resp = this.count$Response(params, context);
    return resp.pipe(takeUntil(this.cancelPendingRequests$), 
      map((r: StrictHttpResponse<number>): number => r.body)
    );
  }

  /** Path part for operation `get()` */
  static readonly ServiceMusicElementGetPath = '/musicelement/{id}';

  /**
   * Returns an MusicElement using an id.
   *
   *
   *
   * This method provides access to the full `HttpResponse`, allowing access to response headers.
   * To access only the response body, use `get()` instead.
   *
   * This method doesn't expect any request body.
   */
  get$Response(params: ServiceMusicElementGet$Params, context?: HttpContext): Observable<StrictHttpResponse<(Song | Album | Artist | Playlist)>> {
    const obs = serviceMusicElementGet(this.http, this.rootUrl, params, context);
    return obs;
  }

  /**
   * Returns an MusicElement using an id.
   *
   *
   *
   * This method provides access only to the response body.
   * To access the full response (for headers, for example), `get$Response()` instead.
   *
   * This method doesn't expect any request body.
   */
  get(params: ServiceMusicElementGet$Params, context?: HttpContext): Observable<(Song | Album | Artist | Playlist)> {
    const resp = this.get$Response(params, context);
    return resp.pipe(takeUntil(this.cancelPendingRequests$), 
      map((r: StrictHttpResponse<(Song | Album | Artist | Playlist)>): (Song | Album | Artist | Playlist) => r.body)
    );
  }

  /** Path part for operation `update()` */
  static readonly ServiceMusicElementUpdatePath = '/musicelement/{id}';

  /**
   * Updates an MusicElement using an id.
   *
   *
   *
   * This method provides access to the full `HttpResponse`, allowing access to response headers.
   * To access only the response body, use `update()` instead.
   *
   * This method sends `application/json` and handles request body of type `application/json`.
   */
  update$Response(params: ServiceMusicElementUpdate$Params, context?: HttpContext): Observable<StrictHttpResponse<void>> {
    const obs = serviceMusicElementUpdate(this.http, this.rootUrl, params, context);
    return obs;
  }

  /**
   * Updates an MusicElement using an id.
   *
   *
   *
   * This method provides access only to the response body.
   * To access the full response (for headers, for example), `update$Response()` instead.
   *
   * This method sends `application/json` and handles request body of type `application/json`.
   */
  update(params: ServiceMusicElementUpdate$Params, context?: HttpContext): Observable<void> {
    const resp = this.update$Response(params, context);
    return resp.pipe(takeUntil(this.cancelPendingRequests$), 
      map((r: StrictHttpResponse<void>): void => r.body)
    );
  }

  /** Path part for operation `erase()` */
  static readonly ServiceMusicElementErasePath = '/musicelement/{id}';

  /**
   * Deletes an MusicElement using an id.
   *
   *
   *
   * This method provides access to the full `HttpResponse`, allowing access to response headers.
   * To access only the response body, use `erase()` instead.
   *
   * This method doesn't expect any request body.
   */
  erase$Response(params: ServiceMusicElementErase$Params, context?: HttpContext): Observable<StrictHttpResponse<void>> {
    const obs = serviceMusicElementErase(this.http, this.rootUrl, params, context);
    return obs;
  }

  /**
   * Deletes an MusicElement using an id.
   *
   *
   *
   * This method provides access only to the response body.
   * To access the full response (for headers, for example), `erase$Response()` instead.
   *
   * This method doesn't expect any request body.
   */
  erase(params: ServiceMusicElementErase$Params, context?: HttpContext): Observable<void> {
    const resp = this.erase$Response(params, context);
    return resp.pipe(takeUntil(this.cancelPendingRequests$), 
      map((r: StrictHttpResponse<void>): void => r.body)
    );
  }

  /** Path part for operation `uploadCoverToCloud()` */
  static readonly ServiceMusicElementUploadCoverToCloudPath = '/musicelement/{id}/uploadcovertocloud';

  /**
   * Queues the current cover image of the music element for cloud upload.
   *
   *
   *
   * This method provides access to the full `HttpResponse`, allowing access to response headers.
   * To access only the response body, use `uploadCoverToCloud()` instead.
   *
   * This method doesn't expect any request body.
   */
  uploadCoverToCloud$Response(params: ServiceMusicElementUploadCoverToCloud$Params, context?: HttpContext): Observable<StrictHttpResponse<void>> {
    const obs = serviceMusicElementUploadCoverToCloud(this.http, this.rootUrl, params, context);
    return obs;
  }

  /**
   * Queues the current cover image of the music element for cloud upload.
   *
   *
   *
   * This method provides access only to the response body.
   * To access the full response (for headers, for example), `uploadCoverToCloud$Response()` instead.
   *
   * This method doesn't expect any request body.
   */
  uploadCoverToCloud(params: ServiceMusicElementUploadCoverToCloud$Params, context?: HttpContext): Observable<void> {
    const resp = this.uploadCoverToCloud$Response(params, context);
    return resp.pipe(takeUntil(this.cancelPendingRequests$), 
      map((r: StrictHttpResponse<void>): void => r.body)
    );
  }



    getEntityName(): string {
        return 'MusicElement';
    }
}