import { takeUntil } from 'rxjs/operators';
import { Identifier } from "../models/Identifier";
/* eslint-disable */
/* Code generated by ng-openapi-gen DO NOT EDIT. */

import { HttpClient, HttpContext } from '@angular/common/http';
import { Injectable } from '@angular/core';
import { Observable } from 'rxjs';
import { map } from 'rxjs/operators';

import { BaseService } from '../base-service';
import { ApiConfiguration } from '../api-configuration';
import { StrictHttpResponse } from '../strict-http-response';

import { Playlist } from '../models/playlist';
import { servicePlaylistCount } from '../fn/playlist/service-playlist-count';
import { ServicePlaylistCount$Params } from '../fn/playlist/service-playlist-count';
import { servicePlaylistCreate } from '../fn/playlist/service-playlist-create';
import { ServicePlaylistCreate$Params } from '../fn/playlist/service-playlist-create';
import { servicePlaylistCreateFromAlbums } from '../fn/playlist/service-playlist-create-from-albums';
import { ServicePlaylistCreateFromAlbums$Params } from '../fn/playlist/service-playlist-create-from-albums';
import { servicePlaylistErase } from '../fn/playlist/service-playlist-erase';
import { ServicePlaylistErase$Params } from '../fn/playlist/service-playlist-erase';
import { servicePlaylistGet } from '../fn/playlist/service-playlist-get';
import { ServicePlaylistGet$Params } from '../fn/playlist/service-playlist-get';
import { servicePlaylistGetPage } from '../fn/playlist/service-playlist-get-page';
import { ServicePlaylistGetPage$Params } from '../fn/playlist/service-playlist-get-page';
import { servicePlaylistInsert } from '../fn/playlist/service-playlist-insert';
import { ServicePlaylistInsert$Params } from '../fn/playlist/service-playlist-insert';
import { servicePlaylistUpdate } from '../fn/playlist/service-playlist-update';
import { ServicePlaylistUpdate$Params } from '../fn/playlist/service-playlist-update';

@Injectable({ providedIn: 'root' })
export class PlaylistService extends BaseService<Playlist> {
  
    constructor(config: ApiConfiguration, http: HttpClient) {
        super(config, http);  
        this.catchNullEntityIfAvailable();
    }
    

  /** Path part for operation `getPage()` */
  static readonly GetPagePath = '/playlist';

  /**
   * Returns Playlist(s) using an filter.
   *  					Add an filter by using the '/filter' and '/condition' paths.					
   * You can sort them by an property.
   *
   *
   *
   * This method provides access to the full `HttpResponse`, allowing access to response headers.
   * To access only the response body, use `getPage()` instead.
   *
   * This method doesn't expect any request body.
   */
  getPage$Response(params?: ServicePlaylistGetPage$Params, context?: HttpContext): Observable<StrictHttpResponse<Array<Playlist>>> {
    const obs = servicePlaylistGetPage(this.http, this.rootUrl, params, context);
    return obs;
  }

  /**
   * Returns Playlist(s) using an filter.
   *  					Add an filter by using the '/filter' and '/condition' paths.					
   * You can sort them by an property.
   *
   *
   *
   * This method provides access only to the response body.
   * To access the full response (for headers, for example), `getPage$Response()` instead.
   *
   * This method doesn't expect any request body.
   */
  getPage(params?: ServicePlaylistGetPage$Params, context?: HttpContext): Observable<Array<Playlist>> {
    const resp = this.getPage$Response(params, context);
    return resp.pipe(takeUntil(this.cancelPendingRequests$), 
      map((r: StrictHttpResponse<Array<Playlist>>): Array<Playlist> => r.body)
    );
  }

  /** Path part for operation `insert()` */
  static readonly ServicePlaylistInsertPath = '/playlist';

  /**
   * Creates an Playlist. You can pass an empty id, it will then create one.
   *
   *
   *
   * This method provides access to the full `HttpResponse`, allowing access to response headers.
   * To access only the response body, use `insert()` instead.
   *
   * This method sends `application/json` and handles request body of type `application/json`.
   */
  insert$Response(params?: ServicePlaylistInsert$Params, context?: HttpContext): Observable<StrictHttpResponse<void>> {
    const obs = servicePlaylistInsert(this.http, this.rootUrl, params, context);
    return obs;
  }

  /**
   * Creates an Playlist. You can pass an empty id, it will then create one.
   *
   *
   *
   * This method provides access only to the response body.
   * To access the full response (for headers, for example), `insert$Response()` instead.
   *
   * This method sends `application/json` and handles request body of type `application/json`.
   */
  insert(params?: ServicePlaylistInsert$Params, context?: HttpContext): Observable<void> {
    const resp = this.insert$Response(params, context);
    return resp.pipe(takeUntil(this.cancelPendingRequests$), 
      map((r: StrictHttpResponse<void>): void => r.body)
    );
  }

  /** Path part for operation `count()` */
  static readonly ServicePlaylistCountPath = '/playlist/count';

  /**
   * Returns number of playlist in library.
   *
   *
   *
   * This method provides access to the full `HttpResponse`, allowing access to response headers.
   * To access only the response body, use `count()` instead.
   *
   * This method doesn't expect any request body.
   */
  count$Response(params?: ServicePlaylistCount$Params, context?: HttpContext): Observable<StrictHttpResponse<number>> {
    const obs = servicePlaylistCount(this.http, this.rootUrl, params, context);
    return obs;
  }

  /**
   * Returns number of playlist in library.
   *
   *
   *
   * This method provides access only to the response body.
   * To access the full response (for headers, for example), `count$Response()` instead.
   *
   * This method doesn't expect any request body.
   */
  count(params?: ServicePlaylistCount$Params, context?: HttpContext): Observable<number> {
    const resp = this.count$Response(params, context);
    return resp.pipe(takeUntil(this.cancelPendingRequests$), 
      map((r: StrictHttpResponse<number>): number => r.body)
    );
  }

  /** Path part for operation `create()` */
  static readonly ServicePlaylistCreatePath = '/playlist/create';

  /**
   * Creates a new Playlist based on on a song list.
   *
   *
   *
   * This method provides access to the full `HttpResponse`, allowing access to response headers.
   * To access only the response body, use `create()` instead.
   *
   * This method sends `application/json` and handles request body of type `application/json`.
   */
  create$Response(params?: ServicePlaylistCreate$Params, context?: HttpContext): Observable<StrictHttpResponse<void>> {
    const obs = servicePlaylistCreate(this.http, this.rootUrl, params, context);
    return obs;
  }

  /**
   * Creates a new Playlist based on on a song list.
   *
   *
   *
   * This method provides access only to the response body.
   * To access the full response (for headers, for example), `create$Response()` instead.
   *
   * This method sends `application/json` and handles request body of type `application/json`.
   */
  create(params?: ServicePlaylistCreate$Params, context?: HttpContext): Observable<void> {
    const resp = this.create$Response(params, context);
    return resp.pipe(takeUntil(this.cancelPendingRequests$), 
      map((r: StrictHttpResponse<void>): void => r.body)
    );
  }

  /** Path part for operation `createFromAlbums()` */
  static readonly ServicePlaylistCreateFromAlbumsPath = '/playlist/createfromalbums';

  /**
   * Creates a new Playlist based on albums.
   *
   *
   *
   * This method provides access to the full `HttpResponse`, allowing access to response headers.
   * To access only the response body, use `createFromAlbums()` instead.
   *
   * This method sends `application/json` and handles request body of type `application/json`.
   */
  createFromAlbums$Response(params?: ServicePlaylistCreateFromAlbums$Params, context?: HttpContext): Observable<StrictHttpResponse<void>> {
    const obs = servicePlaylistCreateFromAlbums(this.http, this.rootUrl, params, context);
    return obs;
  }

  /**
   * Creates a new Playlist based on albums.
   *
   *
   *
   * This method provides access only to the response body.
   * To access the full response (for headers, for example), `createFromAlbums$Response()` instead.
   *
   * This method sends `application/json` and handles request body of type `application/json`.
   */
  createFromAlbums(params?: ServicePlaylistCreateFromAlbums$Params, context?: HttpContext): Observable<void> {
    const resp = this.createFromAlbums$Response(params, context);
    return resp.pipe(takeUntil(this.cancelPendingRequests$), 
      map((r: StrictHttpResponse<void>): void => r.body)
    );
  }

  /** Path part for operation `get()` */
  static readonly ServicePlaylistGetPath = '/playlist/{id}';

  /**
   * Returns an Playlist using an id.
   *
   *
   *
   * This method provides access to the full `HttpResponse`, allowing access to response headers.
   * To access only the response body, use `get()` instead.
   *
   * This method doesn't expect any request body.
   */
  get$Response(params: ServicePlaylistGet$Params, context?: HttpContext): Observable<StrictHttpResponse<Playlist>> {
    const obs = servicePlaylistGet(this.http, this.rootUrl, params, context);
    return obs;
  }

  /**
   * Returns an Playlist using an id.
   *
   *
   *
   * This method provides access only to the response body.
   * To access the full response (for headers, for example), `get$Response()` instead.
   *
   * This method doesn't expect any request body.
   */
  get(params: ServicePlaylistGet$Params, context?: HttpContext): Observable<Playlist> {
    const resp = this.get$Response(params, context);
    return resp.pipe(takeUntil(this.cancelPendingRequests$), 
      map((r: StrictHttpResponse<Playlist>): Playlist => r.body)
    );
  }

  /** Path part for operation `update()` */
  static readonly ServicePlaylistUpdatePath = '/playlist/{id}';

  /**
   * Updates an Playlist using an id.
   *
   *
   *
   * This method provides access to the full `HttpResponse`, allowing access to response headers.
   * To access only the response body, use `update()` instead.
   *
   * This method sends `application/json` and handles request body of type `application/json`.
   */
  update$Response(params: ServicePlaylistUpdate$Params, context?: HttpContext): Observable<StrictHttpResponse<void>> {
    const obs = servicePlaylistUpdate(this.http, this.rootUrl, params, context);
    return obs;
  }

  /**
   * Updates an Playlist using an id.
   *
   *
   *
   * This method provides access only to the response body.
   * To access the full response (for headers, for example), `update$Response()` instead.
   *
   * This method sends `application/json` and handles request body of type `application/json`.
   */
  update(params: ServicePlaylistUpdate$Params, context?: HttpContext): Observable<void> {
    const resp = this.update$Response(params, context);
    return resp.pipe(takeUntil(this.cancelPendingRequests$), 
      map((r: StrictHttpResponse<void>): void => r.body)
    );
  }

  /** Path part for operation `erase()` */
  static readonly ServicePlaylistErasePath = '/playlist/{id}';

  /**
   * Deletes an Playlist using an id.
   *
   *
   *
   * This method provides access to the full `HttpResponse`, allowing access to response headers.
   * To access only the response body, use `erase()` instead.
   *
   * This method doesn't expect any request body.
   */
  erase$Response(params: ServicePlaylistErase$Params, context?: HttpContext): Observable<StrictHttpResponse<void>> {
    const obs = servicePlaylistErase(this.http, this.rootUrl, params, context);
    return obs;
  }

  /**
   * Deletes an Playlist using an id.
   *
   *
   *
   * This method provides access only to the response body.
   * To access the full response (for headers, for example), `erase$Response()` instead.
   *
   * This method doesn't expect any request body.
   */
  erase(params: ServicePlaylistErase$Params, context?: HttpContext): Observable<void> {
    const resp = this.erase$Response(params, context);
    return resp.pipe(takeUntil(this.cancelPendingRequests$), 
      map((r: StrictHttpResponse<void>): void => r.body)
    );
  }



    getEntityName(): string {
        return 'Playlist';
    }
}