import { takeUntil } from 'rxjs/operators';
import { Identifier } from "../models/Identifier";
/* eslint-disable */
/* Code generated by ng-openapi-gen DO NOT EDIT. */

import { HttpClient, HttpContext } from '@angular/common/http';
import { Injectable } from '@angular/core';
import { Observable } from 'rxjs';
import { map } from 'rxjs/operators';

import { BaseService } from '../base-service';
import { ApiConfiguration } from '../api-configuration';
import { StrictHttpResponse } from '../strict-http-response';

import { PlaylistItem } from '../models/playlist-item';
import { servicePlaylistItemAdd } from '../fn/playlist-item/service-playlist-item-add';
import { ServicePlaylistItemAdd$Params } from '../fn/playlist-item/service-playlist-item-add';
import { servicePlaylistItemAddAlbum } from '../fn/playlist-item/service-playlist-item-add-album';
import { ServicePlaylistItemAddAlbum$Params } from '../fn/playlist-item/service-playlist-item-add-album';
import { servicePlaylistItemCount } from '../fn/playlist-item/service-playlist-item-count';
import { ServicePlaylistItemCount$Params } from '../fn/playlist-item/service-playlist-item-count';
import { servicePlaylistItemErase } from '../fn/playlist-item/service-playlist-item-erase';
import { ServicePlaylistItemErase$Params } from '../fn/playlist-item/service-playlist-item-erase';
import { servicePlaylistItemGet } from '../fn/playlist-item/service-playlist-item-get';
import { ServicePlaylistItemGet$Params } from '../fn/playlist-item/service-playlist-item-get';
import { servicePlaylistItemGetPage } from '../fn/playlist-item/service-playlist-item-get-page';
import { ServicePlaylistItemGetPage$Params } from '../fn/playlist-item/service-playlist-item-get-page';
import { servicePlaylistItemInsert } from '../fn/playlist-item/service-playlist-item-insert';
import { ServicePlaylistItemInsert$Params } from '../fn/playlist-item/service-playlist-item-insert';
import { servicePlaylistItemRemoveMultiple } from '../fn/playlist-item/service-playlist-item-remove-multiple';
import { ServicePlaylistItemRemoveMultiple$Params } from '../fn/playlist-item/service-playlist-item-remove-multiple';
import { servicePlaylistItemSetPlaylistItems } from '../fn/playlist-item/service-playlist-item-set-playlist-items';
import { ServicePlaylistItemSetPlaylistItems$Params } from '../fn/playlist-item/service-playlist-item-set-playlist-items';
import { servicePlaylistItemUpdate } from '../fn/playlist-item/service-playlist-item-update';
import { ServicePlaylistItemUpdate$Params } from '../fn/playlist-item/service-playlist-item-update';

@Injectable({ providedIn: 'root' })
export class PlaylistItemService extends BaseService<PlaylistItem> {
  
    constructor(config: ApiConfiguration, http: HttpClient) {
        super(config, http);  
        this.catchNullEntityIfAvailable();
    }
    

  /** Path part for operation `getPage()` */
  static readonly GetPagePath = '/playlistitem';

  /**
   * Returns PlaylistItem(s) using an filter.
   *  					Add an filter by using the '/filter' and '/condition' paths.					
   * You can sort them by an property.
   *
   *
   *
   * This method provides access to the full `HttpResponse`, allowing access to response headers.
   * To access only the response body, use `getPage()` instead.
   *
   * This method doesn't expect any request body.
   */
  getPage$Response(params?: ServicePlaylistItemGetPage$Params, context?: HttpContext): Observable<StrictHttpResponse<Array<PlaylistItem>>> {
    const obs = servicePlaylistItemGetPage(this.http, this.rootUrl, params, context);
    return obs;
  }

  /**
   * Returns PlaylistItem(s) using an filter.
   *  					Add an filter by using the '/filter' and '/condition' paths.					
   * You can sort them by an property.
   *
   *
   *
   * This method provides access only to the response body.
   * To access the full response (for headers, for example), `getPage$Response()` instead.
   *
   * This method doesn't expect any request body.
   */
  getPage(params?: ServicePlaylistItemGetPage$Params, context?: HttpContext): Observable<Array<PlaylistItem>> {
    const resp = this.getPage$Response(params, context);
    return resp.pipe(takeUntil(this.cancelPendingRequests$), 
      map((r: StrictHttpResponse<Array<PlaylistItem>>): Array<PlaylistItem> => r.body)
    );
  }

  /** Path part for operation `insert()` */
  static readonly ServicePlaylistItemInsertPath = '/playlistitem';

  /**
   * Creates an PlaylistItem. You can pass an empty id, it will then create one.
   *
   *
   *
   * This method provides access to the full `HttpResponse`, allowing access to response headers.
   * To access only the response body, use `insert()` instead.
   *
   * This method sends `application/json` and handles request body of type `application/json`.
   */
  insert$Response(params?: ServicePlaylistItemInsert$Params, context?: HttpContext): Observable<StrictHttpResponse<void>> {
    const obs = servicePlaylistItemInsert(this.http, this.rootUrl, params, context);
    return obs;
  }

  /**
   * Creates an PlaylistItem. You can pass an empty id, it will then create one.
   *
   *
   *
   * This method provides access only to the response body.
   * To access the full response (for headers, for example), `insert$Response()` instead.
   *
   * This method sends `application/json` and handles request body of type `application/json`.
   */
  insert(params?: ServicePlaylistItemInsert$Params, context?: HttpContext): Observable<void> {
    const resp = this.insert$Response(params, context);
    return resp.pipe(takeUntil(this.cancelPendingRequests$), 
      map((r: StrictHttpResponse<void>): void => r.body)
    );
  }

  /** Path part for operation `add()` */
  static readonly ServicePlaylistItemAddPath = '/playlistitem/add';

  /**
   * Adds multiple items to a playlist.
   *
   *
   *
   * This method provides access to the full `HttpResponse`, allowing access to response headers.
   * To access only the response body, use `add()` instead.
   *
   * This method sends `application/json` and handles request body of type `application/json`.
   */
  add$Response(params?: ServicePlaylistItemAdd$Params, context?: HttpContext): Observable<StrictHttpResponse<void>> {
    const obs = servicePlaylistItemAdd(this.http, this.rootUrl, params, context);
    return obs;
  }

  /**
   * Adds multiple items to a playlist.
   *
   *
   *
   * This method provides access only to the response body.
   * To access the full response (for headers, for example), `add$Response()` instead.
   *
   * This method sends `application/json` and handles request body of type `application/json`.
   */
  add(params?: ServicePlaylistItemAdd$Params, context?: HttpContext): Observable<void> {
    const resp = this.add$Response(params, context);
    return resp.pipe(takeUntil(this.cancelPendingRequests$), 
      map((r: StrictHttpResponse<void>): void => r.body)
    );
  }

  /** Path part for operation `addAlbum()` */
  static readonly ServicePlaylistItemAddAlbumPath = '/playlistitem/addalbum';

  /**
   * Adds multiple albums to a playlist.
   *
   *
   *
   * This method provides access to the full `HttpResponse`, allowing access to response headers.
   * To access only the response body, use `addAlbum()` instead.
   *
   * This method sends `application/json` and handles request body of type `application/json`.
   */
  addAlbum$Response(params?: ServicePlaylistItemAddAlbum$Params, context?: HttpContext): Observable<StrictHttpResponse<void>> {
    const obs = servicePlaylistItemAddAlbum(this.http, this.rootUrl, params, context);
    return obs;
  }

  /**
   * Adds multiple albums to a playlist.
   *
   *
   *
   * This method provides access only to the response body.
   * To access the full response (for headers, for example), `addAlbum$Response()` instead.
   *
   * This method sends `application/json` and handles request body of type `application/json`.
   */
  addAlbum(params?: ServicePlaylistItemAddAlbum$Params, context?: HttpContext): Observable<void> {
    const resp = this.addAlbum$Response(params, context);
    return resp.pipe(takeUntil(this.cancelPendingRequests$), 
      map((r: StrictHttpResponse<void>): void => r.body)
    );
  }

  /** Path part for operation `count()` */
  static readonly ServicePlaylistItemCountPath = '/playlistitem/count';

  /**
   * Get the count of playlist items.
   *
   *
   *
   * This method provides access to the full `HttpResponse`, allowing access to response headers.
   * To access only the response body, use `count()` instead.
   *
   * This method doesn't expect any request body.
   */
  count$Response(params?: ServicePlaylistItemCount$Params, context?: HttpContext): Observable<StrictHttpResponse<number>> {
    const obs = servicePlaylistItemCount(this.http, this.rootUrl, params, context);
    return obs;
  }

  /**
   * Get the count of playlist items.
   *
   *
   *
   * This method provides access only to the response body.
   * To access the full response (for headers, for example), `count$Response()` instead.
   *
   * This method doesn't expect any request body.
   */
  count(params?: ServicePlaylistItemCount$Params, context?: HttpContext): Observable<number> {
    const resp = this.count$Response(params, context);
    return resp.pipe(takeUntil(this.cancelPendingRequests$), 
      map((r: StrictHttpResponse<number>): number => r.body)
    );
  }

  /** Path part for operation `removeMultiple()` */
  static readonly ServicePlaylistItemRemoveMultiplePath = '/playlistitem/removemultiple';

  /**
   * Removes multiple items from a playlist.
   *
   *
   *
   * This method provides access to the full `HttpResponse`, allowing access to response headers.
   * To access only the response body, use `removeMultiple()` instead.
   *
   * This method sends `application/json` and handles request body of type `application/json`.
   */
  removeMultiple$Response(params?: ServicePlaylistItemRemoveMultiple$Params, context?: HttpContext): Observable<StrictHttpResponse<void>> {
    const obs = servicePlaylistItemRemoveMultiple(this.http, this.rootUrl, params, context);
    return obs;
  }

  /**
   * Removes multiple items from a playlist.
   *
   *
   *
   * This method provides access only to the response body.
   * To access the full response (for headers, for example), `removeMultiple$Response()` instead.
   *
   * This method sends `application/json` and handles request body of type `application/json`.
   */
  removeMultiple(params?: ServicePlaylistItemRemoveMultiple$Params, context?: HttpContext): Observable<void> {
    const resp = this.removeMultiple$Response(params, context);
    return resp.pipe(takeUntil(this.cancelPendingRequests$), 
      map((r: StrictHttpResponse<void>): void => r.body)
    );
  }

  /** Path part for operation `setPlaylistItems()` */
  static readonly ServicePlaylistItemSetPlaylistItemsPath = '/playlistitem/setplaylistitems';

  /**
   * Updates a list of playlist items.
   *
   *
   *
   * This method provides access to the full `HttpResponse`, allowing access to response headers.
   * To access only the response body, use `setPlaylistItems()` instead.
   *
   * This method sends `application/json` and handles request body of type `application/json`.
   */
  setPlaylistItems$Response(params?: ServicePlaylistItemSetPlaylistItems$Params, context?: HttpContext): Observable<StrictHttpResponse<void>> {
    const obs = servicePlaylistItemSetPlaylistItems(this.http, this.rootUrl, params, context);
    return obs;
  }

  /**
   * Updates a list of playlist items.
   *
   *
   *
   * This method provides access only to the response body.
   * To access the full response (for headers, for example), `setPlaylistItems$Response()` instead.
   *
   * This method sends `application/json` and handles request body of type `application/json`.
   */
  setPlaylistItems(params?: ServicePlaylistItemSetPlaylistItems$Params, context?: HttpContext): Observable<void> {
    const resp = this.setPlaylistItems$Response(params, context);
    return resp.pipe(takeUntil(this.cancelPendingRequests$), 
      map((r: StrictHttpResponse<void>): void => r.body)
    );
  }

  /** Path part for operation `get()` */
  static readonly ServicePlaylistItemGetPath = '/playlistitem/{id}';

  /**
   * Returns an PlaylistItem using an id.
   *
   *
   *
   * This method provides access to the full `HttpResponse`, allowing access to response headers.
   * To access only the response body, use `get()` instead.
   *
   * This method doesn't expect any request body.
   */
  get$Response(params: ServicePlaylistItemGet$Params, context?: HttpContext): Observable<StrictHttpResponse<PlaylistItem>> {
    const obs = servicePlaylistItemGet(this.http, this.rootUrl, params, context);
    return obs;
  }

  /**
   * Returns an PlaylistItem using an id.
   *
   *
   *
   * This method provides access only to the response body.
   * To access the full response (for headers, for example), `get$Response()` instead.
   *
   * This method doesn't expect any request body.
   */
  get(params: ServicePlaylistItemGet$Params, context?: HttpContext): Observable<PlaylistItem> {
    const resp = this.get$Response(params, context);
    return resp.pipe(takeUntil(this.cancelPendingRequests$), 
      map((r: StrictHttpResponse<PlaylistItem>): PlaylistItem => r.body)
    );
  }

  /** Path part for operation `update()` */
  static readonly ServicePlaylistItemUpdatePath = '/playlistitem/{id}';

  /**
   * Updates an PlaylistItem using an id.
   *
   *
   *
   * This method provides access to the full `HttpResponse`, allowing access to response headers.
   * To access only the response body, use `update()` instead.
   *
   * This method sends `application/json` and handles request body of type `application/json`.
   */
  update$Response(params: ServicePlaylistItemUpdate$Params, context?: HttpContext): Observable<StrictHttpResponse<void>> {
    const obs = servicePlaylistItemUpdate(this.http, this.rootUrl, params, context);
    return obs;
  }

  /**
   * Updates an PlaylistItem using an id.
   *
   *
   *
   * This method provides access only to the response body.
   * To access the full response (for headers, for example), `update$Response()` instead.
   *
   * This method sends `application/json` and handles request body of type `application/json`.
   */
  update(params: ServicePlaylistItemUpdate$Params, context?: HttpContext): Observable<void> {
    const resp = this.update$Response(params, context);
    return resp.pipe(takeUntil(this.cancelPendingRequests$), 
      map((r: StrictHttpResponse<void>): void => r.body)
    );
  }

  /** Path part for operation `erase()` */
  static readonly ServicePlaylistItemErasePath = '/playlistitem/{id}';

  /**
   * Deletes an PlaylistItem using an id.
   *
   *
   *
   * This method provides access to the full `HttpResponse`, allowing access to response headers.
   * To access only the response body, use `erase()` instead.
   *
   * This method doesn't expect any request body.
   */
  erase$Response(params: ServicePlaylistItemErase$Params, context?: HttpContext): Observable<StrictHttpResponse<void>> {
    const obs = servicePlaylistItemErase(this.http, this.rootUrl, params, context);
    return obs;
  }

  /**
   * Deletes an PlaylistItem using an id.
   *
   *
   *
   * This method provides access only to the response body.
   * To access the full response (for headers, for example), `erase$Response()` instead.
   *
   * This method doesn't expect any request body.
   */
  erase(params: ServicePlaylistItemErase$Params, context?: HttpContext): Observable<void> {
    const resp = this.erase$Response(params, context);
    return resp.pipe(takeUntil(this.cancelPendingRequests$), 
      map((r: StrictHttpResponse<void>): void => r.body)
    );
  }



    getEntityName(): string {
        return 'PlaylistItem';
    }
}