import { takeUntil } from 'rxjs/operators';
import { Identifier } from "../models/Identifier";
/* eslint-disable */
/* Code generated by ng-openapi-gen DO NOT EDIT. */

import { HttpClient, HttpContext } from '@angular/common/http';
import { Injectable } from '@angular/core';
import { Observable } from 'rxjs';
import { map } from 'rxjs/operators';

import { BaseService } from '../base-service';
import { ApiConfiguration } from '../api-configuration';
import { StrictHttpResponse } from '../strict-http-response';

import { serviceSettingErase } from '../fn/setting/service-setting-erase';
import { ServiceSettingErase$Params } from '../fn/setting/service-setting-erase';
import { serviceSettingGet } from '../fn/setting/service-setting-get';
import { ServiceSettingGet$Params } from '../fn/setting/service-setting-get';
import { serviceSettingGetPage } from '../fn/setting/service-setting-get-page';
import { ServiceSettingGetPage$Params } from '../fn/setting/service-setting-get-page';
import { serviceSettingInsert } from '../fn/setting/service-setting-insert';
import { ServiceSettingInsert$Params } from '../fn/setting/service-setting-insert';
import { serviceSettingUpdate } from '../fn/setting/service-setting-update';
import { ServiceSettingUpdate$Params } from '../fn/setting/service-setting-update';
import { Setting } from '../models/setting';

@Injectable({ providedIn: 'root' })
export class SettingService extends BaseService<Setting> {
  
    constructor(config: ApiConfiguration, http: HttpClient) {
        super(config, http);  
        this.catchNullEntityIfAvailable();
    }
    

  /** Path part for operation `getPage()` */
  static readonly GetPagePath = '/setting';

  /**
   * Returns Setting(s) using an filter.
   *  					Add an filter by using the '/filter' and '/condition' paths.					
   * You can sort them by an property.
   *
   *
   *
   * This method provides access to the full `HttpResponse`, allowing access to response headers.
   * To access only the response body, use `getPage()` instead.
   *
   * This method doesn't expect any request body.
   */
  getPage$Response(params?: ServiceSettingGetPage$Params, context?: HttpContext): Observable<StrictHttpResponse<Array<Setting>>> {
    const obs = serviceSettingGetPage(this.http, this.rootUrl, params, context);
    return obs;
  }

  /**
   * Returns Setting(s) using an filter.
   *  					Add an filter by using the '/filter' and '/condition' paths.					
   * You can sort them by an property.
   *
   *
   *
   * This method provides access only to the response body.
   * To access the full response (for headers, for example), `getPage$Response()` instead.
   *
   * This method doesn't expect any request body.
   */
  getPage(params?: ServiceSettingGetPage$Params, context?: HttpContext): Observable<Array<Setting>> {
    const resp = this.getPage$Response(params, context);
    return resp.pipe(takeUntil(this.cancelPendingRequests$), 
      map((r: StrictHttpResponse<Array<Setting>>): Array<Setting> => r.body)
    );
  }

  /** Path part for operation `insert()` */
  static readonly ServiceSettingInsertPath = '/setting';

  /**
   * Creates an Setting. You can pass an empty id, it will then create one.
   *
   *
   *
   * This method provides access to the full `HttpResponse`, allowing access to response headers.
   * To access only the response body, use `insert()` instead.
   *
   * This method sends `application/json` and handles request body of type `application/json`.
   */
  insert$Response(params?: ServiceSettingInsert$Params, context?: HttpContext): Observable<StrictHttpResponse<void>> {
    const obs = serviceSettingInsert(this.http, this.rootUrl, params, context);
    return obs;
  }

  /**
   * Creates an Setting. You can pass an empty id, it will then create one.
   *
   *
   *
   * This method provides access only to the response body.
   * To access the full response (for headers, for example), `insert$Response()` instead.
   *
   * This method sends `application/json` and handles request body of type `application/json`.
   */
  insert(params?: ServiceSettingInsert$Params, context?: HttpContext): Observable<void> {
    const resp = this.insert$Response(params, context);
    return resp.pipe(takeUntil(this.cancelPendingRequests$), 
      map((r: StrictHttpResponse<void>): void => r.body)
    );
  }

  /** Path part for operation `get()` */
  static readonly ServiceSettingGetPath = '/setting/{id}';

  /**
   * Returns an Setting using an id.
   *
   *
   *
   * This method provides access to the full `HttpResponse`, allowing access to response headers.
   * To access only the response body, use `get()` instead.
   *
   * This method doesn't expect any request body.
   */
  get$Response(params: ServiceSettingGet$Params, context?: HttpContext): Observable<StrictHttpResponse<Setting>> {
    const obs = serviceSettingGet(this.http, this.rootUrl, params, context);
    return obs;
  }

  /**
   * Returns an Setting using an id.
   *
   *
   *
   * This method provides access only to the response body.
   * To access the full response (for headers, for example), `get$Response()` instead.
   *
   * This method doesn't expect any request body.
   */
  get(params: ServiceSettingGet$Params, context?: HttpContext): Observable<Setting> {
    const resp = this.get$Response(params, context);
    return resp.pipe(takeUntil(this.cancelPendingRequests$), 
      map((r: StrictHttpResponse<Setting>): Setting => r.body)
    );
  }

  /** Path part for operation `update()` */
  static readonly ServiceSettingUpdatePath = '/setting/{id}';

  /**
   * Updates an Setting using an id.
   *
   *
   *
   * This method provides access to the full `HttpResponse`, allowing access to response headers.
   * To access only the response body, use `update()` instead.
   *
   * This method sends `application/json` and handles request body of type `application/json`.
   */
  update$Response(params: ServiceSettingUpdate$Params, context?: HttpContext): Observable<StrictHttpResponse<void>> {
    const obs = serviceSettingUpdate(this.http, this.rootUrl, params, context);
    return obs;
  }

  /**
   * Updates an Setting using an id.
   *
   *
   *
   * This method provides access only to the response body.
   * To access the full response (for headers, for example), `update$Response()` instead.
   *
   * This method sends `application/json` and handles request body of type `application/json`.
   */
  update(params: ServiceSettingUpdate$Params, context?: HttpContext): Observable<void> {
    const resp = this.update$Response(params, context);
    return resp.pipe(takeUntil(this.cancelPendingRequests$), 
      map((r: StrictHttpResponse<void>): void => r.body)
    );
  }

  /** Path part for operation `erase()` */
  static readonly ServiceSettingErasePath = '/setting/{id}';

  /**
   * Deletes an Setting using an id.
   *
   *
   *
   * This method provides access to the full `HttpResponse`, allowing access to response headers.
   * To access only the response body, use `erase()` instead.
   *
   * This method doesn't expect any request body.
   */
  erase$Response(params: ServiceSettingErase$Params, context?: HttpContext): Observable<StrictHttpResponse<void>> {
    const obs = serviceSettingErase(this.http, this.rootUrl, params, context);
    return obs;
  }

  /**
   * Deletes an Setting using an id.
   *
   *
   *
   * This method provides access only to the response body.
   * To access the full response (for headers, for example), `erase$Response()` instead.
   *
   * This method doesn't expect any request body.
   */
  erase(params: ServiceSettingErase$Params, context?: HttpContext): Observable<void> {
    const resp = this.erase$Response(params, context);
    return resp.pipe(takeUntil(this.cancelPendingRequests$), 
      map((r: StrictHttpResponse<void>): void => r.body)
    );
  }



    getEntityName(): string {
        return 'Setting';
    }
}