import { takeUntil } from 'rxjs/operators';
import { Identifier } from "../models/Identifier";
/* eslint-disable */
/* Code generated by ng-openapi-gen DO NOT EDIT. */

import { HttpClient, HttpContext } from '@angular/common/http';
import { Injectable } from '@angular/core';
import { Observable } from 'rxjs';
import { map } from 'rxjs/operators';

import { BaseService } from '../base-service';
import { ApiConfiguration } from '../api-configuration';
import { StrictHttpResponse } from '../strict-http-response';

import { serviceSongIdentifierErase } from '../fn/song-identifier/service-song-identifier-erase';
import { ServiceSongIdentifierErase$Params } from '../fn/song-identifier/service-song-identifier-erase';
import { serviceSongIdentifierGet } from '../fn/song-identifier/service-song-identifier-get';
import { ServiceSongIdentifierGet$Params } from '../fn/song-identifier/service-song-identifier-get';
import { serviceSongIdentifierGetPage } from '../fn/song-identifier/service-song-identifier-get-page';
import { ServiceSongIdentifierGetPage$Params } from '../fn/song-identifier/service-song-identifier-get-page';
import { serviceSongIdentifierInsert } from '../fn/song-identifier/service-song-identifier-insert';
import { ServiceSongIdentifierInsert$Params } from '../fn/song-identifier/service-song-identifier-insert';
import { serviceSongIdentifierUpdate } from '../fn/song-identifier/service-song-identifier-update';
import { ServiceSongIdentifierUpdate$Params } from '../fn/song-identifier/service-song-identifier-update';
import { SongIdentifier } from '../models/song-identifier';

@Injectable({ providedIn: 'root' })
export class SongIdentifierService extends BaseService<SongIdentifier> {
  
    constructor(config: ApiConfiguration, http: HttpClient) {
        super(config, http);  
        this.catchNullEntityIfAvailable();
    }
    

  /** Path part for operation `getPage()` */
  static readonly GetPagePath = '/songidentifier';

  /**
   * Returns SongIdentifier(s) using an filter.
   *  					Add an filter by using the '/filter' and '/condition' paths.					
   * You can sort them by an property.
   *
   *
   *
   * This method provides access to the full `HttpResponse`, allowing access to response headers.
   * To access only the response body, use `getPage()` instead.
   *
   * This method doesn't expect any request body.
   */
  getPage$Response(params?: ServiceSongIdentifierGetPage$Params, context?: HttpContext): Observable<StrictHttpResponse<Array<SongIdentifier>>> {
    const obs = serviceSongIdentifierGetPage(this.http, this.rootUrl, params, context);
    return obs;
  }

  /**
   * Returns SongIdentifier(s) using an filter.
   *  					Add an filter by using the '/filter' and '/condition' paths.					
   * You can sort them by an property.
   *
   *
   *
   * This method provides access only to the response body.
   * To access the full response (for headers, for example), `getPage$Response()` instead.
   *
   * This method doesn't expect any request body.
   */
  getPage(params?: ServiceSongIdentifierGetPage$Params, context?: HttpContext): Observable<Array<SongIdentifier>> {
    const resp = this.getPage$Response(params, context);
    return resp.pipe(takeUntil(this.cancelPendingRequests$), 
      map((r: StrictHttpResponse<Array<SongIdentifier>>): Array<SongIdentifier> => r.body)
    );
  }

  /** Path part for operation `insert()` */
  static readonly ServiceSongIdentifierInsertPath = '/songidentifier';

  /**
   * Creates an SongIdentifier. You can pass an empty id, it will then create one.
   *
   *
   *
   * This method provides access to the full `HttpResponse`, allowing access to response headers.
   * To access only the response body, use `insert()` instead.
   *
   * This method sends `application/json` and handles request body of type `application/json`.
   */
  insert$Response(params?: ServiceSongIdentifierInsert$Params, context?: HttpContext): Observable<StrictHttpResponse<void>> {
    const obs = serviceSongIdentifierInsert(this.http, this.rootUrl, params, context);
    return obs;
  }

  /**
   * Creates an SongIdentifier. You can pass an empty id, it will then create one.
   *
   *
   *
   * This method provides access only to the response body.
   * To access the full response (for headers, for example), `insert$Response()` instead.
   *
   * This method sends `application/json` and handles request body of type `application/json`.
   */
  insert(params?: ServiceSongIdentifierInsert$Params, context?: HttpContext): Observable<void> {
    const resp = this.insert$Response(params, context);
    return resp.pipe(takeUntil(this.cancelPendingRequests$), 
      map((r: StrictHttpResponse<void>): void => r.body)
    );
  }

  /** Path part for operation `get()` */
  static readonly ServiceSongIdentifierGetPath = '/songidentifier/{id}';

  /**
   * Returns an SongIdentifier using an id.
   *
   *
   *
   * This method provides access to the full `HttpResponse`, allowing access to response headers.
   * To access only the response body, use `get()` instead.
   *
   * This method doesn't expect any request body.
   */
  get$Response(params: ServiceSongIdentifierGet$Params, context?: HttpContext): Observable<StrictHttpResponse<SongIdentifier>> {
    const obs = serviceSongIdentifierGet(this.http, this.rootUrl, params, context);
    return obs;
  }

  /**
   * Returns an SongIdentifier using an id.
   *
   *
   *
   * This method provides access only to the response body.
   * To access the full response (for headers, for example), `get$Response()` instead.
   *
   * This method doesn't expect any request body.
   */
  get(params: ServiceSongIdentifierGet$Params, context?: HttpContext): Observable<SongIdentifier> {
    const resp = this.get$Response(params, context);
    return resp.pipe(takeUntil(this.cancelPendingRequests$), 
      map((r: StrictHttpResponse<SongIdentifier>): SongIdentifier => r.body)
    );
  }

  /** Path part for operation `update()` */
  static readonly ServiceSongIdentifierUpdatePath = '/songidentifier/{id}';

  /**
   * Updates an SongIdentifier using an id.
   *
   *
   *
   * This method provides access to the full `HttpResponse`, allowing access to response headers.
   * To access only the response body, use `update()` instead.
   *
   * This method sends `application/json` and handles request body of type `application/json`.
   */
  update$Response(params: ServiceSongIdentifierUpdate$Params, context?: HttpContext): Observable<StrictHttpResponse<void>> {
    const obs = serviceSongIdentifierUpdate(this.http, this.rootUrl, params, context);
    return obs;
  }

  /**
   * Updates an SongIdentifier using an id.
   *
   *
   *
   * This method provides access only to the response body.
   * To access the full response (for headers, for example), `update$Response()` instead.
   *
   * This method sends `application/json` and handles request body of type `application/json`.
   */
  update(params: ServiceSongIdentifierUpdate$Params, context?: HttpContext): Observable<void> {
    const resp = this.update$Response(params, context);
    return resp.pipe(takeUntil(this.cancelPendingRequests$), 
      map((r: StrictHttpResponse<void>): void => r.body)
    );
  }

  /** Path part for operation `erase()` */
  static readonly ServiceSongIdentifierErasePath = '/songidentifier/{id}';

  /**
   * Deletes an SongIdentifier using an id.
   *
   *
   *
   * This method provides access to the full `HttpResponse`, allowing access to response headers.
   * To access only the response body, use `erase()` instead.
   *
   * This method doesn't expect any request body.
   */
  erase$Response(params: ServiceSongIdentifierErase$Params, context?: HttpContext): Observable<StrictHttpResponse<void>> {
    const obs = serviceSongIdentifierErase(this.http, this.rootUrl, params, context);
    return obs;
  }

  /**
   * Deletes an SongIdentifier using an id.
   *
   *
   *
   * This method provides access only to the response body.
   * To access the full response (for headers, for example), `erase$Response()` instead.
   *
   * This method doesn't expect any request body.
   */
  erase(params: ServiceSongIdentifierErase$Params, context?: HttpContext): Observable<void> {
    const resp = this.erase$Response(params, context);
    return resp.pipe(takeUntil(this.cancelPendingRequests$), 
      map((r: StrictHttpResponse<void>): void => r.body)
    );
  }



    getEntityName(): string {
        return 'SongIdentifier';
    }
}