import { takeUntil } from 'rxjs/operators';
import { Identifier } from "../models/Identifier";
/* eslint-disable */
/* Code generated by ng-openapi-gen DO NOT EDIT. */

import { HttpClient, HttpContext } from '@angular/common/http';
import { Injectable } from '@angular/core';
import { Observable } from 'rxjs';
import { map } from 'rxjs/operators';

import { BaseService } from '../base-service';
import { ApiConfiguration } from '../api-configuration';
import { StrictHttpResponse } from '../strict-http-response';

import { MetricsChartEntry } from '../models/metrics-chart-entry';
import { serviceSongMetricsErase } from '../fn/song-metrics/service-song-metrics-erase';
import { ServiceSongMetricsErase$Params } from '../fn/song-metrics/service-song-metrics-erase';
import { serviceSongMetricsGet } from '../fn/song-metrics/service-song-metrics-get';
import { ServiceSongMetricsGet$Params } from '../fn/song-metrics/service-song-metrics-get';
import { serviceSongMetricsGetChartData } from '../fn/song-metrics/service-song-metrics-get-chart-data';
import { ServiceSongMetricsGetChartData$Params } from '../fn/song-metrics/service-song-metrics-get-chart-data';
import { serviceSongMetricsGetPage } from '../fn/song-metrics/service-song-metrics-get-page';
import { ServiceSongMetricsGetPage$Params } from '../fn/song-metrics/service-song-metrics-get-page';
import { SongMetrics } from '../models/song-metrics';

@Injectable({ providedIn: 'root' })
export class SongMetricsService extends BaseService<SongMetrics> {
  
    constructor(config: ApiConfiguration, http: HttpClient) {
        super(config, http);  
        this.catchNullEntityIfAvailable();
    }
    

  /** Path part for operation `getPage()` */
  static readonly GetPagePath = '/songmetrics';

  /**
   * Returns SongMetrics(s) using an filter.
   *  					Add an filter by using the '/filter' and '/condition' paths.					
   * You can sort them by an property.
   *
   *
   *
   * This method provides access to the full `HttpResponse`, allowing access to response headers.
   * To access only the response body, use `getPage()` instead.
   *
   * This method doesn't expect any request body.
   */
  getPage$Response(params?: ServiceSongMetricsGetPage$Params, context?: HttpContext): Observable<StrictHttpResponse<Array<SongMetrics>>> {
    const obs = serviceSongMetricsGetPage(this.http, this.rootUrl, params, context);
    return obs;
  }

  /**
   * Returns SongMetrics(s) using an filter.
   *  					Add an filter by using the '/filter' and '/condition' paths.					
   * You can sort them by an property.
   *
   *
   *
   * This method provides access only to the response body.
   * To access the full response (for headers, for example), `getPage$Response()` instead.
   *
   * This method doesn't expect any request body.
   */
  getPage(params?: ServiceSongMetricsGetPage$Params, context?: HttpContext): Observable<Array<SongMetrics>> {
    const resp = this.getPage$Response(params, context);
    return resp.pipe(takeUntil(this.cancelPendingRequests$), 
      map((r: StrictHttpResponse<Array<SongMetrics>>): Array<SongMetrics> => r.body)
    );
  }

  /** Path part for operation `getChartData()` */
  static readonly ServiceSongMetricsGetChartDataPath = '/songmetrics/getchartdata';

  /**
   * Get song metrics chart data.
   *
   *
   *
   * This method provides access to the full `HttpResponse`, allowing access to response headers.
   * To access only the response body, use `getChartData()` instead.
   *
   * This method doesn't expect any request body.
   */
  getChartData$Response(params?: ServiceSongMetricsGetChartData$Params, context?: HttpContext): Observable<StrictHttpResponse<Array<MetricsChartEntry>>> {
    const obs = serviceSongMetricsGetChartData(this.http, this.rootUrl, params, context);
    return obs;
  }

  /**
   * Get song metrics chart data.
   *
   *
   *
   * This method provides access only to the response body.
   * To access the full response (for headers, for example), `getChartData$Response()` instead.
   *
   * This method doesn't expect any request body.
   */
  getChartData(params?: ServiceSongMetricsGetChartData$Params, context?: HttpContext): Observable<Array<MetricsChartEntry>> {
    const resp = this.getChartData$Response(params, context);
    return resp.pipe(takeUntil(this.cancelPendingRequests$), 
      map((r: StrictHttpResponse<Array<MetricsChartEntry>>): Array<MetricsChartEntry> => r.body)
    );
  }

  /** Path part for operation `get()` */
  static readonly ServiceSongMetricsGetPath = '/songmetrics/{id}';

  /**
   * Returns an SongMetrics using an id.
   *
   *
   *
   * This method provides access to the full `HttpResponse`, allowing access to response headers.
   * To access only the response body, use `get()` instead.
   *
   * This method doesn't expect any request body.
   */
  get$Response(params: ServiceSongMetricsGet$Params, context?: HttpContext): Observable<StrictHttpResponse<SongMetrics>> {
    const obs = serviceSongMetricsGet(this.http, this.rootUrl, params, context);
    return obs;
  }

  /**
   * Returns an SongMetrics using an id.
   *
   *
   *
   * This method provides access only to the response body.
   * To access the full response (for headers, for example), `get$Response()` instead.
   *
   * This method doesn't expect any request body.
   */
  get(params: ServiceSongMetricsGet$Params, context?: HttpContext): Observable<SongMetrics> {
    const resp = this.get$Response(params, context);
    return resp.pipe(takeUntil(this.cancelPendingRequests$), 
      map((r: StrictHttpResponse<SongMetrics>): SongMetrics => r.body)
    );
  }

  /** Path part for operation `erase()` */
  static readonly ServiceSongMetricsErasePath = '/songmetrics/{id}';

  /**
   * Deletes an SongMetrics using an id.
   *
   *
   *
   * This method provides access to the full `HttpResponse`, allowing access to response headers.
   * To access only the response body, use `erase()` instead.
   *
   * This method doesn't expect any request body.
   */
  erase$Response(params: ServiceSongMetricsErase$Params, context?: HttpContext): Observable<StrictHttpResponse<void>> {
    const obs = serviceSongMetricsErase(this.http, this.rootUrl, params, context);
    return obs;
  }

  /**
   * Deletes an SongMetrics using an id.
   *
   *
   *
   * This method provides access only to the response body.
   * To access the full response (for headers, for example), `erase$Response()` instead.
   *
   * This method doesn't expect any request body.
   */
  erase(params: ServiceSongMetricsErase$Params, context?: HttpContext): Observable<void> {
    const resp = this.erase$Response(params, context);
    return resp.pipe(takeUntil(this.cancelPendingRequests$), 
      map((r: StrictHttpResponse<void>): void => r.body)
    );
  }



    getEntityName(): string {
        return 'SongMetrics';
    }
}