import { takeUntil } from 'rxjs/operators';
import { Identifier } from "../models/Identifier";
/* eslint-disable */
/* Code generated by ng-openapi-gen DO NOT EDIT. */

import { HttpClient, HttpContext } from '@angular/common/http';
import { Injectable } from '@angular/core';
import { Observable } from 'rxjs';
import { map } from 'rxjs/operators';

import { BaseService } from '../base-service';
import { ApiConfiguration } from '../api-configuration';
import { StrictHttpResponse } from '../strict-http-response';

import { CloudSearch } from '../models/cloud-search';
import { serviceSongCount } from '../fn/song/service-song-count';
import { ServiceSongCount$Params } from '../fn/song/service-song-count';
import { serviceSongErase } from '../fn/song/service-song-erase';
import { ServiceSongErase$Params } from '../fn/song/service-song-erase';
import { serviceSongGet } from '../fn/song/service-song-get';
import { ServiceSongGet$Params } from '../fn/song/service-song-get';
import { serviceSongGetCloudStatus } from '../fn/song/service-song-get-cloud-status';
import { ServiceSongGetCloudStatus$Params } from '../fn/song/service-song-get-cloud-status';
import { serviceSongGetPage } from '../fn/song/service-song-get-page';
import { ServiceSongGetPage$Params } from '../fn/song/service-song-get-page';
import { serviceSongGetSongListForArtist } from '../fn/song/service-song-get-song-list-for-artist';
import { ServiceSongGetSongListForArtist$Params } from '../fn/song/service-song-get-song-list-for-artist';
import { serviceSongInsert } from '../fn/song/service-song-insert';
import { ServiceSongInsert$Params } from '../fn/song/service-song-insert';
import { serviceSongUpdate } from '../fn/song/service-song-update';
import { ServiceSongUpdate$Params } from '../fn/song/service-song-update';
import { serviceSongUpdateSongPositions } from '../fn/song/service-song-update-song-positions';
import { ServiceSongUpdateSongPositions$Params } from '../fn/song/service-song-update-song-positions';
import { Song } from '../models/song';

@Injectable({ providedIn: 'root' })
export class SongService extends BaseService<Song> {
  
    constructor(config: ApiConfiguration, http: HttpClient) {
        super(config, http);  
        this.catchNullEntityIfAvailable();
    }
    

  /** Path part for operation `getPage()` */
  static readonly GetPagePath = '/song';

  /**
   * Returns Song(s) using an filter.
   *  					Add an filter by using the '/filter' and '/condition' paths.					
   * You can sort them by an property.
   *
   *
   *
   * This method provides access to the full `HttpResponse`, allowing access to response headers.
   * To access only the response body, use `getPage()` instead.
   *
   * This method doesn't expect any request body.
   */
  getPage$Response(params?: ServiceSongGetPage$Params, context?: HttpContext): Observable<StrictHttpResponse<Array<Song>>> {
    const obs = serviceSongGetPage(this.http, this.rootUrl, params, context);
    return obs;
  }

  /**
   * Returns Song(s) using an filter.
   *  					Add an filter by using the '/filter' and '/condition' paths.					
   * You can sort them by an property.
   *
   *
   *
   * This method provides access only to the response body.
   * To access the full response (for headers, for example), `getPage$Response()` instead.
   *
   * This method doesn't expect any request body.
   */
  getPage(params?: ServiceSongGetPage$Params, context?: HttpContext): Observable<Array<Song>> {
    const resp = this.getPage$Response(params, context);
    return resp.pipe(takeUntil(this.cancelPendingRequests$), 
      map((r: StrictHttpResponse<Array<Song>>): Array<Song> => r.body)
    );
  }

  /** Path part for operation `insert()` */
  static readonly ServiceSongInsertPath = '/song';

  /**
   * Creates an Song. You can pass an empty id, it will then create one.
   *
   *
   *
   * This method provides access to the full `HttpResponse`, allowing access to response headers.
   * To access only the response body, use `insert()` instead.
   *
   * This method sends `application/json` and handles request body of type `application/json`.
   */
  insert$Response(params?: ServiceSongInsert$Params, context?: HttpContext): Observable<StrictHttpResponse<void>> {
    const obs = serviceSongInsert(this.http, this.rootUrl, params, context);
    return obs;
  }

  /**
   * Creates an Song. You can pass an empty id, it will then create one.
   *
   *
   *
   * This method provides access only to the response body.
   * To access the full response (for headers, for example), `insert$Response()` instead.
   *
   * This method sends `application/json` and handles request body of type `application/json`.
   */
  insert(params?: ServiceSongInsert$Params, context?: HttpContext): Observable<void> {
    const resp = this.insert$Response(params, context);
    return resp.pipe(takeUntil(this.cancelPendingRequests$), 
      map((r: StrictHttpResponse<void>): void => r.body)
    );
  }

  /** Path part for operation `count()` */
  static readonly ServiceSongCountPath = '/song/count';

  /**
   * Returns number of songs in library.
   *
   *
   *
   * This method provides access to the full `HttpResponse`, allowing access to response headers.
   * To access only the response body, use `count()` instead.
   *
   * This method doesn't expect any request body.
   */
  count$Response(params?: ServiceSongCount$Params, context?: HttpContext): Observable<StrictHttpResponse<number>> {
    const obs = serviceSongCount(this.http, this.rootUrl, params, context);
    return obs;
  }

  /**
   * Returns number of songs in library.
   *
   *
   *
   * This method provides access only to the response body.
   * To access the full response (for headers, for example), `count$Response()` instead.
   *
   * This method doesn't expect any request body.
   */
  count(params?: ServiceSongCount$Params, context?: HttpContext): Observable<number> {
    const resp = this.count$Response(params, context);
    return resp.pipe(takeUntil(this.cancelPendingRequests$), 
      map((r: StrictHttpResponse<number>): number => r.body)
    );
  }

  /** Path part for operation `getSongListForArtist()` */
  static readonly ServiceSongGetSongListForArtistPath = '/song/getsonglistforartist';

  /**
   * Returns a list of songs for the given artist.
   *
   *
   *
   * This method provides access to the full `HttpResponse`, allowing access to response headers.
   * To access only the response body, use `getSongListForArtist()` instead.
   *
   * This method doesn't expect any request body.
   */
  getSongListForArtist$Response(params?: ServiceSongGetSongListForArtist$Params, context?: HttpContext): Observable<StrictHttpResponse<Array<Song>>> {
    const obs = serviceSongGetSongListForArtist(this.http, this.rootUrl, params, context);
    return obs;
  }

  /**
   * Returns a list of songs for the given artist.
   *
   *
   *
   * This method provides access only to the response body.
   * To access the full response (for headers, for example), `getSongListForArtist$Response()` instead.
   *
   * This method doesn't expect any request body.
   */
  getSongListForArtist(params?: ServiceSongGetSongListForArtist$Params, context?: HttpContext): Observable<Array<Song>> {
    const resp = this.getSongListForArtist$Response(params, context);
    return resp.pipe(takeUntil(this.cancelPendingRequests$), 
      map((r: StrictHttpResponse<Array<Song>>): Array<Song> => r.body)
    );
  }

  /** Path part for operation `updateSongPositions()` */
  static readonly ServiceSongUpdateSongPositionsPath = '/song/updatesongpositions';

  /**
   * Update the position of songs.
   *
   *
   *
   * This method provides access to the full `HttpResponse`, allowing access to response headers.
   * To access only the response body, use `updateSongPositions()` instead.
   *
   * This method sends `application/json` and handles request body of type `application/json`.
   */
  updateSongPositions$Response(params?: ServiceSongUpdateSongPositions$Params, context?: HttpContext): Observable<StrictHttpResponse<void>> {
    const obs = serviceSongUpdateSongPositions(this.http, this.rootUrl, params, context);
    return obs;
  }

  /**
   * Update the position of songs.
   *
   *
   *
   * This method provides access only to the response body.
   * To access the full response (for headers, for example), `updateSongPositions$Response()` instead.
   *
   * This method sends `application/json` and handles request body of type `application/json`.
   */
  updateSongPositions(params?: ServiceSongUpdateSongPositions$Params, context?: HttpContext): Observable<void> {
    const resp = this.updateSongPositions$Response(params, context);
    return resp.pipe(takeUntil(this.cancelPendingRequests$), 
      map((r: StrictHttpResponse<void>): void => r.body)
    );
  }

  /** Path part for operation `get()` */
  static readonly ServiceSongGetPath = '/song/{id}';

  /**
   * Returns an Song using an id.
   *
   *
   *
   * This method provides access to the full `HttpResponse`, allowing access to response headers.
   * To access only the response body, use `get()` instead.
   *
   * This method doesn't expect any request body.
   */
  get$Response(params: ServiceSongGet$Params, context?: HttpContext): Observable<StrictHttpResponse<Song>> {
    const obs = serviceSongGet(this.http, this.rootUrl, params, context);
    return obs;
  }

  /**
   * Returns an Song using an id.
   *
   *
   *
   * This method provides access only to the response body.
   * To access the full response (for headers, for example), `get$Response()` instead.
   *
   * This method doesn't expect any request body.
   */
  get(params: ServiceSongGet$Params, context?: HttpContext): Observable<Song> {
    const resp = this.get$Response(params, context);
    return resp.pipe(takeUntil(this.cancelPendingRequests$), 
      map((r: StrictHttpResponse<Song>): Song => r.body)
    );
  }

  /** Path part for operation `update()` */
  static readonly ServiceSongUpdatePath = '/song/{id}';

  /**
   * Updates an Song using an id.
   *
   *
   *
   * This method provides access to the full `HttpResponse`, allowing access to response headers.
   * To access only the response body, use `update()` instead.
   *
   * This method sends `application/json` and handles request body of type `application/json`.
   */
  update$Response(params: ServiceSongUpdate$Params, context?: HttpContext): Observable<StrictHttpResponse<void>> {
    const obs = serviceSongUpdate(this.http, this.rootUrl, params, context);
    return obs;
  }

  /**
   * Updates an Song using an id.
   *
   *
   *
   * This method provides access only to the response body.
   * To access the full response (for headers, for example), `update$Response()` instead.
   *
   * This method sends `application/json` and handles request body of type `application/json`.
   */
  update(params: ServiceSongUpdate$Params, context?: HttpContext): Observable<void> {
    const resp = this.update$Response(params, context);
    return resp.pipe(takeUntil(this.cancelPendingRequests$), 
      map((r: StrictHttpResponse<void>): void => r.body)
    );
  }

  /** Path part for operation `erase()` */
  static readonly ServiceSongErasePath = '/song/{id}';

  /**
   * Deletes an Song using an id.
   *
   *
   *
   * This method provides access to the full `HttpResponse`, allowing access to response headers.
   * To access only the response body, use `erase()` instead.
   *
   * This method doesn't expect any request body.
   */
  erase$Response(params: ServiceSongErase$Params, context?: HttpContext): Observable<StrictHttpResponse<void>> {
    const obs = serviceSongErase(this.http, this.rootUrl, params, context);
    return obs;
  }

  /**
   * Deletes an Song using an id.
   *
   *
   *
   * This method provides access only to the response body.
   * To access the full response (for headers, for example), `erase$Response()` instead.
   *
   * This method doesn't expect any request body.
   */
  erase(params: ServiceSongErase$Params, context?: HttpContext): Observable<void> {
    const resp = this.erase$Response(params, context);
    return resp.pipe(takeUntil(this.cancelPendingRequests$), 
      map((r: StrictHttpResponse<void>): void => r.body)
    );
  }

  /** Path part for operation `getCloudStatus()` */
  static readonly ServiceSongGetCloudStatusPath = '/song/{id}/getcloudstatus';

  /**
   * Returns the cloud status of this song.
   *
   *
   *
   * This method provides access to the full `HttpResponse`, allowing access to response headers.
   * To access only the response body, use `getCloudStatus()` instead.
   *
   * This method doesn't expect any request body.
   */
  getCloudStatus$Response(params: ServiceSongGetCloudStatus$Params, context?: HttpContext): Observable<StrictHttpResponse<CloudSearch>> {
    const obs = serviceSongGetCloudStatus(this.http, this.rootUrl, params, context);
    return obs;
  }

  /**
   * Returns the cloud status of this song.
   *
   *
   *
   * This method provides access only to the response body.
   * To access the full response (for headers, for example), `getCloudStatus$Response()` instead.
   *
   * This method doesn't expect any request body.
   */
  getCloudStatus(params: ServiceSongGetCloudStatus$Params, context?: HttpContext): Observable<CloudSearch> {
    const resp = this.getCloudStatus$Response(params, context);
    return resp.pipe(takeUntil(this.cancelPendingRequests$), 
      map((r: StrictHttpResponse<CloudSearch>): CloudSearch => r.body)
    );
  }



    getEntityName(): string {
        return 'Song';
    }
}