/* eslint-disable */
/* Code generated by ng-openapi-gen DO NOT EDIT. */

import { HttpClient, HttpContext, HttpResponse } from '@angular/common/http';
import { Observable } from 'rxjs';
import { filter, map } from 'rxjs/operators';
import { StrictHttpResponse } from '../../strict-http-response';
import { RequestBuilder } from '../../request-builder';

import { AlbumBookmark } from '../../models/album-bookmark';
import { Identifier } from '../../models/Identifier';
export type IdentifierLike = Identifier | string;



export interface ServiceAlbumBookmarkGet$Params {

/**
 * The identifier of a resource
 */
  id: IdentifierLike;
}

export function serviceAlbumBookmarkGet(http: HttpClient, rootUrl: string, params: ServiceAlbumBookmarkGet$Params, context?: HttpContext): Observable<StrictHttpResponse<AlbumBookmark>> {
  const rb = new RequestBuilder(rootUrl, serviceAlbumBookmarkGet.PATH, 'get');
  if (params) {
    rb.path('id', String(params.id), {});
  }

  return http.request(
    rb.build({ responseType: 'json', accept: 'application/json', context })
  ).pipe(
    filter((r: any): r is HttpResponse<any> => r instanceof HttpResponse),
    map((r: HttpResponse<any>) => {
      return r as StrictHttpResponse<AlbumBookmark>;
    })
  );
}

serviceAlbumBookmarkGet.PATH = '/albumbookmark/{id}';

export { serviceAlbumBookmarkGet as get };
