/* eslint-disable */
/* Code generated by ng-openapi-gen DO NOT EDIT. */

import { HttpClient, HttpContext, HttpResponse } from '@angular/common/http';
import { Observable } from 'rxjs';
import { filter, map } from 'rxjs/operators';
import { StrictHttpResponse } from '../../strict-http-response';
import { RequestBuilder } from '../../request-builder';

import { Album } from '../../models/album';
import { Identifier } from '../../models/Identifier';
export type IdentifierLike = Identifier | string;



export interface ServiceAlbumGet$Params {

/**
 * The identifier of a resource
 */
  id: IdentifierLike;
}

export function serviceAlbumGet(http: HttpClient, rootUrl: string, params: ServiceAlbumGet$Params, context?: HttpContext): Observable<StrictHttpResponse<Album>> {
  const rb = new RequestBuilder(rootUrl, serviceAlbumGet.PATH, 'get');
  if (params) {
    rb.path('id', String(params.id), {});
  }

  return http.request(
    rb.build({ responseType: 'json', accept: 'application/json', context })
  ).pipe(
    filter((r: any): r is HttpResponse<any> => r instanceof HttpResponse),
    map((r: HttpResponse<any>) => {
      return r as StrictHttpResponse<Album>;
    })
  );
}

serviceAlbumGet.PATH = '/album/{id}';

export { serviceAlbumGet as get };
