# coding: utf-8

"""
    MyMusik API

    MyMusik is an music player platform for offline music.  The API is object based. Each object has base methods: Insert, Update, Get, Get-Page, Erase.  Insert and Update always require a complete object. Every property must be present. Empty values are allowed.  For Insert the id is empty. The generated id is returned in the Location header.  Get requires only the object id. Get-Page uses a separate Filter object with Condition objects.  There are predefined filters available for example <ObjectName>By<PropertyName> lets you filter pages by any property. Additional actions are defined per path and may vary. Some enum values are placeholders for future features.  The API is protected using access tokens. By default remote access is disabled. You can enable it in settings but do so carefully.

    The version of the OpenAPI document: 1.0.0
    Contact: info@shaggai.email
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


from __future__ import annotations
import pprint
import re  # noqa: F401
import json

from datetime import datetime
from pydantic import BaseModel, ConfigDict, Field, StrictInt, StrictStr, field_validator
from typing import Any, ClassVar, Dict, List, Optional
from typing_extensions import Annotated
from typing import Optional, Set
from typing_extensions import Self

class AiMusicVoiceCommand(BaseModel):
    """
    AiMusicVoiceCommand
    """ # noqa: E501
    api_description_json: Optional[StrictStr] = Field(default=None, alias="apiDescriptionJson")
    created: Optional[datetime] = None
    current_screen_reference: Optional[Annotated[str, Field(strict=True)]] = Field(default=None, alias="currentScreenReference")
    current_screen_type: Optional[StrictStr] = Field(default=None, alias="currentScreenType")
    error_message: Optional[StrictStr] = Field(default=None, alias="errorMessage")
    execution_result: Optional[StrictStr] = Field(default=None, alias="executionResult")
    frontend_info_json: Optional[StrictStr] = Field(default=None, alias="frontendInfoJson")
    generated_script: Optional[StrictStr] = Field(default=None, alias="generatedScript")
    id: Annotated[str, Field(strict=True)]
    retry_counter: Optional[StrictInt] = Field(default=None, alias="retryCounter")
    status: Optional[StrictStr] = None
    transcript: Optional[StrictStr] = None
    updated: Optional[datetime] = None
    user_instruction: Optional[StrictStr] = Field(default=None, alias="userInstruction")
    __properties: ClassVar[List[str]] = ["apiDescriptionJson", "created", "currentScreenReference", "currentScreenType", "errorMessage", "executionResult", "frontendInfoJson", "generatedScript", "id", "retryCounter", "status", "transcript", "updated", "userInstruction"]

    @field_validator('current_screen_reference')
    def current_screen_reference_validate_regular_expression(cls, value):
        """Validates the regular expression"""
        if value is None:
            return value

        if not re.match(r"^[A-Fa-f0-9]{30}$|^(?![\s\S])$", value):
            raise ValueError(r"must validate the regular expression /^[A-Fa-f0-9]{30}$|^(?![\s\S])$/")
        return value

    @field_validator('current_screen_type')
    def current_screen_type_validate_enum(cls, value):
        """Validates the enum"""
        if value is None:
            return value

        if value not in set(['UNKNOWN', 'PLAYER', 'QUEUE', 'SEARCH', 'SONG', 'ALBUM', 'PLAYLIST', 'ARTIST']):
            raise ValueError("must be one of enum values ('UNKNOWN', 'PLAYER', 'QUEUE', 'SEARCH', 'SONG', 'ALBUM', 'PLAYLIST', 'ARTIST')")
        return value

    @field_validator('id')
    def id_validate_regular_expression(cls, value):
        """Validates the regular expression"""
        if not re.match(r"^[A-Fa-f0-9]{30}$|^(?![\s\S])$", value):
            raise ValueError(r"must validate the regular expression /^[A-Fa-f0-9]{30}$|^(?![\s\S])$/")
        return value

    @field_validator('status')
    def status_validate_enum(cls, value):
        """Validates the enum"""
        if value is None:
            return value

        if value not in set(['CREATED', 'RECORDING', 'TRANSCRIBING', 'GENERATING_SCRIPT', 'WAITING_FOR_FRONTEND_EXECUTION', 'FRONTEND_EXECUTING', 'SUCCESS', 'FAILED', 'CANCELLED']):
            raise ValueError("must be one of enum values ('CREATED', 'RECORDING', 'TRANSCRIBING', 'GENERATING_SCRIPT', 'WAITING_FOR_FRONTEND_EXECUTION', 'FRONTEND_EXECUTING', 'SUCCESS', 'FAILED', 'CANCELLED')")
        return value

    model_config = ConfigDict(
        populate_by_name=True,
        validate_assignment=True,
        protected_namespaces=(),
    )


    def to_str(self) -> str:
        """Returns the string representation of the model using alias"""
        return pprint.pformat(self.model_dump(by_alias=True))

    def to_json(self) -> str:
        """Returns the JSON representation of the model using alias"""
        # TODO: pydantic v2: use .model_dump_json(by_alias=True, exclude_unset=True) instead
        return json.dumps(self.to_dict())

    @classmethod
    def from_json(cls, json_str: str) -> Optional[Self]:
        """Create an instance of AiMusicVoiceCommand from a JSON string"""
        return cls.from_dict(json.loads(json_str))

    def to_dict(self) -> Dict[str, Any]:
        """Return the dictionary representation of the model using alias.

        This has the following differences from calling pydantic's
        `self.model_dump(by_alias=True)`:

        * `None` is only added to the output dict for nullable fields that
          were set at model initialization. Other fields with value `None`
          are ignored.
        """
        excluded_fields: Set[str] = set([
        ])

        _dict = self.model_dump(
            by_alias=True,
            exclude=excluded_fields,
            exclude_none=True,
        )
        return _dict

    @classmethod
    def from_dict(cls, obj: Optional[Dict[str, Any]]) -> Optional[Self]:
        """Create an instance of AiMusicVoiceCommand from a dict"""
        if obj is None:
            return None

        if not isinstance(obj, dict):
            return cls.model_validate(obj)

        _obj = cls.model_validate({
            "apiDescriptionJson": obj.get("apiDescriptionJson"),
            "created": obj.get("created"),
            "currentScreenReference": obj.get("currentScreenReference"),
            "currentScreenType": obj.get("currentScreenType"),
            "errorMessage": obj.get("errorMessage"),
            "executionResult": obj.get("executionResult"),
            "frontendInfoJson": obj.get("frontendInfoJson"),
            "generatedScript": obj.get("generatedScript"),
            "id": obj.get("id"),
            "retryCounter": obj.get("retryCounter"),
            "status": obj.get("status"),
            "transcript": obj.get("transcript"),
            "updated": obj.get("updated"),
            "userInstruction": obj.get("userInstruction")
        })
        return _obj


