# coding: utf-8

"""
    MyMusik API

    MyMusik is an music player platform for offline music.  The API is object based. Each object has base methods: Insert, Update, Get, Get-Page, Erase.  Insert and Update always require a complete object. Every property must be present. Empty values are allowed.  For Insert the id is empty. The generated id is returned in the Location header.  Get requires only the object id. Get-Page uses a separate Filter object with Condition objects.  There are predefined filters available for example <ObjectName>By<PropertyName> lets you filter pages by any property. Additional actions are defined per path and may vary. Some enum values are placeholders for future features.  The API is protected using access tokens. By default remote access is disabled. You can enable it in settings but do so carefully.

    The version of the OpenAPI document: 1.0.0
    Contact: info@shaggai.email
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


from __future__ import annotations
import pprint
import re  # noqa: F401
import json

from datetime import datetime
from pydantic import BaseModel, ConfigDict, Field, StrictBool, StrictInt, StrictStr, field_validator
from typing import Any, ClassVar, Dict, List, Optional
from typing_extensions import Annotated
from typing import Optional, Set
from typing_extensions import Self

class Device(BaseModel):
    """
    Device
    """ # noqa: E501
    api_version: Optional[StrictStr] = Field(default=None, alias="apiVersion")
    app_install_date: Optional[datetime] = Field(default=None, alias="appInstallDate")
    app_version: Optional[StrictStr] = Field(default=None, alias="appVersion")
    cloud_last_server_revision: Optional[StrictInt] = Field(default=None, alias="cloudLastServerRevision")
    has_dark_mode_on: Optional[StrictBool] = Field(default=None, alias="hasDarkModeOn")
    hash: Optional[Annotated[str, Field(strict=True)]] = None
    id: Annotated[str, Field(strict=True)]
    ip: Optional[StrictStr] = None
    is_initialized: Optional[StrictBool] = Field(default=None, alias="isInitialized")
    is_mobile: Optional[StrictBool] = Field(default=None, alias="isMobile")
    is_trusted: Optional[StrictBool] = Field(default=None, alias="isTrusted")
    last_app_update: Optional[datetime] = Field(default=None, alias="lastAppUpdate")
    last_login: Optional[datetime] = Field(default=None, alias="lastLogin")
    last_online_check: Optional[datetime] = Field(default=None, alias="lastOnlineCheck")
    location: Optional[StrictStr] = None
    logged_in: Optional[StrictBool] = Field(default=None, alias="loggedIn")
    max_storage: Optional[StrictInt] = Field(default=None, alias="maxStorage")
    operating_system: Optional[StrictStr] = Field(default=None, alias="operatingSystem")
    os_version: Optional[StrictStr] = Field(default=None, alias="osVersion")
    owner: Optional[StrictStr] = None
    processor: Optional[StrictStr] = None
    storage_usage: Optional[StrictInt] = Field(default=None, alias="storageUsage")
    __properties: ClassVar[List[str]] = ["apiVersion", "appInstallDate", "appVersion", "cloudLastServerRevision", "hasDarkModeOn", "hash", "id", "ip", "isInitialized", "isMobile", "isTrusted", "lastAppUpdate", "lastLogin", "lastOnlineCheck", "location", "loggedIn", "maxStorage", "operatingSystem", "osVersion", "owner", "processor", "storageUsage"]

    @field_validator('hash')
    def hash_validate_regular_expression(cls, value):
        """Validates the regular expression"""
        if value is None:
            return value

        if not re.match(r"^[A-Fa-f0-9]{64}$", value):
            raise ValueError(r"must validate the regular expression /^[A-Fa-f0-9]{64}$/")
        return value

    @field_validator('id')
    def id_validate_regular_expression(cls, value):
        """Validates the regular expression"""
        if not re.match(r"^[A-Fa-f0-9]{30}$|^(?![\s\S])$", value):
            raise ValueError(r"must validate the regular expression /^[A-Fa-f0-9]{30}$|^(?![\s\S])$/")
        return value

    model_config = ConfigDict(
        populate_by_name=True,
        validate_assignment=True,
        protected_namespaces=(),
    )


    def to_str(self) -> str:
        """Returns the string representation of the model using alias"""
        return pprint.pformat(self.model_dump(by_alias=True))

    def to_json(self) -> str:
        """Returns the JSON representation of the model using alias"""
        # TODO: pydantic v2: use .model_dump_json(by_alias=True, exclude_unset=True) instead
        return json.dumps(self.to_dict())

    @classmethod
    def from_json(cls, json_str: str) -> Optional[Self]:
        """Create an instance of Device from a JSON string"""
        return cls.from_dict(json.loads(json_str))

    def to_dict(self) -> Dict[str, Any]:
        """Return the dictionary representation of the model using alias.

        This has the following differences from calling pydantic's
        `self.model_dump(by_alias=True)`:

        * `None` is only added to the output dict for nullable fields that
          were set at model initialization. Other fields with value `None`
          are ignored.
        """
        excluded_fields: Set[str] = set([
        ])

        _dict = self.model_dump(
            by_alias=True,
            exclude=excluded_fields,
            exclude_none=True,
        )
        return _dict

    @classmethod
    def from_dict(cls, obj: Optional[Dict[str, Any]]) -> Optional[Self]:
        """Create an instance of Device from a dict"""
        if obj is None:
            return None

        if not isinstance(obj, dict):
            return cls.model_validate(obj)

        _obj = cls.model_validate({
            "apiVersion": obj.get("apiVersion"),
            "appInstallDate": obj.get("appInstallDate"),
            "appVersion": obj.get("appVersion"),
            "cloudLastServerRevision": obj.get("cloudLastServerRevision"),
            "hasDarkModeOn": obj.get("hasDarkModeOn"),
            "hash": obj.get("hash"),
            "id": obj.get("id"),
            "ip": obj.get("ip"),
            "isInitialized": obj.get("isInitialized"),
            "isMobile": obj.get("isMobile"),
            "isTrusted": obj.get("isTrusted"),
            "lastAppUpdate": obj.get("lastAppUpdate"),
            "lastLogin": obj.get("lastLogin"),
            "lastOnlineCheck": obj.get("lastOnlineCheck"),
            "location": obj.get("location"),
            "loggedIn": obj.get("loggedIn"),
            "maxStorage": obj.get("maxStorage"),
            "operatingSystem": obj.get("operatingSystem"),
            "osVersion": obj.get("osVersion"),
            "owner": obj.get("owner"),
            "processor": obj.get("processor"),
            "storageUsage": obj.get("storageUsage")
        })
        return _obj


