# coding: utf-8

"""
    MyMusik API

    MyMusik is an music player platform for offline music.  The API is object based. Each object has base methods: Insert, Update, Get, Get-Page, Erase.  Insert and Update always require a complete object. Every property must be present. Empty values are allowed.  For Insert the id is empty. The generated id is returned in the Location header.  Get requires only the object id. Get-Page uses a separate Filter object with Condition objects.  There are predefined filters available for example <ObjectName>By<PropertyName> lets you filter pages by any property. Additional actions are defined per path and may vary. Some enum values are placeholders for future features.  The API is protected using access tokens. By default remote access is disabled. You can enable it in settings but do so carefully.

    The version of the OpenAPI document: 1.0.0
    Contact: info@shaggai.email
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


from __future__ import annotations
import pprint
import re  # noqa: F401
import json

from datetime import datetime
from pydantic import BaseModel, ConfigDict, Field, StrictBool, StrictInt, StrictStr, field_validator
from typing import Any, ClassVar, Dict, List, Optional
from typing_extensions import Annotated
from typing import Optional, Set
from typing_extensions import Self

class Report(BaseModel):
    """
    Report
    """ # noqa: E501
    action: Optional[StrictStr] = None
    additional_text: Optional[Annotated[str, Field(strict=True, max_length=5000)]] = Field(default=None, alias="additionalText")
    asset_id: Optional[Annotated[str, Field(strict=True)]] = Field(default=None, alias="assetId")
    asset_parent_id: Optional[Annotated[str, Field(strict=True)]] = Field(default=None, alias="assetParentId")
    blamed_user: Optional[StrictStr] = Field(default=None, alias="blamedUser")
    category: Optional[StrictStr] = None
    created: Optional[datetime] = None
    evidence: Optional[StrictStr] = None
    evidence_hash: Optional[Annotated[str, Field(strict=True)]] = Field(default=None, alias="evidenceHash")
    id: Annotated[str, Field(strict=True)]
    is_admin_report: Optional[StrictBool] = Field(default=None, alias="isAdminReport")
    is_resolved: Optional[StrictBool] = Field(default=None, alias="isResolved")
    modified: Optional[datetime] = None
    owner: Optional[StrictStr] = None
    pre_proccessed: Optional[StrictBool] = Field(default=None, alias="preProccessed")
    punishment: Optional[StrictStr] = None
    reason: Optional[StrictStr] = None
    report_for: Optional[StrictStr] = Field(default=None, alias="reportFor")
    resolved_at: Optional[datetime] = Field(default=None, alias="resolvedAt")
    resolved_comment: Optional[StrictStr] = Field(default=None, alias="resolvedComment")
    severity: Optional[StrictInt] = None
    sig: Optional[StrictStr] = None
    stamp: Optional[Annotated[str, Field(strict=True)]] = None
    __properties: ClassVar[List[str]] = ["action", "additionalText", "assetId", "assetParentId", "blamedUser", "category", "created", "evidence", "evidenceHash", "id", "isAdminReport", "isResolved", "modified", "owner", "preProccessed", "punishment", "reason", "reportFor", "resolvedAt", "resolvedComment", "severity", "sig", "stamp"]

    @field_validator('action')
    def action_validate_enum(cls, value):
        """Validates the enum"""
        if value is None:
            return value

        if value not in set(['NoAction', 'Hide', 'Show', 'Erase', 'RestrictAccess', 'ReturnAccess', 'BanOwner', 'UnbanOwner', 'DeepBanOwner', 'DeepUnbanOwner', 'OtherAction']):
            raise ValueError("must be one of enum values ('NoAction', 'Hide', 'Show', 'Erase', 'RestrictAccess', 'ReturnAccess', 'BanOwner', 'UnbanOwner', 'DeepBanOwner', 'DeepUnbanOwner', 'OtherAction')")
        return value

    @field_validator('asset_id')
    def asset_id_validate_regular_expression(cls, value):
        """Validates the regular expression"""
        if value is None:
            return value

        if not re.match(r"^[A-Fa-f0-9]{30}$|^(?![\s\S])$", value):
            raise ValueError(r"must validate the regular expression /^[A-Fa-f0-9]{30}$|^(?![\s\S])$/")
        return value

    @field_validator('asset_parent_id')
    def asset_parent_id_validate_regular_expression(cls, value):
        """Validates the regular expression"""
        if value is None:
            return value

        if not re.match(r"^[A-Fa-f0-9]{30}$|^(?![\s\S])$", value):
            raise ValueError(r"must validate the regular expression /^[A-Fa-f0-9]{30}$|^(?![\s\S])$/")
        return value

    @field_validator('evidence_hash')
    def evidence_hash_validate_regular_expression(cls, value):
        """Validates the regular expression"""
        if value is None:
            return value

        if not re.match(r"^[A-Fa-f0-9]{64}$", value):
            raise ValueError(r"must validate the regular expression /^[A-Fa-f0-9]{64}$/")
        return value

    @field_validator('id')
    def id_validate_regular_expression(cls, value):
        """Validates the regular expression"""
        if not re.match(r"^[A-Fa-f0-9]{30}$|^(?![\s\S])$", value):
            raise ValueError(r"must validate the regular expression /^[A-Fa-f0-9]{30}$|^(?![\s\S])$/")
        return value

    @field_validator('punishment')
    def punishment_validate_enum(cls, value):
        """Validates the enum"""
        if value is None:
            return value

        if value not in set(['None', 'Warning', 'TemporaryRestriction', 'PermanentBan', 'Takedown', 'OtherPunishment']):
            raise ValueError("must be one of enum values ('None', 'Warning', 'TemporaryRestriction', 'PermanentBan', 'Takedown', 'OtherPunishment')")
        return value

    @field_validator('reason')
    def reason_validate_enum(cls, value):
        """Validates the enum"""
        if value is None:
            return value

        if value not in set(['InappropriateContent', 'CopyrightViolation', 'Spam', 'Fraud', 'PrivacyViolation', 'SexualContent', 'ViolentOrRepulsiveContent', 'HatefulOrAbusiveContent', 'HarassmentOrBullying', 'HarmfulOrDangerousActs', 'SuicideSelfHarmOrEatingDisorders', 'Misinformation', 'ChildAbuse', 'PromotesTerrorism', 'SpamOrMisleading', 'LegalIssue', 'Advertisement', 'Other', 'AiGeneratedContent', 'AiHallucination', 'AiPolicyEvasion', 'AiPromptInjection', 'AiUnsafeInstructions', 'AiSensitiveDataExposure']):
            raise ValueError("must be one of enum values ('InappropriateContent', 'CopyrightViolation', 'Spam', 'Fraud', 'PrivacyViolation', 'SexualContent', 'ViolentOrRepulsiveContent', 'HatefulOrAbusiveContent', 'HarassmentOrBullying', 'HarmfulOrDangerousActs', 'SuicideSelfHarmOrEatingDisorders', 'Misinformation', 'ChildAbuse', 'PromotesTerrorism', 'SpamOrMisleading', 'LegalIssue', 'Advertisement', 'Other', 'AiGeneratedContent', 'AiHallucination', 'AiPolicyEvasion', 'AiPromptInjection', 'AiUnsafeInstructions', 'AiSensitiveDataExposure')")
        return value

    @field_validator('report_for')
    def report_for_validate_enum(cls, value):
        """Validates the enum"""
        if value is None:
            return value

        if value not in set(['NotDefined', 'Comment', 'SharedAsset', 'Tag']):
            raise ValueError("must be one of enum values ('NotDefined', 'Comment', 'SharedAsset', 'Tag')")
        return value

    @field_validator('stamp')
    def stamp_validate_regular_expression(cls, value):
        """Validates the regular expression"""
        if value is None:
            return value

        if not re.match(r"^[A-Fa-f0-9]{30}$|^(?![\s\S])$", value):
            raise ValueError(r"must validate the regular expression /^[A-Fa-f0-9]{30}$|^(?![\s\S])$/")
        return value

    model_config = ConfigDict(
        populate_by_name=True,
        validate_assignment=True,
        protected_namespaces=(),
    )


    def to_str(self) -> str:
        """Returns the string representation of the model using alias"""
        return pprint.pformat(self.model_dump(by_alias=True))

    def to_json(self) -> str:
        """Returns the JSON representation of the model using alias"""
        # TODO: pydantic v2: use .model_dump_json(by_alias=True, exclude_unset=True) instead
        return json.dumps(self.to_dict())

    @classmethod
    def from_json(cls, json_str: str) -> Optional[Self]:
        """Create an instance of Report from a JSON string"""
        return cls.from_dict(json.loads(json_str))

    def to_dict(self) -> Dict[str, Any]:
        """Return the dictionary representation of the model using alias.

        This has the following differences from calling pydantic's
        `self.model_dump(by_alias=True)`:

        * `None` is only added to the output dict for nullable fields that
          were set at model initialization. Other fields with value `None`
          are ignored.
        """
        excluded_fields: Set[str] = set([
        ])

        _dict = self.model_dump(
            by_alias=True,
            exclude=excluded_fields,
            exclude_none=True,
        )
        return _dict

    @classmethod
    def from_dict(cls, obj: Optional[Dict[str, Any]]) -> Optional[Self]:
        """Create an instance of Report from a dict"""
        if obj is None:
            return None

        if not isinstance(obj, dict):
            return cls.model_validate(obj)

        _obj = cls.model_validate({
            "action": obj.get("action"),
            "additionalText": obj.get("additionalText"),
            "assetId": obj.get("assetId"),
            "assetParentId": obj.get("assetParentId"),
            "blamedUser": obj.get("blamedUser"),
            "category": obj.get("category"),
            "created": obj.get("created"),
            "evidence": obj.get("evidence"),
            "evidenceHash": obj.get("evidenceHash"),
            "id": obj.get("id"),
            "isAdminReport": obj.get("isAdminReport"),
            "isResolved": obj.get("isResolved"),
            "modified": obj.get("modified"),
            "owner": obj.get("owner"),
            "preProccessed": obj.get("preProccessed"),
            "punishment": obj.get("punishment"),
            "reason": obj.get("reason"),
            "reportFor": obj.get("reportFor"),
            "resolvedAt": obj.get("resolvedAt"),
            "resolvedComment": obj.get("resolvedComment"),
            "severity": obj.get("severity"),
            "sig": obj.get("sig"),
            "stamp": obj.get("stamp")
        })
        return _obj


