# coding: utf-8

"""
    MyMusik API

    MyMusik is an music player platform for offline music.  The API is object based. Each object has base methods: Insert, Update, Get, Get-Page, Erase.  Insert and Update always require a complete object. Every property must be present. Empty values are allowed.  For Insert the id is empty. The generated id is returned in the Location header.  Get requires only the object id. Get-Page uses a separate Filter object with Condition objects.  There are predefined filters available for example <ObjectName>By<PropertyName> lets you filter pages by any property. Additional actions are defined per path and may vary. Some enum values are placeholders for future features.  The API is protected using access tokens. By default remote access is disabled. You can enable it in settings but do so carefully.

    The version of the OpenAPI document: 1.0.0
    Contact: info@shaggai.email
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


from __future__ import annotations
import pprint
import re  # noqa: F401
import json

from datetime import datetime
from pydantic import BaseModel, ConfigDict, Field, StrictBool, StrictStr, field_validator
from typing import Any, ClassVar, Dict, List, Optional
from typing_extensions import Annotated
from mymusik_client.models.album import Album
from mymusik_client.models.song import Song
from typing import Optional, Set
from typing_extensions import Self

class SongIdentifier(BaseModel):
    """
    SongIdentifier
    """ # noqa: E501
    album_suggestions: Optional[List[Album]] = Field(default=None, alias="albumSuggestions")
    created: Optional[datetime] = None
    finished: Optional[datetime] = None
    id: Annotated[str, Field(strict=True)]
    incomplete: Song
    should_check_online: Optional[StrictBool] = Field(default=None, alias="shouldCheckOnline")
    song_suggestion: Optional[Song] = Field(default=None, alias="songSuggestion")
    status: Optional[StrictStr] = None
    __properties: ClassVar[List[str]] = ["albumSuggestions", "created", "finished", "id", "incomplete", "shouldCheckOnline", "songSuggestion", "status"]

    @field_validator('id')
    def id_validate_regular_expression(cls, value):
        """Validates the regular expression"""
        if not re.match(r"^[A-Fa-f0-9]{30}$|^(?![\s\S])$", value):
            raise ValueError(r"must validate the regular expression /^[A-Fa-f0-9]{30}$|^(?![\s\S])$/")
        return value

    @field_validator('status')
    def status_validate_enum(cls, value):
        """Validates the enum"""
        if value is None:
            return value

        if value not in set(['NOT_STARTED', 'IN_PROGRESS', 'FILE_ANALIZED', 'CANCELED', 'FAILED', 'SUCCESS']):
            raise ValueError("must be one of enum values ('NOT_STARTED', 'IN_PROGRESS', 'FILE_ANALIZED', 'CANCELED', 'FAILED', 'SUCCESS')")
        return value

    model_config = ConfigDict(
        populate_by_name=True,
        validate_assignment=True,
        protected_namespaces=(),
    )


    def to_str(self) -> str:
        """Returns the string representation of the model using alias"""
        return pprint.pformat(self.model_dump(by_alias=True))

    def to_json(self) -> str:
        """Returns the JSON representation of the model using alias"""
        # TODO: pydantic v2: use .model_dump_json(by_alias=True, exclude_unset=True) instead
        return json.dumps(self.to_dict())

    @classmethod
    def from_json(cls, json_str: str) -> Optional[Self]:
        """Create an instance of SongIdentifier from a JSON string"""
        return cls.from_dict(json.loads(json_str))

    def to_dict(self) -> Dict[str, Any]:
        """Return the dictionary representation of the model using alias.

        This has the following differences from calling pydantic's
        `self.model_dump(by_alias=True)`:

        * `None` is only added to the output dict for nullable fields that
          were set at model initialization. Other fields with value `None`
          are ignored.
        """
        excluded_fields: Set[str] = set([
        ])

        _dict = self.model_dump(
            by_alias=True,
            exclude=excluded_fields,
            exclude_none=True,
        )
        # override the default output from pydantic by calling `to_dict()` of each item in album_suggestions (list)
        _items = []
        if self.album_suggestions:
            for _item_album_suggestions in self.album_suggestions:
                if _item_album_suggestions:
                    _items.append(_item_album_suggestions.to_dict())
            _dict['albumSuggestions'] = _items
        # override the default output from pydantic by calling `to_dict()` of incomplete
        if self.incomplete:
            _dict['incomplete'] = self.incomplete.to_dict()
        # override the default output from pydantic by calling `to_dict()` of song_suggestion
        if self.song_suggestion:
            _dict['songSuggestion'] = self.song_suggestion.to_dict()
        return _dict

    @classmethod
    def from_dict(cls, obj: Optional[Dict[str, Any]]) -> Optional[Self]:
        """Create an instance of SongIdentifier from a dict"""
        if obj is None:
            return None

        if not isinstance(obj, dict):
            return cls.model_validate(obj)

        _obj = cls.model_validate({
            "albumSuggestions": [Album.from_dict(_item) for _item in obj["albumSuggestions"]] if obj.get("albumSuggestions") is not None else None,
            "created": obj.get("created"),
            "finished": obj.get("finished"),
            "id": obj.get("id"),
            "incomplete": Song.from_dict(obj["incomplete"]) if obj.get("incomplete") is not None else None,
            "shouldCheckOnline": obj.get("shouldCheckOnline"),
            "songSuggestion": Song.from_dict(obj["songSuggestion"]) if obj.get("songSuggestion") is not None else None,
            "status": obj.get("status")
        })
        return _obj


