# coding: utf-8

"""
    MyMusik API

    MyMusik is an music player platform for offline music.  The API is object based. Each object has base methods: Insert, Update, Get, Get-Page, Erase.  Insert and Update always require a complete object. Every property must be present. Empty values are allowed.  For Insert the id is empty. The generated id is returned in the Location header.  Get requires only the object id. Get-Page uses a separate Filter object with Condition objects.  There are predefined filters available for example <ObjectName>By<PropertyName> lets you filter pages by any property. Additional actions are defined per path and may vary. Some enum values are placeholders for future features.  The API is protected using access tokens. By default remote access is disabled. You can enable it in settings but do so carefully.

    The version of the OpenAPI document: 1.0.0
    Contact: info@shaggai.email
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


from __future__ import annotations
import pprint
import re  # noqa: F401
import json

from datetime import datetime
from pydantic import BaseModel, ConfigDict, Field, StrictBool, StrictInt, StrictStr, field_validator
from typing import Any, ClassVar, Dict, List, Optional
from typing_extensions import Annotated
from mymusik_client.models.artist import Artist
from mymusik_client.models.audio_file import AudioFile
from mymusik_client.models.image_file import ImageFile
from mymusik_client.models.tag import Tag
from typing import Optional, Set
from typing_extensions import Self

class Song(BaseModel):
    """
    Song
    """ # noqa: E501
    class_type: StrictStr = Field(alias="classType")
    couldnt_find_music_id: Optional[StrictBool] = Field(default=None, alias="couldntFindMusicId")
    created: Optional[datetime] = None
    id: Annotated[str, Field(strict=True)]
    image: ImageFile
    modified: Optional[datetime] = None
    name: StrictStr
    public_music_id: Optional[StrictStr] = Field(default=None, alias="publicMusicId")
    should_fetch_cover: Optional[StrictBool] = Field(default=None, alias="shouldFetchCover")
    tags: List[Tag]
    visible: StrictBool
    album_id: StrictStr = Field(alias="albumId")
    album_name: StrictStr = Field(alias="albumName")
    artists: Optional[List[Artist]] = None
    file: Optional[AudioFile] = None
    position: StrictInt
    __properties: ClassVar[List[str]] = ["classType", "couldntFindMusicId", "created", "id", "image", "modified", "name", "publicMusicId", "shouldFetchCover", "tags", "visible", "albumId", "albumName", "artists", "file", "position"]

    @field_validator('class_type')
    def class_type_validate_enum(cls, value):
        """Validates the enum"""
        if value not in set(['Song', 'Album', 'Artist', 'Playlist']):
            raise ValueError("must be one of enum values ('Song', 'Album', 'Artist', 'Playlist')")
        return value

    @field_validator('id')
    def id_validate_regular_expression(cls, value):
        """Validates the regular expression"""
        if not re.match(r"^[A-Fa-f0-9]{30}$|^(?![\s\S])$", value):
            raise ValueError(r"must validate the regular expression /^[A-Fa-f0-9]{30}$|^(?![\s\S])$/")
        return value

    model_config = ConfigDict(
        populate_by_name=True,
        validate_assignment=True,
        protected_namespaces=(),
    )


    def to_str(self) -> str:
        """Returns the string representation of the model using alias"""
        return pprint.pformat(self.model_dump(by_alias=True))

    def to_json(self) -> str:
        """Returns the JSON representation of the model using alias"""
        # TODO: pydantic v2: use .model_dump_json(by_alias=True, exclude_unset=True) instead
        return json.dumps(self.to_dict())

    @classmethod
    def from_json(cls, json_str: str) -> Optional[Self]:
        """Create an instance of Song from a JSON string"""
        return cls.from_dict(json.loads(json_str))

    def to_dict(self) -> Dict[str, Any]:
        """Return the dictionary representation of the model using alias.

        This has the following differences from calling pydantic's
        `self.model_dump(by_alias=True)`:

        * `None` is only added to the output dict for nullable fields that
          were set at model initialization. Other fields with value `None`
          are ignored.
        """
        excluded_fields: Set[str] = set([
        ])

        _dict = self.model_dump(
            by_alias=True,
            exclude=excluded_fields,
            exclude_none=True,
        )
        # override the default output from pydantic by calling `to_dict()` of image
        if self.image:
            _dict['image'] = self.image.to_dict()
        # override the default output from pydantic by calling `to_dict()` of each item in tags (list)
        _items = []
        if self.tags:
            for _item_tags in self.tags:
                if _item_tags:
                    _items.append(_item_tags.to_dict())
            _dict['tags'] = _items
        # override the default output from pydantic by calling `to_dict()` of each item in artists (list)
        _items = []
        if self.artists:
            for _item_artists in self.artists:
                if _item_artists:
                    _items.append(_item_artists.to_dict())
            _dict['artists'] = _items
        # override the default output from pydantic by calling `to_dict()` of file
        if self.file:
            _dict['file'] = self.file.to_dict()
        return _dict

    @classmethod
    def from_dict(cls, obj: Optional[Dict[str, Any]]) -> Optional[Self]:
        """Create an instance of Song from a dict"""
        if obj is None:
            return None

        if not isinstance(obj, dict):
            return cls.model_validate(obj)

        _obj = cls.model_validate({
            "classType": obj.get("classType"),
            "couldntFindMusicId": obj.get("couldntFindMusicId"),
            "created": obj.get("created"),
            "id": obj.get("id"),
            "image": ImageFile.from_dict(obj["image"]) if obj.get("image") is not None else None,
            "modified": obj.get("modified"),
            "name": obj.get("name"),
            "publicMusicId": obj.get("publicMusicId"),
            "shouldFetchCover": obj.get("shouldFetchCover"),
            "tags": [Tag.from_dict(_item) for _item in obj["tags"]] if obj.get("tags") is not None else None,
            "visible": obj.get("visible"),
            "albumId": obj.get("albumId"),
            "albumName": obj.get("albumName"),
            "artists": [Artist.from_dict(_item) for _item in obj["artists"]] if obj.get("artists") is not None else None,
            "file": AudioFile.from_dict(obj["file"]) if obj.get("file") is not None else None,
            "position": obj.get("position")
        })
        return _obj


