/* eslint-disable */
/* Code generated by ng-openapi-gen DO NOT EDIT. */

import { HttpClient, HttpContext, HttpResponse } from '@angular/common/http';
import { Observable } from 'rxjs';
import { filter, map } from 'rxjs/operators';
import { StrictHttpResponse } from '../../strict-http-response';
import { RequestBuilder } from '../../request-builder';

import { Token } from '../../models/token';
import { Identifier } from '../../models/Identifier';
export type IdentifierLike = Identifier | string;



export interface ServiceTokenAuthUrl$Params {

/**
 * The identifier of a resource
 */
  id: IdentifierLike;
}

export function serviceTokenAuthUrl(http: HttpClient, rootUrl: string, params: ServiceTokenAuthUrl$Params, context?: HttpContext): Observable<StrictHttpResponse<Token>> {
  const rb = new RequestBuilder(rootUrl, serviceTokenAuthUrl.PATH, 'get');
  if (params) {
    rb.path('id', String(params.id), {});
  }

  return http.request(
    rb.build({ responseType: 'json', accept: 'application/json', context })
  ).pipe(
    filter((r: any): r is HttpResponse<any> => r instanceof HttpResponse),
    map((r: HttpResponse<any>) => {
      return r as StrictHttpResponse<Token>;
    })
  );
}

serviceTokenAuthUrl.PATH = '/token/{id}/authurl';

export { serviceTokenAuthUrl as authUrl };
