/* eslint-disable */
/* Code generated by ng-openapi-gen DO NOT EDIT. */

import { HttpClient, HttpContext, HttpResponse } from '@angular/common/http';
import { Observable } from 'rxjs';
import { filter, map } from 'rxjs/operators';
import { StrictHttpResponse } from '../../strict-http-response';
import { RequestBuilder } from '../../request-builder';
import { Identifier } from '../../models/Identifier';
export type IdentifierLike = Identifier | string;




export interface ServiceAudioFileContent$Ogg$Params {

/**
 * The identifier of a resource
 */
  id: IdentifierLike;
  filename?: string;
  format?: 'ogg' | 'mp3' | 'flac' | 'wav';
}

export function serviceAudioFileContent$Ogg(http: HttpClient, rootUrl: string, params: ServiceAudioFileContent$Ogg$Params, context?: HttpContext): Observable<StrictHttpResponse<Blob>> {
  const rb = new RequestBuilder(rootUrl, serviceAudioFileContent$Ogg.PATH, 'get');
  if (params) {
    rb.path('id', String(params.id), {});
    rb.query('filename', params.filename, {});
    rb.query('format', params.format, {});
  }

  return http.request(
    rb.build({ responseType: 'blob', accept: 'audio/ogg', context })
  ).pipe(
    filter((r: any): r is HttpResponse<any> => r instanceof HttpResponse),
    map((r: HttpResponse<any>) => {
      return r as StrictHttpResponse<Blob>;
    })
  );
}

serviceAudioFileContent$Ogg.PATH = '/audiofile/{id}/content';

export { serviceAudioFileContent$Ogg as content$Ogg };
