/* eslint-disable */
/* Code generated by ng-openapi-gen DO NOT EDIT. */

import { HttpClient, HttpContext, HttpResponse } from '@angular/common/http';
import { Observable } from 'rxjs';
import { filter, map } from 'rxjs/operators';
import { StrictHttpResponse } from '../../strict-http-response';
import { RequestBuilder } from '../../request-builder';

import { AudioFile } from '../../models/audio-file';
import { Identifier } from '../../models/Identifier';
export type IdentifierLike = Identifier | string;



export interface ServiceAudioFileGet$Params {

/**
 * The identifier of a resource
 */
  id: IdentifierLike;
}

export function serviceAudioFileGet(http: HttpClient, rootUrl: string, params: ServiceAudioFileGet$Params, context?: HttpContext): Observable<StrictHttpResponse<AudioFile>> {
  const rb = new RequestBuilder(rootUrl, serviceAudioFileGet.PATH, 'get');
  if (params) {
    rb.path('id', String(params.id), {});
  }

  return http.request(
    rb.build({ responseType: 'json', accept: 'application/json', context })
  ).pipe(
    filter((r: any): r is HttpResponse<any> => r instanceof HttpResponse),
    map((r: HttpResponse<any>) => {
      return r as StrictHttpResponse<AudioFile>;
    })
  );
}

serviceAudioFileGet.PATH = '/audiofile/{id}';

export { serviceAudioFileGet as get };
