/* eslint-disable */
/* Code generated by ng-openapi-gen DO NOT EDIT. */

import { HttpClient, HttpContext, HttpResponse } from '@angular/common/http';
import { Observable } from 'rxjs';
import { filter, map } from 'rxjs/operators';
import { StrictHttpResponse } from '../../strict-http-response';
import { RequestBuilder } from '../../request-builder';

import { QueueItemList } from '../../models/queue-item-list';
import { Identifier } from '../../models/Identifier';
export type IdentifierLike = Identifier | string;



export interface ServiceQueueItemSkipItemsUpTo$Params {
  
    /**
     * QueueItemList that should be updated
     */
    body?: QueueItemList
}

export function serviceQueueItemSkipItemsUpTo(http: HttpClient, rootUrl: string, params?: ServiceQueueItemSkipItemsUpTo$Params, context?: HttpContext): Observable<StrictHttpResponse<void>> {
  const rb = new RequestBuilder(rootUrl, serviceQueueItemSkipItemsUpTo.PATH, 'post');
  if (params) {
    rb.body(params.body, 'application/json');
  }

  return http.request(
    rb.build({ responseType: 'text', accept: '*/*', context })
  ).pipe(
    filter((r: any): r is HttpResponse<any> => r instanceof HttpResponse),
    map((r: HttpResponse<any>) => {
      return (r as HttpResponse<any>).clone({ body: undefined }) as StrictHttpResponse<void>;
    })
  );
}

serviceQueueItemSkipItemsUpTo.PATH = '/queueitem/skipitemsupto';

export { serviceQueueItemSkipItemsUpTo as skipItemsUpTo };
